// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App orchestrates all desktop services and exposes methods for frontend bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as discovery$0 from "./internal/discovery/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as notifications$0 from "../../wailsapp/wails/v3/pkg/services/notifications/models.js";

/**
 * @param {string} name
 * @param {string} host
 * @param {number} port
 * @returns {$CancellablePromise<string>}
 */
export function AddConnection(name, host, port) {
    return $Call.ByID(2802565916, name, host, port);
}

/**
 * Connect opens or focuses a window for the given connection's backend.
 * Returns true if a connection was established (new or existing), false on failure.
 * When silent is true, no "Connection Lost" notification is sent on health-check failure
 * (used for startup auto-connect where a failure is expected, not exceptional).
 * Window creation and goroutine startup happen outside the lock;
 * only the map read/write is protected by mu.
 * @param {config$0.Connection | null} conn
 * @param {boolean} silent
 * @returns {$CancellablePromise<boolean>}
 */
export function Connect(conn, silent) {
    return $Call.ByID(164877153, conn, silent);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<boolean>}
 */
export function ConnectByID(id) {
    return $Call.ByID(247129501, id);
}

/**
 * ConnectFromPicker connects to a saved connection by ID and hides the picker
 * window on success. Called from the picker frontend.
 * @param {string} id
 * @returns {$CancellablePromise<boolean>}
 */
export function ConnectFromPicker(id) {
    return $Call.ByID(2013878859, id);
}

/**
 * @param {string} host
 * @param {number} port
 * @returns {$CancellablePromise<boolean>}
 */
export function ConnectToAddress(host, port) {
    return $Call.ByID(2109971584, host, port);
}

/**
 * ConnectToAddressFromPicker connects to an address and hides the picker
 * window on success. Called from the picker frontend (manual form, discovered instances).
 * @param {string} host
 * @param {number} port
 * @returns {$CancellablePromise<boolean>}
 */
export function ConnectToAddressFromPicker(host, port) {
    return $Call.ByID(2942492226, host, port);
}

/**
 * GetActiveConnections returns the keys ("host:port") of all open connection windows.
 * Called by the picker frontend to show active state.
 * @returns {$CancellablePromise<string[]>}
 */
export function GetActiveConnections() {
    return $Call.ByID(4242594810).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<config$0.Connection[]>}
 */
export function GetConnections() {
    return $Call.ByID(1541859132).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<discovery$0.Instance[]>}
 */
export function GetDiscoveredInstances() {
    return $Call.ByID(438969147).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * MoveConnection reorders a saved connection by swapping it with its adjacent
 * neighbor: delta<0 moves it up (toward the front), delta>0 moves it down.
 * @param {string} id
 * @param {number} delta
 * @returns {$CancellablePromise<void>}
 */
export function MoveConnection(id, delta) {
    return $Call.ByID(1876798444, id, delta);
}

/**
 * RefreshTrayMenu rebuilds the tray menu with current connections.
 * INVARIANT: Must NOT be called while the caller holds a.mu.
 * @returns {$CancellablePromise<void>}
 */
export function RefreshTrayMenu() {
    return $Call.ByID(660590835);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveConnection(id) {
    return $Call.ByID(3294149945, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function SetDefaultConnection(id) {
    return $Call.ByID(3648922044, id);
}

/**
 * SetWailsApp wires Wails components after creation but before Run().
 * @param {application$0.App | null} app
 * @param {application$0.WebviewWindow | null} picker
 * @param {application$0.SystemTray | null} tray
 * @param {notifications$0.NotificationService | null} notifierSvc
 * @returns {$CancellablePromise<void>}
 */
export function SetWailsApp(app, picker, tray, notifierSvc) {
    return $Call.ByID(543693278, app, picker, tray, notifierSvc);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = config$0.Connection.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = discovery$0.Instance.createFrom;
const $$createType4 = $Create.Array($$createType3);
