/**
 * apiClient — transport-aware fetch dispatcher.
 *
 * Factory that dispatches based on the active transport kind:
 *  - 'direct': forwards to the existing apiFetch (direct TCP to Niuniu server)
 *  - 'relay':  wraps the request in Noise AEAD and sends it through the relay tunnel
 *
 * Feature flag: set RELAY_TRANSPORT_ENABLED = false to always use direct.
 */

import { apiFetch } from './client';
import {
  tunnelFetch,
  TunnelRelayError,
  type TunnelRequest,
  type TunnelResponse,
} from './relay/tunnelFetch';
import { plainTunnelFetch } from './relay/plainFetch';
import { pairKeyFetch, decodePairKey } from './relay/pairKeyFetch';
import { performHandshake } from './relay/handshake';
import { useTransportStore } from '../stores/transportStore';
import { useRelayAccountStore } from '../stores/relayAccountStore';
import { usePairedDesktopsStore, type PairedDesktop } from '../stores/pairedDesktopsStore';
import { getOrCreateIdentity } from '../crypto/identity';
import { buildDPoPHeader } from '../crypto/dpop';
import { decode as b64Decode } from '@stablelib/base64';
import { findLanEndpoint } from './lan/discover';
import { openLanTunnel, LAN_CAPABLE } from './lan/tunnel';
import { lanEncryptedRPC } from './lan/rpc';
import { fingerprintXpub } from '../crypto/fingerprint';
import type { CipherPair } from '../crypto/noise';
import type { Identity } from '../crypto/identity';

// ─── Feature flags ────────────────────────────────────────────────────────────

export const RELAY_TRANSPORT_ENABLED = true;

/**
 * Available transport modes for encrypted RPCs through the relay, plus
 * their trust models against the relay operator (TLS protects every mode
 * against external observers; the differences below are about what the
 * relay process itself can read):
 *
 *   "pairkey" — preferred. 32-byte ChaCha20-Poly1305 key generated by the
 *               relay at scan-pairing time and stored on
 *               desktop_mobile_links. Each frame carries a fresh random
 *               nonce; concurrent and out-of-order RPCs are independent
 *               (no shared cipher state). Trust model: the relay holds
 *               the key, so it CAN decrypt — the protection is against
 *               anyone between the relay process and the desktop process
 *               (TLS-WSS termination handlers, infra teams reading raw
 *               packets, etc.), not against a malicious relay operator.
 *               Falls back to `RELAY_FALLBACK_MODE` for paired desktops
 *               that predate the 008 migration and therefore have no
 *               pair_key on file.
 *   "noise"   — legacy Noise KK encrypted_rpc. The handshake derives a
 *               cipher pair the relay never sees, so this IS end-to-end
 *               against a malicious relay. Monotonic-counter cipher state
 *               makes it concurrency-fragile (2026-05-02 incident: any
 *               out-of-order decrypt poisons the desktop's CipherPair
 *               permanently with "chacha20poly1305: message authentication
 *               failed"); kept for back-compat, not the default.
 *   "plain"   — no encryption between relay and desktop. The relay sees
 *               the full payload — same trust surface as pairkey, just
 *               more obvious about it.
 */
export type RelayTransportMode = 'pairkey' | 'noise' | 'plain';

export const RELAY_TRANSPORT_MODE: RelayTransportMode = 'pairkey';

/**
 * Mode used when the configured `RELAY_TRANSPORT_MODE` is unavailable for
 * a given desktop (e.g. pairkey selected but no pair_key stored, or the
 * relay returned 409 pair_key_unprovisioned). "plain" is the safest
 * fallback for pairkey — the trust surface is identical (the relay holds
 * the pair_key in either mode), and the user's business flow keeps
 * working without a re-pair gate.
 */
export const RELAY_FALLBACK_MODE: RelayTransportMode = 'plain';

let modeOverrideForTesting: RelayTransportMode | null = null;

function activeTransportMode(): RelayTransportMode {
  return modeOverrideForTesting ?? RELAY_TRANSPORT_MODE;
}

/**
 * Test-only switch. Forces a specific transport mode regardless of the
 * production default; pass `null` to clear. Production code must not
 * call this.
 */
export function __setTransportModeForTesting(
  v: RelayTransportMode | null,
): void {
  modeOverrideForTesting = v;
}

/**
 * Back-compat for existing tests that flipped between "encrypted" and
 * "plaintext". Maps onto the new mode override:
 *   true        → 'plain'   (force plaintext)
 *   false       → 'noise'   (force legacy noise — what the encrypted-path
 *                            tests target)
 *   null        → clear override (use production default)
 *
 * @deprecated prefer `__setTransportModeForTesting`.
 */
export function __setPlaintextModeForTesting(v: boolean | null): void {
  if (v === null) {
    modeOverrideForTesting = null;
    return;
  }
  modeOverrideForTesting = v ? 'plain' : 'noise';
}

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ApiClientOptions {
  /** Override the desktop to route to (for relay transport). */
  desktopId?: string;
  /** Extra fetch options passed through to direct transport. */
  fetchOptions?: RequestInit;
}

// ─── Direct transport (thin wrapper) ─────────────────────────────────────────

export async function directFetch<T>(path: string, options: RequestInit = {}): Promise<T> {
  return apiFetch<T>(path, options);
}

// ─── Relay transport helper ───────────────────────────────────────────────────

/**
 * relayFetch — sends a request through the encrypted relay tunnel.
 *
 * On first call per desktop, lazily performs the Noise KK handshake and
 * caches the resulting CipherPair. Subsequent calls reuse the cached cipher.
 *
 * If the desktop lost its cipher cache (e.g. process restart), it responds
 * with 412 + X-Niuniu-Error: no_session. This function transparently evicts
 * the stale mobile-side cipher, re-handshakes, and retries the request once.
 *
 * Requires:
 *  1. A relay device token in pairedDesktopsStore.
 *  2. The mobile identity for DPoP signing and the Noise KK handshake.
 */
export async function relayFetch(
  desktopId: string,
  path: string,
  options: RequestInit = {},
): Promise<TunnelResponse> {
  const desktop = usePairedDesktopsStore.getState().getDesktop(desktopId);
  if (!desktop) {
    throw new Error(`relayFetch: desktop ${desktopId} not found in paired desktops`);
  }

  const { relayBaseUrl } = useRelayAccountStore.getState();
  if (!relayBaseUrl) {
    throw new Error('relayFetch: no relay base URL configured');
  }

  const identity = await getOrCreateIdentity();

  // Resolve the actual mode for this call. If pairkey is requested but the
  // pair has no key (older pair, or the relay predates the 008 migration),
  // demote to RELAY_FALLBACK_MODE so the user's business flow still works.
  let mode = activeTransportMode();
  let pairKeyBytes: Uint8Array | null = null;
  if (mode === 'pairkey') {
    pairKeyBytes = decodePairKey(desktop.pairKey);
    if (!pairKeyBytes) {
      mode = RELAY_FALLBACK_MODE;
    }
  }

  const body =
    options.body == null
      ? null
      : typeof options.body === 'string'
        ? options.body
        : options.body instanceof ArrayBuffer
          ? new Uint8Array(options.body)
          : options.body instanceof Uint8Array
            ? options.body
            : String(options.body);
  const req: TunnelRequest = {
    method: (options.method ?? 'GET').toUpperCase(),
    path,
    headers: options.headers as Record<string, string> | undefined,
    body: body as string | Uint8Array | null | undefined,
  };

  if (mode === 'pairkey' && pairKeyBytes && desktop.mobileId) {
    try {
      return await pairKeyFetch(
        relayBaseUrl,
        desktopId,
        desktop.mobileId,
        pairKeyBytes,
        req,
        desktop.relayDeviceToken,
        identity.edPriv,
      );
    } catch (err) {
      // Runtime fallback: the relay may have been rolled back to a build
      // without the 008 migration, the desktop_mobile_links row may have
      // been revoked, or this client built since the link was provisioned
      // but the row got cleaned up server-side. Either way the relay
      // signals it via X-Niuniu-Error: pair_key_unprovisioned /
      // pair_link_missing on a 409. In those cases plain mode still works,
      // so demote and retry once instead of bricking the user until they
      // re-pair.
      if (
        err instanceof TunnelRelayError &&
        err.status === 409 &&
        (err.errorCode === 'pair_key_unprovisioned' ||
          err.errorCode === 'pair_link_missing')
      ) {
        return plainTunnelFetch(
          relayBaseUrl,
          desktopId,
          req,
          desktop.relayDeviceToken,
          identity.edPriv,
        );
      }
      throw err;
    }
  }

  if (mode === 'pairkey' /* missing mobileId */) {
    // Anomaly: pair has a key but no mobileId in store. addDesktop sets
    // mobileId at pair time so this only appears on stores from older
    // builds. Surface so we can find and fix the upgrade path; meanwhile
    // fall back rather than blocking the user.
    console.warn(
      `[smartFetch] pair ${desktopId} has pairKey but no mobileId — falling back to plain. Re-pair to provision.`,
    );
  }

  if (mode === 'plain' || mode === 'pairkey') {
    return plainTunnelFetch(
      relayBaseUrl,
      desktopId,
      req,
      desktop.relayDeviceToken,
      identity.edPriv,
    );
  }

  // mode === 'noise' — legacy Noise KK path with 412 retry. Noise's CipherPair
  // has a single monotonic nonce counter and requires strict in-order
  // encrypt/decrypt — so this branch (and only this branch) goes through the
  // per-desktop serial queue. pairkey/plain above are stateless AEAD or
  // unencrypted and run concurrently.
  return enqueueForDesktop(desktopId, async () => {
    try {
      return await sendViaRelay(relayBaseUrl, desktopId, desktop, identity, path, options);
    } catch (err) {
      if (
        err instanceof TunnelRelayError &&
        err.status === 412 &&
        err.errorCode === 'no_session'
      ) {
        // Desktop has no cipher session for us — our cached cipher is stale.
        // Evict it so the next attempt re-runs the Noise KK handshake, then retry once.
        useTransportStore.getState().removeCipher(desktopId);
        return await sendViaRelay(relayBaseUrl, desktopId, desktop, identity, path, options);
      }
      throw err;
    }
  });
}

// Deduplicates concurrent Noise KK handshakes for the same desktop. Without
// this, N parallel relayFetch calls on a cold cache would each kick off their
// own handshake → desktop stores only the last, mobile stores whichever
// setCipher ran last, and the mismatch produces chacha20poly1305 AEAD failures
// on every subsequent RPC (desktop logs: "encrypted_rpc: decrypt failed").
const inflightHandshakes = new Map<string, Promise<CipherPair>>();

async function ensureCipher(
  relayBaseUrl: string,
  desktopId: string,
  desktop: PairedDesktop,
  identity: Identity,
): Promise<CipherPair> {
  const store = useTransportStore.getState();
  const existing = store.getCipher(desktopId);
  if (existing) return existing;

  const inflight = inflightHandshakes.get(desktopId);
  if (inflight) return inflight;

  const promise = (async (): Promise<CipherPair> => {
    try {
      const desktopXpubBytes = b64Decode(desktop.xpub);
      const deviceTokenBytes = new TextEncoder().encode(desktop.relayDeviceToken);
      const dpop = buildDPoPHeader(
        identity.edPriv,
        deviceTokenBytes,
        'POST',
        `/d/${desktopId}/crypto/handshake`,
      );
      const cipher = await performHandshake(
        relayBaseUrl,
        desktopId,
        identity,
        desktopXpubBytes,
        desktop.relayDeviceToken,
        dpop,
      );
      useTransportStore.getState().setCipher(desktopId, cipher);
      return cipher;
    } finally {
      inflightHandshakes.delete(desktopId);
    }
  })();
  inflightHandshakes.set(desktopId, promise);
  return promise;
}

async function sendViaRelay(
  relayBaseUrl: string,
  desktopId: string,
  desktop: PairedDesktop,
  identity: Awaited<ReturnType<typeof getOrCreateIdentity>>,
  path: string,
  options: RequestInit,
): Promise<TunnelResponse> {
  const cipher = await ensureCipher(relayBaseUrl, desktopId, desktop, identity);

  const body =
    options.body == null
      ? null
      : typeof options.body === 'string'
        ? options.body
        : options.body instanceof ArrayBuffer
          ? new Uint8Array(options.body)
          : options.body instanceof Uint8Array
            ? options.body
            : String(options.body);

  const req: TunnelRequest = {
    method: (options.method ?? 'GET').toUpperCase(),
    path,
    headers: options.headers as Record<string, string> | undefined,
    body: body as string | Uint8Array | null | undefined,
  };

  return tunnelFetch(
    relayBaseUrl,
    desktopId,
    req,
    cipher,
    desktop.relayDeviceToken,
    identity.edPriv,
  );
}

// ─── Per-desktop encrypted-RPC serial queue ─────────────────────────────────
//
// Noise transport ciphers (both relay-noise mode and LAN's encrypted_rpc)
// maintain a single send/recv nonce counter and require monotonic, in-order
// delivery: encrypt N must be decrypted before encrypt N+1, full stop. If
// two encrypted RPCs run concurrently against the same Noise CipherPair:
//   1. encrypts have overlapping or out-of-order nonces, AND
//   2. arrive at the desktop as parallel yamux streams that hit the cipher
//      in scheduler-determined order, NOT the order they were sent.
// The desktop's `cp.Decrypt` then fails with "chacha20poly1305: message
// authentication failed" on every frame whose nonce doesn't match the
// recv counter — and `flynn/noise.CipherState` flips to permanently
// invalid on the first failure, so once one RPC fails, every subsequent
// RPC on the same cipher fails too.
//
// Scope: this queue ONLY wraps the two transports that actually need it:
//   * relay-noise mode (inside `relayFetch`).
//   * LAN encrypted_rpc (inside `smartFetchEncrypted`).
// pairkey and plain are stateless AEAD / unencrypted respectively and run
// concurrently — they call into this module without ever entering the
// queue, so a burst of pairkey RPCs against one desktop hits the relay in
// parallel like any normal HTTP client.
const desktopChainTail: Map<string, Promise<unknown>> = new Map();

async function enqueueForDesktop<T>(
  desktopId: string,
  fn: () => Promise<T>,
): Promise<T> {
  const prev = desktopChainTail.get(desktopId) ?? Promise.resolve();
  // Run after the predecessor settles, regardless of success/failure — one
  // failed RPC must not strand the queue.
  const next = prev.then(fn, fn);
  desktopChainTail.set(desktopId, next);
  // Free the slot once this promise is the chain tail, so unrelated future
  // calls don't observe a stale rejection. The .then with a noop catch is
  // intentional — using .finally would propagate the underlying rejection
  // to a side-channel promise that nothing awaits, surfacing as an
  // "unhandled promise rejection" even though `next` itself IS awaited by
  // the caller.
  next.then(
    () => {
      if (desktopChainTail.get(desktopId) === next) {
        desktopChainTail.delete(desktopId);
      }
    },
    () => {
      if (desktopChainTail.get(desktopId) === next) {
        desktopChainTail.delete(desktopId);
      }
    },
  );
  return next;
}

/**
 * Test-only helper: clears the per-desktop encrypted-RPC serialization queue
 * so a fresh test starts without inheriting unsettled or just-resolved
 * predecessor promises from earlier tests. Production code never calls this.
 */
export function __resetEncryptedQueueForTesting(): void {
  desktopChainTail.clear();
}

// ─── LAN endpoint cache (background-probe) ──────────────────────────────────
//
// Original design ran `findLanEndpoint(desktop, 3000)` on every API call
// inside `smartFetchEncrypted`. When the desktop's `lastKnownLanEndpoints`
// existed but were unreachable (typical "moved off home Wi-Fi onto cellular"
// case), every call paid the full 3 s probe timeout before falling back to
// relay. Even with negative caching that was still 3 s on the first call
// after every cache expiry.
//
// New design: keep the probe entirely off the request path. Each request
// just reads this cache:
//   * `hit`  → use the cached LAN endpoint (LAN RPC still goes through the
//              per-desktop queue because it's Noise KK).
//   * `miss` → cached "no LAN" verdict, skip LAN, go relay; no probe spawned.
//   * none   → no verdict yet; spawn a background probe for next time and
//              go relay this round.
//
// The probe runs as a fire-and-forget IIFE; results land in the cache when
// they arrive. NetInfo's network-change handler wipes the cache so the next
// request after a network transition re-probes instead of trusting a verdict
// from the previous network.
//
// TTLs:
//   * hit  TTL 30 s — DHCP renewals / IP rotation can move the desktop's
//          IP, so a positive verdict shouldn't outlive a typical lease cycle.
//   * miss TTL 60 s — long enough to avoid hot-looping probes when the user
//          is genuinely off the desktop's LAN, short enough to recover when
//          the LAN comes back without a NetInfo signal.
type LanCacheEntry =
  | { kind: 'hit'; endpoint: { host: string; port: number }; until: number }
  | { kind: 'miss'; until: number };

const LAN_CACHE_HIT_TTL_MS = 30_000;
const LAN_CACHE_MISS_TTL_MS = 60_000;
const lanEndpointCache: Map<string, LanCacheEntry> = new Map();
const inflightLanProbes: Map<string, Promise<void>> = new Map();

// Bumped by the NetInfo handler. A probe records the generation it was
// started under and discards its own result on completion if it has changed
// — otherwise a probe-in-flight from the old network would overwrite the
// just-cleared cache with a stale verdict.
let probeGeneration = 0;

function getLanCache(desktopId: string): LanCacheEntry | null {
  const e = lanEndpointCache.get(desktopId);
  if (!e) return null;
  if (Date.now() >= e.until) {
    lanEndpointCache.delete(desktopId);
    return null;
  }
  return e;
}

function setLanCacheHit(
  desktopId: string,
  endpoint: { host: string; port: number },
): void {
  lanEndpointCache.set(desktopId, {
    kind: 'hit',
    endpoint,
    until: Date.now() + LAN_CACHE_HIT_TTL_MS,
  });
}

function setLanCacheMiss(desktopId: string): void {
  lanEndpointCache.set(desktopId, {
    kind: 'miss',
    until: Date.now() + LAN_CACHE_MISS_TTL_MS,
  });
}

/**
 * Kicks off a LAN endpoint probe in the background. Idempotent per desktopId
 * — a second call while a probe is already inflight is a no-op. Result lands
 * in `lanEndpointCache`; the calling request never awaits this.
 */
function kickLanProbeInBackground(desktopId: string): void {
  if (inflightLanProbes.has(desktopId)) return;
  const desktop = usePairedDesktopsStore.getState().getDesktop(desktopId);
  if (!desktop) return;

  const myGeneration = probeGeneration;
  // Box around the promise so the IIFE's `finally` can identity-check
  // against "the promise this kick produced" without TS tripping on a
  // self-referential `const promise = (async () => { ... promise ... })()`.
  // By the time `finally` runs, slot.promise has been assigned.
  const slot: { promise: Promise<void> | null } = { promise: null };
  slot.promise = (async () => {
    try {
      const endpoint = await findLanEndpoint(desktop, 3000);
      // Network changed mid-probe — verdict is stale, drop it on the floor.
      if (myGeneration !== probeGeneration) return;
      if (endpoint) {
        setLanCacheHit(desktopId, endpoint);
        usePairedDesktopsStore
          .getState()
          .recordLanEndpoint(desktopId, endpoint);
      } else {
        setLanCacheMiss(desktopId);
      }
    } catch {
      if (myGeneration !== probeGeneration) return;
      setLanCacheMiss(desktopId);
    } finally {
      // Identity check: a NetInfo change may have cleared the inflight map
      // and a fresh probe may already own the slot. Don't evict someone
      // else's entry.
      if (inflightLanProbes.get(desktopId) === slot.promise) {
        inflightLanProbes.delete(desktopId);
      }
    }
  })();
  inflightLanProbes.set(desktopId, slot.promise);
}

/**
 * Test-only helper: clears both the verdict cache and the inflight probe
 * map so a fresh test starts without inheriting state from earlier ones.
 * Also bumps `probeGeneration` so any in-flight probe from a prior test
 * has its result discarded.
 */
export function __resetLanCacheForTesting(): void {
  lanEndpointCache.clear();
  inflightLanProbes.clear();
  probeGeneration++;
}

/**
 * Test-only helper: awaits all currently-inflight background probes. Call
 * this after issuing a `smartFetch` and before asserting on probe-related
 * mocks, otherwise the probe's microtask may not have settled yet.
 */
export async function __waitForInflightLanProbesForTesting(): Promise<void> {
  await Promise.allSettled([...inflightLanProbes.values()]);
}

// Wire NetInfo to invalidate the LAN endpoint cache the moment the device
// changes networks. Without this, a 'hit' verdict captured on home Wi-Fi
// would survive the switch to cellular and the next request would try to
// open a tunnel to an unreachable 192.168.x.x; conversely a 'miss' captured
// on cellular would block the LAN fast path even after the user rejoined
// the desktop's network. The listener fires on connection-type / SSID
// transitions so the next request after the change starts from a clean
// slate (and may kick a fresh background probe).
//
// require()'d in a try/catch so tests that don't mock NetInfo still load
// this module cleanly: a missing native binding becomes a no-op and the
// per-entry TTLs (30 s hit, 60 s miss) remain the only safety net.
let netInfoUnsubscribe: (() => void) | null = null;

function subscribeToNetworkChanges(): void {
  if (netInfoUnsubscribe) return;
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const NetInfo = require('@react-native-community/netinfo').default;
    netInfoUnsubscribe = NetInfo.addEventListener(() => {
      lanEndpointCache.clear();
      // Allow a fresh probe to start immediately on the new network.
      // The old in-flight probe will still complete; its generation token
      // check in `kickLanProbeInBackground` ensures it does not write its
      // stale verdict to the freshly-cleared cache.
      inflightLanProbes.clear();
      probeGeneration++;
    });
  } catch {
    // Module not linked in this build (e.g. Expo Go without the native
    // binding) — fall back to the time-based recovery window.
  }
}

subscribeToNetworkChanges();

/**
 * Test-only helper: tears down the NetInfo listener so a test that mocks
 * NetInfo can install its own fresh subscription and observe behaviour
 * without a leftover one from module load.
 */
export function __resetNetInfoForTesting(): void {
  if (netInfoUnsubscribe) {
    netInfoUnsubscribe();
    netInfoUnsubscribe = null;
  }
}

/**
 * Test-only helper: re-runs the NetInfo subscription bootstrap. Pair with
 * `__resetNetInfoForTesting` and a `jest.mock('@react-native-community/
 * netinfo', ...)` to verify the wiring.
 */
export function __subscribeToNetworkChangesForTesting(): void {
  subscribeToNetworkChanges();
}

// ─── Unified dispatcher ───────────────────────────────────────────────────────

/**
 * smartFetch — dispatches to LAN direct, relay, or direct transport based on
 * current store state and LAN availability.
 *
 * LAN fast-path (when LAN_CAPABLE and relay transport is active):
 *   1. Probe for a reachable LAN endpoint.
 *   2. Reuse a cached YamuxSession tunnel if available; otherwise open one.
 *   3. Send the request as a Noise-encrypted RPC over a yamux stream.
 *   4. Map the result back to a Response-compatible object.
 *
 * Falls back to relay on any LAN failure.
 *
 * All encrypted paths (LAN + relay) are funnelled through `enqueueForDesktop`
 * so concurrent callers serialize per desktop — see the long comment on
 * `desktopChainTail` for why.
 */
export async function smartFetch<T>(
  path: string,
  options: RequestInit & { desktopId?: string } = {},
): Promise<T> {
  if (!RELAY_TRANSPORT_ENABLED) {
    return directFetch<T>(path, options);
  }

  const { activeTransportKind } = useTransportStore.getState();
  const { desktopId, ...fetchOpts } = options;

  if (activeTransportKind === 'relay' && desktopId) {
    // No top-level queue: pairkey + plain transports use stateless AEAD
    // (or no encryption) and are inherently concurrent-safe. The serial
    // queue is now scoped to the two transports that actually need it
    // (relay-noise inside relayFetch, LAN inside smartFetchEncrypted),
    // so a burst of pairkey calls runs in parallel like any normal HTTP
    // client.
    return smartFetchEncrypted<T>(path, fetchOpts, desktopId);
  }

  return directFetch<T>(path, fetchOpts);
}

async function smartFetchEncrypted<T>(
  path: string,
  fetchOpts: RequestInit,
  desktopId: string,
): Promise<T> {
  // ── LAN fast-path (cache-only, never blocks the request) ─────────────────
  // LAN's CipherPair (Noise KK) has the same monotonic-counter limitation
  // that bit the relay-noise path, so the LAN RPC itself still goes through
  // `enqueueForDesktop`. What's gone is the in-request `findLanEndpoint`
  // probe — it now runs in the background (see `kickLanProbeInBackground`)
  // and its verdict lands in `lanEndpointCache`. The dispatcher just reads
  // that cache:
  //
  //   * verdict 'hit'  → use the cached endpoint, run LAN RPC under queue.
  //   * verdict 'miss' → skip LAN, go relay, no probe.
  //   * no verdict     → kick a background probe for next time, go relay
  //                       this round.
  //
  // First request after a cold cache (or after a NetInfo network-change
  // event clears it) is therefore always relay, but it returns immediately
  // — no 3 s probe wait — and subsequent requests pick up the LAN fast
  // path as soon as the background probe answers.
  if (LAN_CAPABLE) {
    const cached = getLanCache(desktopId);
    if (cached?.kind === 'hit') {
      try {
        return await enqueueForDesktop(desktopId, () =>
          runLanRpc<T>(desktopId, cached.endpoint, path, fetchOpts),
        );
      } catch (lanErr) {
        // Tunnel error or AEAD failure on a cached endpoint — invalidate the
        // hit so the next request doesn't re-open the same broken tunnel,
        // and fall through to relay.
        console.warn(
          `[smartFetch] LAN RPC failed for ${desktopId}, falling back to relay:`,
          lanErr,
        );
        useTransportStore.getState().removeLanHandle(desktopId);
        setLanCacheMiss(desktopId);
      }
    } else if (!cached) {
      // No verdict yet — fire a probe for next time. Don't await it.
      kickLanProbeInBackground(desktopId);
    }
    // cached?.kind === 'miss' → fall straight through, no probe.
  }

  // ── Relay path ─────────────────────────────────────────────────────────────
  const tunnelRes = await relayFetch(desktopId, path, fetchOpts);
  if (!tunnelRes.ok) {
    throw new Error(
      `smartFetch(relay): remote error ${tunnelRes.status}: ${tunnelRes.body}`,
    );
  }
  if (!tunnelRes.body) return undefined as T;
  return JSON.parse(tunnelRes.body) as T;
}

async function runLanRpc<T>(
  desktopId: string,
  endpoint: { host: string; port: number },
  path: string,
  fetchOpts: RequestInit,
): Promise<T> {
  const desktop = usePairedDesktopsStore.getState().getDesktop(desktopId);
  if (!desktop) {
    throw new Error(`runLanRpc: desktop ${desktopId} not found`);
  }
  const identity = await getOrCreateIdentity();

  // Reuse cached LAN tunnel if any
  let handle = useTransportStore.getState().getLanHandle(desktopId);
  if (!handle) {
    handle = await openLanTunnel({ desktop, endpoint, identity });
    useTransportStore.getState().setLanHandle(desktopId, handle);
  }

  const mobileId = 'lan:' + fingerprintXpub(identity.xPub);

  const bodyBytes =
    fetchOpts.body == null
      ? undefined
      : typeof fetchOpts.body === 'string'
        ? new TextEncoder().encode(fetchOpts.body)
        : fetchOpts.body instanceof Uint8Array
          ? fetchOpts.body
          : fetchOpts.body instanceof ArrayBuffer
            ? new Uint8Array(fetchOpts.body)
            : new TextEncoder().encode(String(fetchOpts.body));

  const rawHeaders = fetchOpts.headers as Record<string, string> | undefined;
  const headersMap: Record<string, string[]> = {};
  if (rawHeaders) {
    for (const [k, v] of Object.entries(rawHeaders)) {
      headersMap[k] = [v];
    }
  }

  const result = await lanEncryptedRPC({
    tunnel: handle,
    mobileId,
    method: (fetchOpts.method ?? 'GET').toUpperCase(),
    path,
    headers: headersMap,
    body: bodyBytes,
  });

  if (result.status >= 400) {
    throw new Error(`smartFetch(lan): remote error ${result.status}`);
  }
  if (!result.body || result.body.length === 0) return undefined as T;
  return JSON.parse(new TextDecoder().decode(result.body)) as T;
}
