// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents_owner_filter.sql

package store

import (
	"context"
	"strings"
)

const listAgentsForOwners = `-- name: ListAgentsForOwners :many
SELECT id, name, description, dir_path, file_hash, source_url, driver, capabilities, owner_type, owner_id, created_at, updated_at FROM agents
WHERE (owner_type = 'user' AND owner_id = ?)
   OR (owner_type = 'org'  AND owner_id IN (/*SLICE:org_ids*/?))
ORDER BY created_at DESC
`

type ListAgentsForOwnersParams struct {
	OwnerID int64   `json:"owner_id"`
	OrgIds  []int64 `json:"org_ids"`
}

func (q *Queries) ListAgentsForOwners(ctx context.Context, arg ListAgentsForOwnersParams) ([]Agent, error) {
	query := listAgentsForOwners
	var queryParams []interface{}
	queryParams = append(queryParams, arg.OwnerID)
	if len(arg.OrgIds) > 0 {
		for _, v := range arg.OrgIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:org_ids*/?", strings.Repeat(",?", len(arg.OrgIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:org_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DirPath,
			&i.FileHash,
			&i.SourceUrl,
			&i.Driver,
			&i.Capabilities,
			&i.OwnerType,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
