// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_messages.sql

package store

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const countAgentMessages = `-- name: CountAgentMessages :one
SELECT COUNT(*) FROM agent_messages
WHERE workspace_id = ?
`

func (q *Queries) CountAgentMessages(ctx context.Context, workspaceID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAgentMessages, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgentMessage = `-- name: CreateAgentMessage :exec
INSERT INTO agent_messages (id, workspace_id, role, content, message_id, event_type, tool_name, tool_input, tool_use_id, is_error, cost_usd, num_turns, duration_ms, input_tokens, output_tokens, harness_run_id, attachments, workspace_agent_id, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
`

type CreateAgentMessageParams struct {
	ID               string          `json:"id"`
	WorkspaceID      int64           `json:"workspace_id"`
	Role             string          `json:"role"`
	Content          string          `json:"content"`
	MessageID        string          `json:"message_id"`
	EventType        string          `json:"event_type"`
	ToolName         sql.NullString  `json:"tool_name"`
	ToolInput        sql.NullString  `json:"tool_input"`
	ToolUseID        sql.NullString  `json:"tool_use_id"`
	IsError          int64           `json:"is_error"`
	CostUsd          sql.NullFloat64 `json:"cost_usd"`
	NumTurns         sql.NullInt64   `json:"num_turns"`
	DurationMs       sql.NullInt64   `json:"duration_ms"`
	InputTokens      sql.NullInt64   `json:"input_tokens"`
	OutputTokens     sql.NullInt64   `json:"output_tokens"`
	HarnessRunID     sql.NullInt64   `json:"harness_run_id"`
	Attachments      sql.NullString  `json:"attachments"`
	WorkspaceAgentID sql.NullInt64   `json:"workspace_agent_id"`
}

func (q *Queries) CreateAgentMessage(ctx context.Context, arg CreateAgentMessageParams) error {
	_, err := q.db.ExecContext(ctx, createAgentMessage,
		arg.ID,
		arg.WorkspaceID,
		arg.Role,
		arg.Content,
		arg.MessageID,
		arg.EventType,
		arg.ToolName,
		arg.ToolInput,
		arg.ToolUseID,
		arg.IsError,
		arg.CostUsd,
		arg.NumTurns,
		arg.DurationMs,
		arg.InputTokens,
		arg.OutputTokens,
		arg.HarnessRunID,
		arg.Attachments,
		arg.WorkspaceAgentID,
	)
	return err
}

const getAgentMessage = `-- name: GetAgentMessage :one
SELECT id, workspace_id, role, content, message_id, event_type, tool_name, tool_input, tool_use_id, is_error, cost_usd, num_turns, duration_ms, input_tokens, output_tokens, harness_run_id, attachments, workspace_agent_id, created_at FROM agent_messages
WHERE id = ?
`

func (q *Queries) GetAgentMessage(ctx context.Context, id string) (AgentMessage, error) {
	row := q.db.QueryRowContext(ctx, getAgentMessage, id)
	var i AgentMessage
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Role,
		&i.Content,
		&i.MessageID,
		&i.EventType,
		&i.ToolName,
		&i.ToolInput,
		&i.ToolUseID,
		&i.IsError,
		&i.CostUsd,
		&i.NumTurns,
		&i.DurationMs,
		&i.InputTokens,
		&i.OutputTokens,
		&i.HarnessRunID,
		&i.Attachments,
		&i.WorkspaceAgentID,
		&i.CreatedAt,
	)
	return i, err
}

const getLastAgentMessage = `-- name: GetLastAgentMessage :one
SELECT id, workspace_id, role, content, message_id, event_type, tool_name, tool_input, tool_use_id, is_error, cost_usd, num_turns, duration_ms, input_tokens, output_tokens, harness_run_id, attachments, workspace_agent_id, created_at FROM agent_messages
WHERE workspace_id = ?
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLastAgentMessage(ctx context.Context, workspaceID int64) (AgentMessage, error) {
	row := q.db.QueryRowContext(ctx, getLastAgentMessage, workspaceID)
	var i AgentMessage
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Role,
		&i.Content,
		&i.MessageID,
		&i.EventType,
		&i.ToolName,
		&i.ToolInput,
		&i.ToolUseID,
		&i.IsError,
		&i.CostUsd,
		&i.NumTurns,
		&i.DurationMs,
		&i.InputTokens,
		&i.OutputTokens,
		&i.HarnessRunID,
		&i.Attachments,
		&i.WorkspaceAgentID,
		&i.CreatedAt,
	)
	return i, err
}

const latestMessagePerAgent = `-- name: LatestMessagePerAgent :many
SELECT am.id, am.workspace_id, am.role, am.content, am.message_id, am.event_type, am.tool_name, am.tool_input, am.tool_use_id, am.is_error, am.cost_usd, am.num_turns, am.duration_ms, am.input_tokens, am.output_tokens, am.harness_run_id, am.attachments, am.workspace_agent_id, am.created_at
FROM agent_messages am
WHERE am.workspace_id = ?
  AND am.workspace_agent_id IS NOT NULL
  AND am.id = (
    SELECT am2.id FROM agent_messages am2
    WHERE am2.workspace_id = am.workspace_id
      AND am2.workspace_agent_id = am.workspace_agent_id
    ORDER BY am2.created_at DESC, am2.id DESC
    LIMIT 1
  )
`

func (q *Queries) LatestMessagePerAgent(ctx context.Context, workspaceID int64) ([]AgentMessage, error) {
	rows, err := q.db.QueryContext(ctx, latestMessagePerAgent, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMessage{}
	for rows.Next() {
		var i AgentMessage
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Role,
			&i.Content,
			&i.MessageID,
			&i.EventType,
			&i.ToolName,
			&i.ToolInput,
			&i.ToolUseID,
			&i.IsError,
			&i.CostUsd,
			&i.NumTurns,
			&i.DurationMs,
			&i.InputTokens,
			&i.OutputTokens,
			&i.HarnessRunID,
			&i.Attachments,
			&i.WorkspaceAgentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentMessages = `-- name: ListAgentMessages :many
SELECT id, workspace_id, role, content, message_id, event_type, tool_name, tool_input, tool_use_id, is_error, cost_usd, num_turns, duration_ms, input_tokens, output_tokens, harness_run_id, attachments, workspace_agent_id, created_at FROM agent_messages
WHERE workspace_id = ?
ORDER BY created_at ASC, id ASC
LIMIT ? OFFSET ?
`

type ListAgentMessagesParams struct {
	WorkspaceID int64 `json:"workspace_id"`
	Limit       int64 `json:"limit"`
	Offset      int64 `json:"offset"`
}

func (q *Queries) ListAgentMessages(ctx context.Context, arg ListAgentMessagesParams) ([]AgentMessage, error) {
	rows, err := q.db.QueryContext(ctx, listAgentMessages, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMessage{}
	for rows.Next() {
		var i AgentMessage
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Role,
			&i.Content,
			&i.MessageID,
			&i.EventType,
			&i.ToolName,
			&i.ToolInput,
			&i.ToolUseID,
			&i.IsError,
			&i.CostUsd,
			&i.NumTurns,
			&i.DurationMs,
			&i.InputTokens,
			&i.OutputTokens,
			&i.HarnessRunID,
			&i.Attachments,
			&i.WorkspaceAgentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentMessagesAfter = `-- name: ListAgentMessagesAfter :many
SELECT am.id, am.workspace_id, am.role, am.content, am.message_id, am.event_type, am.tool_name, am.tool_input, am.tool_use_id, am.is_error, am.cost_usd, am.num_turns, am.duration_ms, am.input_tokens, am.output_tokens, am.harness_run_id, am.attachments, am.workspace_agent_id, am.created_at FROM agent_messages am
WHERE am.workspace_id = ?
  AND (am.created_at > (SELECT am2.created_at FROM agent_messages am2 WHERE am2.id = ?)
       OR (am.created_at = (SELECT am2.created_at FROM agent_messages am2 WHERE am2.id = ?) AND am.id > ?))
ORDER BY am.created_at ASC, am.id ASC
LIMIT ?
`

type ListAgentMessagesAfterParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	ID          string `json:"id"`
	ID_2        string `json:"id_2"`
	ID_3        string `json:"id_3"`
	Limit       int64  `json:"limit"`
}

func (q *Queries) ListAgentMessagesAfter(ctx context.Context, arg ListAgentMessagesAfterParams) ([]AgentMessage, error) {
	rows, err := q.db.QueryContext(ctx, listAgentMessagesAfter,
		arg.WorkspaceID,
		arg.ID,
		arg.ID_2,
		arg.ID_3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMessage{}
	for rows.Next() {
		var i AgentMessage
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Role,
			&i.Content,
			&i.MessageID,
			&i.EventType,
			&i.ToolName,
			&i.ToolInput,
			&i.ToolUseID,
			&i.IsError,
			&i.CostUsd,
			&i.NumTurns,
			&i.DurationMs,
			&i.InputTokens,
			&i.OutputTokens,
			&i.HarnessRunID,
			&i.Attachments,
			&i.WorkspaceAgentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentMessagesBefore = `-- name: ListAgentMessagesBefore :many
SELECT id, workspace_id, role, content, message_id, event_type, tool_name, tool_input, tool_use_id, is_error, cost_usd, num_turns, duration_ms, input_tokens, output_tokens, harness_run_id, attachments, workspace_agent_id, created_at FROM (
    SELECT am.id, am.workspace_id, am.role, am.content, am.message_id, am.event_type, am.tool_name, am.tool_input, am.tool_use_id, am.is_error, am.cost_usd, am.num_turns, am.duration_ms, am.input_tokens, am.output_tokens, am.harness_run_id, am.attachments, am.workspace_agent_id, am.created_at FROM agent_messages am
    WHERE am.workspace_id = ?
      AND (am.created_at < (SELECT am2.created_at FROM agent_messages am2 WHERE am2.id = ?)
           OR (am.created_at = (SELECT am2.created_at FROM agent_messages am2 WHERE am2.id = ?) AND am.id < ?))
    ORDER BY am.created_at DESC, am.id DESC
    LIMIT ?
) ORDER BY created_at ASC, id ASC
`

type ListAgentMessagesBeforeParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	ID          string `json:"id"`
	ID_2        string `json:"id_2"`
	ID_3        string `json:"id_3"`
	Limit       int64  `json:"limit"`
}

func (q *Queries) ListAgentMessagesBefore(ctx context.Context, arg ListAgentMessagesBeforeParams) ([]AgentMessage, error) {
	rows, err := q.db.QueryContext(ctx, listAgentMessagesBefore,
		arg.WorkspaceID,
		arg.ID,
		arg.ID_2,
		arg.ID_3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMessage{}
	for rows.Next() {
		var i AgentMessage
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Role,
			&i.Content,
			&i.MessageID,
			&i.EventType,
			&i.ToolName,
			&i.ToolInput,
			&i.ToolUseID,
			&i.IsError,
			&i.CostUsd,
			&i.NumTurns,
			&i.DurationMs,
			&i.InputTokens,
			&i.OutputTokens,
			&i.HarnessRunID,
			&i.Attachments,
			&i.WorkspaceAgentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentMessagesByAgent = `-- name: ListAgentMessagesByAgent :many
SELECT id, workspace_id, role, content, message_id, event_type, tool_name, tool_input, tool_use_id, is_error, cost_usd, num_turns, duration_ms, input_tokens, output_tokens, harness_run_id, attachments, workspace_agent_id, created_at FROM agent_messages
WHERE workspace_id = ? AND workspace_agent_id = ?
ORDER BY created_at DESC, id DESC
LIMIT ?
`

type ListAgentMessagesByAgentParams struct {
	WorkspaceID      int64         `json:"workspace_id"`
	WorkspaceAgentID sql.NullInt64 `json:"workspace_agent_id"`
	Limit            int64         `json:"limit"`
}

func (q *Queries) ListAgentMessagesByAgent(ctx context.Context, arg ListAgentMessagesByAgentParams) ([]AgentMessage, error) {
	rows, err := q.db.QueryContext(ctx, listAgentMessagesByAgent, arg.WorkspaceID, arg.WorkspaceAgentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMessage{}
	for rows.Next() {
		var i AgentMessage
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Role,
			&i.Content,
			&i.MessageID,
			&i.EventType,
			&i.ToolName,
			&i.ToolInput,
			&i.ToolUseID,
			&i.IsError,
			&i.CostUsd,
			&i.NumTurns,
			&i.DurationMs,
			&i.InputTokens,
			&i.OutputTokens,
			&i.HarnessRunID,
			&i.Attachments,
			&i.WorkspaceAgentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentMessagesLatest = `-- name: ListAgentMessagesLatest :many
SELECT id, workspace_id, role, content, message_id, event_type, tool_name, tool_input, tool_use_id, is_error, cost_usd, num_turns, duration_ms, input_tokens, output_tokens, harness_run_id, attachments, workspace_agent_id, created_at FROM (
    SELECT id, workspace_id, role, content, message_id, event_type, tool_name, tool_input, tool_use_id, is_error, cost_usd, num_turns, duration_ms, input_tokens, output_tokens, harness_run_id, attachments, workspace_agent_id, created_at FROM agent_messages
    WHERE workspace_id = ?
    ORDER BY created_at DESC, id DESC
    LIMIT ?
) ORDER BY created_at ASC, id ASC
`

type ListAgentMessagesLatestParams struct {
	WorkspaceID int64 `json:"workspace_id"`
	Limit       int64 `json:"limit"`
}

func (q *Queries) ListAgentMessagesLatest(ctx context.Context, arg ListAgentMessagesLatestParams) ([]AgentMessage, error) {
	rows, err := q.db.QueryContext(ctx, listAgentMessagesLatest, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMessage{}
	for rows.Next() {
		var i AgentMessage
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Role,
			&i.Content,
			&i.MessageID,
			&i.EventType,
			&i.ToolName,
			&i.ToolInput,
			&i.ToolUseID,
			&i.IsError,
			&i.CostUsd,
			&i.NumTurns,
			&i.DurationMs,
			&i.InputTokens,
			&i.OutputTokens,
			&i.HarnessRunID,
			&i.Attachments,
			&i.WorkspaceAgentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAgentMessages = `-- name: PruneAgentMessages :exec
DELETE FROM agent_messages
WHERE workspace_id IN (SELECT id FROM workspaces WHERE is_archived = 1)
  AND agent_messages.created_at < ?
`

// Delete messages older than cutoff for archived workspaces (retention policy).
func (q *Queries) PruneAgentMessages(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.ExecContext(ctx, pruneAgentMessages, createdAt)
	return err
}

const pruneOrphanedAgentMessages = `-- name: PruneOrphanedAgentMessages :exec
DELETE FROM agent_messages WHERE workspace_id NOT IN (SELECT id FROM workspaces)
`

// Delete agent_messages whose workspace no longer exists.
// Handles rows left behind by older versions where foreign_keys was disabled.
func (q *Queries) PruneOrphanedAgentMessages(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, pruneOrphanedAgentMessages)
	return err
}

const searchWorkspaceIDsByUserContentForOwners = `-- name: SearchWorkspaceIDsByUserContentForOwners :many
SELECT DISTINCT w.id
FROM agent_messages m
JOIN workspaces w ON w.id = m.workspace_id
WHERE w.is_archived = 0
  AND m.role = 'user'
  AND m.event_type = 'text'
  AND LOWER(m.content) LIKE LOWER(?)
  AND ((w.owner_type = 'user' AND w.owner_id = ?)
    OR (w.owner_type = 'org'  AND w.owner_id IN (/*SLICE:org_ids*/?)))
ORDER BY w.id
`

type SearchWorkspaceIDsByUserContentForOwnersParams struct {
	LOWER   string  `json:"LOWER"`
	OwnerID int64   `json:"owner_id"`
	OrgIds  []int64 `json:"org_ids"`
}

// Distinct workspace IDs (within the caller's accessible scope) that contain at
// least one user-authored chat message whose text content matches the keyword.
// role='user' selects messages the human sent (assistant/tool output excluded);
// event_type='text' skips tool_use/thinking/system rows. No ESCAPE clause (sqlc
// parser limitation); user wildcards %,_ match as SQL wildcards (same as user
// search). Caller pre-narrows scope via authz to avoid cross-owner leaks.
func (q *Queries) SearchWorkspaceIDsByUserContentForOwners(ctx context.Context, arg SearchWorkspaceIDsByUserContentForOwnersParams) ([]int64, error) {
	query := searchWorkspaceIDsByUserContentForOwners
	var queryParams []interface{}
	queryParams = append(queryParams, arg.LOWER)
	queryParams = append(queryParams, arg.OwnerID)
	if len(arg.OrgIds) > 0 {
		for _, v := range arg.OrgIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:org_ids*/?", strings.Repeat(",?", len(arg.OrgIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:org_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
