// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ask_user.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const cancelAllPendingAskUserRequests = `-- name: CancelAllPendingAskUserRequests :many
UPDATE agent_ask_user_requests
   SET status = 'cancelled',
       decision_source = 'session_end',
       decided_at = CURRENT_TIMESTAMP
 WHERE status = 'pending'
 RETURNING id, workspace_id
`

type CancelAllPendingAskUserRequestsRow struct {
	ID          int64 `json:"id"`
	WorkspaceID int64 `json:"workspace_id"`
}

func (q *Queries) CancelAllPendingAskUserRequests(ctx context.Context) ([]CancelAllPendingAskUserRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, cancelAllPendingAskUserRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CancelAllPendingAskUserRequestsRow{}
	for rows.Next() {
		var i CancelAllPendingAskUserRequestsRow
		if err := rows.Scan(&i.ID, &i.WorkspaceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cancelPendingAskUserRequestsByWorkspace = `-- name: CancelPendingAskUserRequestsByWorkspace :many
UPDATE agent_ask_user_requests
   SET status = 'cancelled',
       decision_source = ?,
       decided_at = CURRENT_TIMESTAMP
 WHERE workspace_id = ? AND status = 'pending'
 RETURNING id, owner_type, owner_id
`

type CancelPendingAskUserRequestsByWorkspaceParams struct {
	DecisionSource sql.NullString `json:"decision_source"`
	WorkspaceID    int64          `json:"workspace_id"`
}

type CancelPendingAskUserRequestsByWorkspaceRow struct {
	ID        int64  `json:"id"`
	OwnerType string `json:"owner_type"`
	OwnerID   int64  `json:"owner_id"`
}

func (q *Queries) CancelPendingAskUserRequestsByWorkspace(ctx context.Context, arg CancelPendingAskUserRequestsByWorkspaceParams) ([]CancelPendingAskUserRequestsByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, cancelPendingAskUserRequestsByWorkspace, arg.DecisionSource, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CancelPendingAskUserRequestsByWorkspaceRow{}
	for rows.Next() {
		var i CancelPendingAskUserRequestsByWorkspaceRow
		if err := rows.Scan(&i.ID, &i.OwnerType, &i.OwnerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAskUserRequest = `-- name: GetAskUserRequest :one
SELECT id, workspace_id, owner_type, owner_id, session_id, questions_json, status, decision_source, decided_by, answers_json, requested_at, decided_at, expires_at FROM agent_ask_user_requests WHERE id = ?
`

func (q *Queries) GetAskUserRequest(ctx context.Context, id int64) (AgentAskUserRequest, error) {
	row := q.db.QueryRowContext(ctx, getAskUserRequest, id)
	var i AgentAskUserRequest
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.OwnerType,
		&i.OwnerID,
		&i.SessionID,
		&i.QuestionsJson,
		&i.Status,
		&i.DecisionSource,
		&i.DecidedBy,
		&i.AnswersJson,
		&i.RequestedAt,
		&i.DecidedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertAskUserRequest = `-- name: InsertAskUserRequest :one
INSERT INTO agent_ask_user_requests
    (workspace_id, owner_type, owner_id, session_id, questions_json, status, requested_at, expires_at)
VALUES
    (?, ?, ?, ?, ?, 'pending', CURRENT_TIMESTAMP, ?)
RETURNING id
`

type InsertAskUserRequestParams struct {
	WorkspaceID   int64     `json:"workspace_id"`
	OwnerType     string    `json:"owner_type"`
	OwnerID       int64     `json:"owner_id"`
	SessionID     string    `json:"session_id"`
	QuestionsJson string    `json:"questions_json"`
	ExpiresAt     time.Time `json:"expires_at"`
}

func (q *Queries) InsertAskUserRequest(ctx context.Context, arg InsertAskUserRequestParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertAskUserRequest,
		arg.WorkspaceID,
		arg.OwnerType,
		arg.OwnerID,
		arg.SessionID,
		arg.QuestionsJson,
		arg.ExpiresAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listPendingAskUserRequestsByWorkspace = `-- name: ListPendingAskUserRequestsByWorkspace :many
SELECT id, workspace_id, owner_type, owner_id, session_id, questions_json, status, decision_source, decided_by, answers_json, requested_at, decided_at, expires_at FROM agent_ask_user_requests
 WHERE workspace_id = ? AND status = 'pending'
 ORDER BY requested_at ASC
`

func (q *Queries) ListPendingAskUserRequestsByWorkspace(ctx context.Context, workspaceID int64) ([]AgentAskUserRequest, error) {
	rows, err := q.db.QueryContext(ctx, listPendingAskUserRequestsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentAskUserRequest{}
	for rows.Next() {
		var i AgentAskUserRequest
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.OwnerType,
			&i.OwnerID,
			&i.SessionID,
			&i.QuestionsJson,
			&i.Status,
			&i.DecisionSource,
			&i.DecidedBy,
			&i.AnswersJson,
			&i.RequestedAt,
			&i.DecidedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAskUserRequestAnswered = `-- name: MarkAskUserRequestAnswered :execrows
UPDATE agent_ask_user_requests
   SET status = 'answered',
       decision_source = ?,
       decided_by = ?,
       answers_json = ?,
       decided_at = CURRENT_TIMESTAMP
 WHERE id = ? AND status = 'pending'
`

type MarkAskUserRequestAnsweredParams struct {
	DecisionSource sql.NullString `json:"decision_source"`
	DecidedBy      sql.NullInt64  `json:"decided_by"`
	AnswersJson    sql.NullString `json:"answers_json"`
	ID             int64          `json:"id"`
}

func (q *Queries) MarkAskUserRequestAnswered(ctx context.Context, arg MarkAskUserRequestAnsweredParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAskUserRequestAnswered,
		arg.DecisionSource,
		arg.DecidedBy,
		arg.AnswersJson,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markAskUserRequestCancelled = `-- name: MarkAskUserRequestCancelled :execrows
UPDATE agent_ask_user_requests
   SET status = 'cancelled',
       decision_source = ?,
       decided_at = CURRENT_TIMESTAMP
 WHERE id = ? AND status = 'pending'
`

type MarkAskUserRequestCancelledParams struct {
	DecisionSource sql.NullString `json:"decision_source"`
	ID             int64          `json:"id"`
}

func (q *Queries) MarkAskUserRequestCancelled(ctx context.Context, arg MarkAskUserRequestCancelledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAskUserRequestCancelled, arg.DecisionSource, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markAskUserRequestTimeout = `-- name: MarkAskUserRequestTimeout :execrows
UPDATE agent_ask_user_requests
   SET status = 'timeout',
       decision_source = 'timeout',
       decided_at = CURRENT_TIMESTAMP
 WHERE id = ? AND status = 'pending'
`

func (q *Queries) MarkAskUserRequestTimeout(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAskUserRequestTimeout, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
