// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assignable.sql

package store

import (
	"context"
)

const getUserBasic = `-- name: GetUserBasic :one
SELECT id, username, display_name FROM users WHERE id = ?
`

type GetUserBasicRow struct {
	ID          int64  `json:"id"`
	Username    string `json:"username"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) GetUserBasic(ctx context.Context, id int64) (GetUserBasicRow, error) {
	row := q.db.QueryRowContext(ctx, getUserBasic, id)
	var i GetUserBasicRow
	err := row.Scan(&i.ID, &i.Username, &i.DisplayName)
	return i, err
}

const listAssignableUsersForOrg = `-- name: ListAssignableUsersForOrg :many
SELECT u.id, u.username, u.display_name, m.role
FROM org_members m
JOIN users u ON u.id = m.user_id
WHERE m.org_id = ?
ORDER BY u.display_name, u.username
`

type ListAssignableUsersForOrgRow struct {
	ID          int64  `json:"id"`
	Username    string `json:"username"`
	DisplayName string `json:"display_name"`
	Role        string `json:"role"`
}

func (q *Queries) ListAssignableUsersForOrg(ctx context.Context, orgID int64) ([]ListAssignableUsersForOrgRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssignableUsersForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssignableUsersForOrgRow{}
	for rows.Next() {
		var i ListAssignableUsersForOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
