// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_security.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const countFailedLoginsByIP = `-- name: CountFailedLoginsByIP :one
SELECT COUNT(*) FROM login_attempts
WHERE ip = ?
  AND success = 0
  AND created_at >= ?
`

type CountFailedLoginsByIPParams struct {
	Ip        string    `json:"ip"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CountFailedLoginsByIP(ctx context.Context, arg CountFailedLoginsByIPParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFailedLoginsByIP, arg.Ip, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFailedLoginsByUser = `-- name: CountFailedLoginsByUser :one
SELECT COUNT(*) FROM login_attempts
WHERE user_id = ?
  AND success = 0
  AND created_at >= ?
`

type CountFailedLoginsByUserParams struct {
	UserID    sql.NullInt64 `json:"user_id"`
	CreatedAt time.Time     `json:"created_at"`
}

func (q *Queries) CountFailedLoginsByUser(ctx context.Context, arg CountFailedLoginsByUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFailedLoginsByUser, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOldLoginAttempts = `-- name: DeleteOldLoginAttempts :exec
DELETE FROM login_attempts WHERE created_at < ?
`

func (q *Queries) DeleteOldLoginAttempts(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteOldLoginAttempts, createdAt)
	return err
}

const getIPLockout = `-- name: GetIPLockout :one
SELECT ip, fail_count, locked_until, updated_at
FROM ip_lockouts
WHERE ip = ?
`

func (q *Queries) GetIPLockout(ctx context.Context, ip string) (IpLockout, error) {
	row := q.db.QueryRowContext(ctx, getIPLockout, ip)
	var i IpLockout
	err := row.Scan(
		&i.Ip,
		&i.FailCount,
		&i.LockedUntil,
		&i.UpdatedAt,
	)
	return i, err
}

const listLoginAttemptsForUser = `-- name: ListLoginAttemptsForUser :many
SELECT id, user_id, username, ip, user_agent, success, reason, created_at
FROM login_attempts
WHERE user_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListLoginAttemptsForUserParams struct {
	UserID sql.NullInt64 `json:"user_id"`
	Limit  int64         `json:"limit"`
}

func (q *Queries) ListLoginAttemptsForUser(ctx context.Context, arg ListLoginAttemptsForUserParams) ([]LoginAttempt, error) {
	rows, err := q.db.QueryContext(ctx, listLoginAttemptsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoginAttempt{}
	for rows.Next() {
		var i LoginAttempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.Ip,
			&i.UserAgent,
			&i.Success,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserAccount = `-- name: LockUserAccount :exec
UPDATE users
SET locked_until = ?,
    lockout_count = lockout_count + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type LockUserAccountParams struct {
	LockedUntil sql.NullTime `json:"locked_until"`
	ID          int64        `json:"id"`
}

func (q *Queries) LockUserAccount(ctx context.Context, arg LockUserAccountParams) error {
	_, err := q.db.ExecContext(ctx, lockUserAccount, arg.LockedUntil, arg.ID)
	return err
}

const recordLoginAttempt = `-- name: RecordLoginAttempt :exec
INSERT INTO login_attempts (user_id, username, ip, user_agent, success, reason, created_at)
VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
`

type RecordLoginAttemptParams struct {
	UserID    sql.NullInt64 `json:"user_id"`
	Username  string        `json:"username"`
	Ip        string        `json:"ip"`
	UserAgent string        `json:"user_agent"`
	Success   int64         `json:"success"`
	Reason    string        `json:"reason"`
}

func (q *Queries) RecordLoginAttempt(ctx context.Context, arg RecordLoginAttemptParams) error {
	_, err := q.db.ExecContext(ctx, recordLoginAttempt,
		arg.UserID,
		arg.Username,
		arg.Ip,
		arg.UserAgent,
		arg.Success,
		arg.Reason,
	)
	return err
}

const resetIPLockoutFailCount = `-- name: ResetIPLockoutFailCount :exec
UPDATE ip_lockouts
SET fail_count = 0,
    locked_until = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE ip = ?
`

func (q *Queries) ResetIPLockoutFailCount(ctx context.Context, ip string) error {
	_, err := q.db.ExecContext(ctx, resetIPLockoutFailCount, ip)
	return err
}

const setRequirePasswordChange = `-- name: SetRequirePasswordChange :exec
UPDATE users
SET require_password_change = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type SetRequirePasswordChangeParams struct {
	RequirePasswordChange int64 `json:"require_password_change"`
	ID                    int64 `json:"id"`
}

func (q *Queries) SetRequirePasswordChange(ctx context.Context, arg SetRequirePasswordChangeParams) error {
	_, err := q.db.ExecContext(ctx, setRequirePasswordChange, arg.RequirePasswordChange, arg.ID)
	return err
}

const unlockUserAccount = `-- name: UnlockUserAccount :exec
UPDATE users
SET locked_until = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UnlockUserAccount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, unlockUserAccount, id)
	return err
}

const updateUserPasswordWithTimestamp = `-- name: UpdateUserPasswordWithTimestamp :exec
UPDATE users
SET password_hash = ?,
    password_changed_at = CURRENT_TIMESTAMP,
    require_password_change = 0,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateUserPasswordWithTimestampParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateUserPasswordWithTimestamp(ctx context.Context, arg UpdateUserPasswordWithTimestampParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPasswordWithTimestamp, arg.PasswordHash, arg.ID)
	return err
}

const upsertIPLockout = `-- name: UpsertIPLockout :exec
INSERT INTO ip_lockouts (ip, fail_count, locked_until, updated_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT (ip) DO UPDATE
SET fail_count = EXCLUDED.fail_count,
    locked_until = EXCLUDED.locked_until,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertIPLockoutParams struct {
	Ip          string       `json:"ip"`
	FailCount   int64        `json:"fail_count"`
	LockedUntil sql.NullTime `json:"locked_until"`
}

func (q *Queries) UpsertIPLockout(ctx context.Context, arg UpsertIPLockoutParams) error {
	_, err := q.db.ExecContext(ctx, upsertIPLockout, arg.Ip, arg.FailCount, arg.LockedUntil)
	return err
}
