// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: claude_accounts.sql

package store

import (
	"context"
	"database/sql"
)

const appendClaudeAccountAudit = `-- name: AppendClaudeAccountAudit :exec
INSERT INTO claude_account_audit_log (account_id, actor_user_id, action, payload)
VALUES (?, ?, ?, ?)
`

type AppendClaudeAccountAuditParams struct {
	AccountID   sql.NullInt64 `json:"account_id"`
	ActorUserID sql.NullInt64 `json:"actor_user_id"`
	Action      string        `json:"action"`
	Payload     string        `json:"payload"`
}

func (q *Queries) AppendClaudeAccountAudit(ctx context.Context, arg AppendClaudeAccountAuditParams) error {
	_, err := q.db.ExecContext(ctx, appendClaudeAccountAudit,
		arg.AccountID,
		arg.ActorUserID,
		arg.Action,
		arg.Payload,
	)
	return err
}

const clearActiveClaudeAccount = `-- name: ClearActiveClaudeAccount :exec
DELETE FROM claude_active_account WHERE owner_type = ? AND owner_id = ?
`

type ClearActiveClaudeAccountParams struct {
	OwnerType string `json:"owner_type"`
	OwnerID   int64  `json:"owner_id"`
}

func (q *Queries) ClearActiveClaudeAccount(ctx context.Context, arg ClearActiveClaudeAccountParams) error {
	_, err := q.db.ExecContext(ctx, clearActiveClaudeAccount, arg.OwnerType, arg.OwnerID)
	return err
}

const createClaudeAccount = `-- name: CreateClaudeAccount :one

INSERT INTO claude_accounts (name, email, config_dir, visibility, status, created_at, created_by)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateClaudeAccountParams struct {
	Name       string         `json:"name"`
	Email      sql.NullString `json:"email"`
	ConfigDir  string         `json:"config_dir"`
	Visibility string         `json:"visibility"`
	Status     string         `json:"status"`
	CreatedAt  int64          `json:"created_at"`
	CreatedBy  sql.NullInt64  `json:"created_by"`
}

// WARNING: sqlc v1.30.0 has a query-string truncation bug that affects
// this file (each query loses its trailing token, and bleed-over corrupts
// the next query). DO NOT run `make sqlc` to regenerate `claude_accounts.sql.go`
// without first verifying the output. The current `claude_accounts.sql.go`
// has been manually corrected; if you must regenerate, diff the result
// against HEAD and restore truncated tokens before committing. Track
// sqlc upgrades to find a version where this bug is fixed.
// See: docs/superpowers/plans/2026-05-08-claude-multi-account.md Task 5 notes.
func (q *Queries) CreateClaudeAccount(ctx context.Context, arg CreateClaudeAccountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createClaudeAccount,
		arg.Name,
		arg.Email,
		arg.ConfigDir,
		arg.Visibility,
		arg.Status,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteClaudeAccount = `-- name: DeleteClaudeAccount :exec
DELETE FROM claude_accounts WHERE id = ? AND config_dir != ''
`

func (q *Queries) DeleteClaudeAccount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteClaudeAccount, id)
	return err
}

const getActiveClaudeAccount = `-- name: GetActiveClaudeAccount :one
SELECT account_id FROM claude_active_account
WHERE owner_type = ? AND owner_id = ?
`

type GetActiveClaudeAccountParams struct {
	OwnerType string `json:"owner_type"`
	OwnerID   int64  `json:"owner_id"`
}

func (q *Queries) GetActiveClaudeAccount(ctx context.Context, arg GetActiveClaudeAccountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getActiveClaudeAccount, arg.OwnerType, arg.OwnerID)
	var account_id int64
	err := row.Scan(&account_id)
	return account_id, err
}

const getClaudeAccount = `-- name: GetClaudeAccount :one
SELECT id, name, email, config_dir, visibility, status,
       created_at, last_used_at, created_by
FROM claude_accounts
WHERE id = ?
`

func (q *Queries) GetClaudeAccount(ctx context.Context, id int64) (ClaudeAccount, error) {
	row := q.db.QueryRowContext(ctx, getClaudeAccount, id)
	var i ClaudeAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ConfigDir,
		&i.Visibility,
		&i.Status,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getDefaultClaudeAccount = `-- name: GetDefaultClaudeAccount :one
SELECT id, name, email, config_dir, visibility, status,
       created_at, last_used_at, created_by
FROM claude_accounts
WHERE config_dir = ''
LIMIT 1
`

func (q *Queries) GetDefaultClaudeAccount(ctx context.Context) (ClaudeAccount, error) {
	row := q.db.QueryRowContext(ctx, getDefaultClaudeAccount)
	var i ClaudeAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ConfigDir,
		&i.Visibility,
		&i.Status,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getUserRole = `-- name: GetUserRole :one
SELECT role FROM users WHERE id = ?
`

func (q *Queries) GetUserRole(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserRole, id)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getWorkspaceClaudeAccount = `-- name: GetWorkspaceClaudeAccount :one
SELECT claude_account_id FROM workspaces WHERE id = ?
`

func (q *Queries) GetWorkspaceClaudeAccount(ctx context.Context, id int64) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceClaudeAccount, id)
	var claude_account_id sql.NullInt64
	err := row.Scan(&claude_account_id)
	return claude_account_id, err
}

const getWorkspaceForClaudeResolve = `-- name: GetWorkspaceForClaudeResolve :one
SELECT owner_type, owner_id, claude_account_id FROM workspaces WHERE id = ?
`

type GetWorkspaceForClaudeResolveRow struct {
	OwnerType       string        `json:"owner_type"`
	OwnerID         int64         `json:"owner_id"`
	ClaudeAccountID sql.NullInt64 `json:"claude_account_id"`
}

func (q *Queries) GetWorkspaceForClaudeResolve(ctx context.Context, id int64) (GetWorkspaceForClaudeResolveRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceForClaudeResolve, id)
	var i GetWorkspaceForClaudeResolveRow
	err := row.Scan(&i.OwnerType, &i.OwnerID, &i.ClaudeAccountID)
	return i, err
}

const listClaudeAccountAudit = `-- name: ListClaudeAccountAudit :many
SELECT id, account_id, actor_user_id, action, payload, created_at
FROM claude_account_audit_log
WHERE account_id = ? AND id < ?
ORDER BY id DESC
LIMIT ?
`

type ListClaudeAccountAuditParams struct {
	AccountID sql.NullInt64 `json:"account_id"`
	ID        int64         `json:"id"`
	Limit     int64         `json:"limit"`
}

func (q *Queries) ListClaudeAccountAudit(ctx context.Context, arg ListClaudeAccountAuditParams) ([]ClaudeAccountAuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listClaudeAccountAudit, arg.AccountID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaudeAccountAuditLog{}
	for rows.Next() {
		var i ClaudeAccountAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ActorUserID,
			&i.Action,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClaudeAccountsForCaller = `-- name: ListClaudeAccountsForCaller :many
SELECT id, name, email, config_dir, visibility, status,
       created_at, last_used_at, created_by
FROM claude_accounts
WHERE ? = 1
   OR visibility = 'public'
   OR created_by = ?
ORDER BY (config_dir = '') DESC, created_at ASC
`

type ListClaudeAccountsForCallerParams struct {
	Column1   interface{}   `json:"column_1"`
	CreatedBy sql.NullInt64 `json:"created_by"`
}

// 1st ? = adminFlag (1 = caller is admin, 0 = not)
// 2nd ? = callerID (>0 = a real user, 0 = anonymous)
// NOTE: ascii-only comments here -- sqlc v1.30.0 truncates query strings
// when multi-byte chars appear in -- comments inside .sql files.
func (q *Queries) ListClaudeAccountsForCaller(ctx context.Context, arg ListClaudeAccountsForCallerParams) ([]ClaudeAccount, error) {
	rows, err := q.db.QueryContext(ctx, listClaudeAccountsForCaller, arg.Column1, arg.CreatedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaudeAccount{}
	for rows.Next() {
		var i ClaudeAccount
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.ConfigDir,
			&i.Visibility,
			&i.Status,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActiveClaudeAccount = `-- name: SetActiveClaudeAccount :exec
INSERT INTO claude_active_account (owner_type, owner_id, account_id)
VALUES (?, ?, ?)
ON CONFLICT (owner_type, owner_id) DO UPDATE SET account_id = excluded.account_id
`

type SetActiveClaudeAccountParams struct {
	OwnerType string `json:"owner_type"`
	OwnerID   int64  `json:"owner_id"`
	AccountID int64  `json:"account_id"`
}

func (q *Queries) SetActiveClaudeAccount(ctx context.Context, arg SetActiveClaudeAccountParams) error {
	_, err := q.db.ExecContext(ctx, setActiveClaudeAccount, arg.OwnerType, arg.OwnerID, arg.AccountID)
	return err
}

const setWorkspaceClaudeAccount = `-- name: SetWorkspaceClaudeAccount :exec
UPDATE workspaces SET claude_account_id = ? WHERE id = ?
`

type SetWorkspaceClaudeAccountParams struct {
	ClaudeAccountID sql.NullInt64 `json:"claude_account_id"`
	ID              int64         `json:"id"`
}

func (q *Queries) SetWorkspaceClaudeAccount(ctx context.Context, arg SetWorkspaceClaudeAccountParams) error {
	_, err := q.db.ExecContext(ctx, setWorkspaceClaudeAccount, arg.ClaudeAccountID, arg.ID)
	return err
}

const touchClaudeAccount = `-- name: TouchClaudeAccount :exec
UPDATE claude_accounts SET last_used_at = ? WHERE id = ?
`

type TouchClaudeAccountParams struct {
	LastUsedAt sql.NullInt64 `json:"last_used_at"`
	ID         int64         `json:"id"`
}

func (q *Queries) TouchClaudeAccount(ctx context.Context, arg TouchClaudeAccountParams) error {
	_, err := q.db.ExecContext(ctx, touchClaudeAccount, arg.LastUsedAt, arg.ID)
	return err
}

const updateClaudeAccountAfterLogin = `-- name: UpdateClaudeAccountAfterLogin :exec
UPDATE claude_accounts
SET email = ?, status = ?, last_used_at = ?
WHERE id = ?
`

type UpdateClaudeAccountAfterLoginParams struct {
	Email      sql.NullString `json:"email"`
	Status     string         `json:"status"`
	LastUsedAt sql.NullInt64  `json:"last_used_at"`
	ID         int64          `json:"id"`
}

func (q *Queries) UpdateClaudeAccountAfterLogin(ctx context.Context, arg UpdateClaudeAccountAfterLoginParams) error {
	_, err := q.db.ExecContext(ctx, updateClaudeAccountAfterLogin,
		arg.Email,
		arg.Status,
		arg.LastUsedAt,
		arg.ID,
	)
	return err
}

const updateClaudeAccountName = `-- name: UpdateClaudeAccountName :exec
UPDATE claude_accounts SET name = ? WHERE id = ?
`

type UpdateClaudeAccountNameParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateClaudeAccountName(ctx context.Context, arg UpdateClaudeAccountNameParams) error {
	_, err := q.db.ExecContext(ctx, updateClaudeAccountName, arg.Name, arg.ID)
	return err
}

const updateClaudeAccountStatus = `-- name: UpdateClaudeAccountStatus :exec
UPDATE claude_accounts SET status = ? WHERE id = ?
`

type UpdateClaudeAccountStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateClaudeAccountStatus(ctx context.Context, arg UpdateClaudeAccountStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateClaudeAccountStatus, arg.Status, arg.ID)
	return err
}

const updateClaudeAccountVisibility = `-- name: UpdateClaudeAccountVisibility :exec
UPDATE claude_accounts SET visibility = ? WHERE id = ?
`

type UpdateClaudeAccountVisibilityParams struct {
	Visibility string `json:"visibility"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateClaudeAccountVisibility(ctx context.Context, arg UpdateClaudeAccountVisibilityParams) error {
	_, err := q.db.ExecContext(ctx, updateClaudeAccountVisibility, arg.Visibility, arg.ID)
	return err
}
