// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: column_gate_specs.sql

package store

import (
	"context"
	"strings"
)

const countSpecFloorBindings = `-- name: CountSpecFloorBindings :one
SELECT CAST(COUNT(*) AS INTEGER) FROM column_gate_specs WHERE spec_id = ? AND applicability = 'always'
`

// How many columns bind this spec as a project floor (applicability='always').
// Used to protect a floor's severity from being silently downgraded (spec section 18).
func (q *Queries) CountSpecFloorBindings(ctx context.Context, specID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSpecFloorBindings, specID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteColumnGateSpecs = `-- name: DeleteColumnGateSpecs :exec
DELETE FROM column_gate_specs WHERE column_id = ?
`

func (q *Queries) DeleteColumnGateSpecs(ctx context.Context, columnID int64) error {
	_, err := q.db.ExecContext(ctx, deleteColumnGateSpecs, columnID)
	return err
}

const insertColumnGateSpec = `-- name: InsertColumnGateSpec :exec
INSERT INTO column_gate_specs (column_id, spec_id, position, applicability) VALUES (?, ?, ?, ?)
`

type InsertColumnGateSpecParams struct {
	ColumnID      int64  `json:"column_id"`
	SpecID        int64  `json:"spec_id"`
	Position      int64  `json:"position"`
	Applicability string `json:"applicability"`
}

// applicability is if_routed (column-level gate) or always (project floor); the
// caller passes it explicitly so a re-bind never silently resets a floor to if_routed.
func (q *Queries) InsertColumnGateSpec(ctx context.Context, arg InsertColumnGateSpecParams) error {
	_, err := q.db.ExecContext(ctx, insertColumnGateSpec,
		arg.ColumnID,
		arg.SpecID,
		arg.Position,
		arg.Applicability,
	)
	return err
}

const listColumnGateSpecs = `-- name: ListColumnGateSpecs :many
SELECT column_id, spec_id, position, applicability FROM column_gate_specs WHERE column_id = ? ORDER BY position
`

func (q *Queries) ListColumnGateSpecs(ctx context.Context, columnID int64) ([]ColumnGateSpec, error) {
	rows, err := q.db.QueryContext(ctx, listColumnGateSpecs, columnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ColumnGateSpec{}
	for rows.Next() {
		var i ColumnGateSpec
		if err := rows.Scan(
			&i.ColumnID,
			&i.SpecID,
			&i.Position,
			&i.Applicability,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listColumnGateSpecsByColumns = `-- name: ListColumnGateSpecsByColumns :many
SELECT column_id, spec_id, position, applicability FROM column_gate_specs
WHERE column_id IN (/*SLICE:column_ids*/?)
ORDER BY column_id, position
`

// Batched form of ListColumnGateSpecs for listing many columns' gate bindings at
// once (the project columns endpoint). Caller groups rows by column_id; ordering
// keeps each column's bindings in position order.
func (q *Queries) ListColumnGateSpecsByColumns(ctx context.Context, columnIds []int64) ([]ColumnGateSpec, error) {
	query := listColumnGateSpecsByColumns
	var queryParams []interface{}
	if len(columnIds) > 0 {
		for _, v := range columnIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:column_ids*/?", strings.Repeat(",?", len(columnIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:column_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ColumnGateSpec{}
	for rows.Next() {
		var i ColumnGateSpec
		if err := rows.Scan(
			&i.ColumnID,
			&i.SpecID,
			&i.Position,
			&i.Applicability,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
