// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: columns.sql

package store

import (
	"context"
	"database/sql"
	"strings"
)

const createColumn = `-- name: CreateColumn :one
INSERT INTO columns (project_id, name, position, lifecycle_mapping) VALUES (?, ?, ?, ?) RETURNING id, project_id, name, position, lifecycle_mapping, reviewer_agent, phase_prompt, auto_advance
`

type CreateColumnParams struct {
	ProjectID        int64  `json:"project_id"`
	Name             string `json:"name"`
	Position         int64  `json:"position"`
	LifecycleMapping string `json:"lifecycle_mapping"`
}

func (q *Queries) CreateColumn(ctx context.Context, arg CreateColumnParams) (Column, error) {
	row := q.db.QueryRowContext(ctx, createColumn,
		arg.ProjectID,
		arg.Name,
		arg.Position,
		arg.LifecycleMapping,
	)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Position,
		&i.LifecycleMapping,
		&i.ReviewerAgent,
		&i.PhasePrompt,
		&i.AutoAdvance,
	)
	return i, err
}

const deleteColumn = `-- name: DeleteColumn :exec
DELETE FROM columns WHERE id = ?
`

func (q *Queries) DeleteColumn(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteColumn, id)
	return err
}

const getColumn = `-- name: GetColumn :one
SELECT id, project_id, name, position, lifecycle_mapping, reviewer_agent, phase_prompt, auto_advance FROM columns WHERE id = ?
`

func (q *Queries) GetColumn(ctx context.Context, id int64) (Column, error) {
	row := q.db.QueryRowContext(ctx, getColumn, id)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Position,
		&i.LifecycleMapping,
		&i.ReviewerAgent,
		&i.PhasePrompt,
		&i.AutoAdvance,
	)
	return i, err
}

const getColumnsByIDs = `-- name: GetColumnsByIDs :many
SELECT id, project_id, name, position, lifecycle_mapping, reviewer_agent, phase_prompt, auto_advance FROM columns WHERE id IN (/*SLICE:ids*/?)
`

// Batched form of GetColumn for callers resolving many columns at once (e.g. the
// attention-issues list, which maps each issue to its column/project for deep
// links) instead of one query per row.
func (q *Queries) GetColumnsByIDs(ctx context.Context, ids []int64) ([]Column, error) {
	query := getColumnsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Column{}
	for rows.Next() {
		var i Column
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Position,
			&i.LifecycleMapping,
			&i.ReviewerAgent,
			&i.PhasePrompt,
			&i.AutoAdvance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listColumnsByProject = `-- name: ListColumnsByProject :many
SELECT id, project_id, name, position, lifecycle_mapping, reviewer_agent, phase_prompt, auto_advance FROM columns WHERE project_id = ? ORDER BY position
`

func (q *Queries) ListColumnsByProject(ctx context.Context, projectID int64) ([]Column, error) {
	rows, err := q.db.QueryContext(ctx, listColumnsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Column{}
	for rows.Next() {
		var i Column
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Position,
			&i.LifecycleMapping,
			&i.ReviewerAgent,
			&i.PhasePrompt,
			&i.AutoAdvance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateColumn = `-- name: UpdateColumn :one
UPDATE columns SET name = ? WHERE id = ? RETURNING id, project_id, name, position, lifecycle_mapping, reviewer_agent, phase_prompt, auto_advance
`

type UpdateColumnParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateColumn(ctx context.Context, arg UpdateColumnParams) (Column, error) {
	row := q.db.QueryRowContext(ctx, updateColumn, arg.Name, arg.ID)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Position,
		&i.LifecycleMapping,
		&i.ReviewerAgent,
		&i.PhasePrompt,
		&i.AutoAdvance,
	)
	return i, err
}

const updateColumnExtension = `-- name: UpdateColumnExtension :one
UPDATE columns
SET reviewer_agent = ?,
    phase_prompt   = ?,
    auto_advance   = ?
WHERE id = ?
RETURNING id, project_id, name, position, lifecycle_mapping, reviewer_agent, phase_prompt, auto_advance
`

type UpdateColumnExtensionParams struct {
	ReviewerAgent sql.NullString `json:"reviewer_agent"`
	PhasePrompt   sql.NullString `json:"phase_prompt"`
	AutoAdvance   int64          `json:"auto_advance"`
	ID            int64          `json:"id"`
}

func (q *Queries) UpdateColumnExtension(ctx context.Context, arg UpdateColumnExtensionParams) (Column, error) {
	row := q.db.QueryRowContext(ctx, updateColumnExtension,
		arg.ReviewerAgent,
		arg.PhasePrompt,
		arg.AutoAdvance,
		arg.ID,
	)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Position,
		&i.LifecycleMapping,
		&i.ReviewerAgent,
		&i.PhasePrompt,
		&i.AutoAdvance,
	)
	return i, err
}

const updateColumnLifecycleMapping = `-- name: UpdateColumnLifecycleMapping :one
UPDATE columns SET lifecycle_mapping = ? WHERE id = ? RETURNING id, project_id, name, position, lifecycle_mapping, reviewer_agent, phase_prompt, auto_advance
`

type UpdateColumnLifecycleMappingParams struct {
	LifecycleMapping string `json:"lifecycle_mapping"`
	ID               int64  `json:"id"`
}

func (q *Queries) UpdateColumnLifecycleMapping(ctx context.Context, arg UpdateColumnLifecycleMappingParams) (Column, error) {
	row := q.db.QueryRowContext(ctx, updateColumnLifecycleMapping, arg.LifecycleMapping, arg.ID)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Position,
		&i.LifecycleMapping,
		&i.ReviewerAgent,
		&i.PhasePrompt,
		&i.AutoAdvance,
	)
	return i, err
}

const updateColumnPosition = `-- name: UpdateColumnPosition :exec
UPDATE columns SET position = ? WHERE id = ?
`

type UpdateColumnPositionParams struct {
	Position int64 `json:"position"`
	ID       int64 `json:"id"`
}

func (q *Queries) UpdateColumnPosition(ctx context.Context, arg UpdateColumnPositionParams) error {
	_, err := q.db.ExecContext(ctx, updateColumnPosition, arg.Position, arg.ID)
	return err
}
