// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package store

import (
	"context"
	"database/sql"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (workspace_id, repo, file_path, line_number, content) VALUES (?, ?, ?, ?, ?) RETURNING id, workspace_id, repo, file_path, line_number, content, sent_to_agent, created_at
`

type CreateCommentParams struct {
	WorkspaceID int64         `json:"workspace_id"`
	Repo        string        `json:"repo"`
	FilePath    string        `json:"file_path"`
	LineNumber  sql.NullInt64 `json:"line_number"`
	Content     string        `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		arg.WorkspaceID,
		arg.Repo,
		arg.FilePath,
		arg.LineNumber,
		arg.Content,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Repo,
		&i.FilePath,
		&i.LineNumber,
		&i.Content,
		&i.SentToAgent,
		&i.CreatedAt,
	)
	return i, err
}

const getComment = `-- name: GetComment :one
SELECT id, workspace_id, repo, file_path, line_number, content, sent_to_agent, created_at FROM comments WHERE id = ?
`

func (q *Queries) GetComment(ctx context.Context, id int64) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Repo,
		&i.FilePath,
		&i.LineNumber,
		&i.Content,
		&i.SentToAgent,
		&i.CreatedAt,
	)
	return i, err
}

const listCommentsByWorkspace = `-- name: ListCommentsByWorkspace :many
SELECT id, workspace_id, repo, file_path, line_number, content, sent_to_agent, created_at FROM comments WHERE workspace_id = ? ORDER BY created_at
`

func (q *Queries) ListCommentsByWorkspace(ctx context.Context, workspaceID int64) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Repo,
			&i.FilePath,
			&i.LineNumber,
			&i.Content,
			&i.SentToAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCommentSent = `-- name: MarkCommentSent :exec
UPDATE comments SET sent_to_agent = TRUE WHERE id = ?
`

func (q *Queries) MarkCommentSent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markCommentSent, id)
	return err
}
