// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: data_sources.sql

package store

import (
	"context"
	"strings"
)

const countDataSourceBinding = `-- name: CountDataSourceBinding :one
SELECT COUNT(*) AS n FROM data_source_bindings
WHERE source_id = ? AND target_type = ? AND target_id = ?
`

type CountDataSourceBindingParams struct {
	SourceID   int64  `json:"source_id"`
	TargetType string `json:"target_type"`
	TargetID   int64  `json:"target_id"`
}

func (q *Queries) CountDataSourceBinding(ctx context.Context, arg CountDataSourceBindingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDataSourceBinding, arg.SourceID, arg.TargetType, arg.TargetID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const createDataSource = `-- name: CreateDataSource :one
INSERT INTO data_sources
  (owner_type, owner_id, user_id, name, kind, config, scope_config, default_access_mode, require_confirm)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateDataSourceParams struct {
	OwnerType         string `json:"owner_type"`
	OwnerID           int64  `json:"owner_id"`
	UserID            int64  `json:"user_id"`
	Name              string `json:"name"`
	Kind              string `json:"kind"`
	Config            string `json:"config"`
	ScopeConfig       string `json:"scope_config"`
	DefaultAccessMode string `json:"default_access_mode"`
	RequireConfirm    string `json:"require_confirm"`
}

func (q *Queries) CreateDataSource(ctx context.Context, arg CreateDataSourceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createDataSource,
		arg.OwnerType,
		arg.OwnerID,
		arg.UserID,
		arg.Name,
		arg.Kind,
		arg.Config,
		arg.ScopeConfig,
		arg.DefaultAccessMode,
		arg.RequireConfirm,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createDataSourceAudit = `-- name: CreateDataSourceAudit :exec
INSERT INTO data_source_audit
  (user_id, source_id, access_mode, database_name, objects, statement_summary, status, rows, duration_ms)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateDataSourceAuditParams struct {
	UserID           int64  `json:"user_id"`
	SourceID         int64  `json:"source_id"`
	AccessMode       string `json:"access_mode"`
	DatabaseName     string `json:"database_name"`
	Objects          string `json:"objects"`
	StatementSummary string `json:"statement_summary"`
	Status           string `json:"status"`
	Rows             int64  `json:"rows"`
	DurationMs       int64  `json:"duration_ms"`
}

func (q *Queries) CreateDataSourceAudit(ctx context.Context, arg CreateDataSourceAuditParams) error {
	_, err := q.db.ExecContext(ctx, createDataSourceAudit,
		arg.UserID,
		arg.SourceID,
		arg.AccessMode,
		arg.DatabaseName,
		arg.Objects,
		arg.StatementSummary,
		arg.Status,
		arg.Rows,
		arg.DurationMs,
	)
	return err
}

const createDataSourceBinding = `-- name: CreateDataSourceBinding :exec
INSERT INTO data_source_bindings (source_id, target_type, target_id)
VALUES (?, ?, ?)
`

type CreateDataSourceBindingParams struct {
	SourceID   int64  `json:"source_id"`
	TargetType string `json:"target_type"`
	TargetID   int64  `json:"target_id"`
}

// Callers delete all bindings for the source first (DeleteBindingsForSource)
// and re-insert, so no ON CONFLICT clause is needed.
func (q *Queries) CreateDataSourceBinding(ctx context.Context, arg CreateDataSourceBindingParams) error {
	_, err := q.db.ExecContext(ctx, createDataSourceBinding, arg.SourceID, arg.TargetType, arg.TargetID)
	return err
}

const deleteBindingsForSource = `-- name: DeleteBindingsForSource :exec
DELETE FROM data_source_bindings WHERE source_id = ?
`

func (q *Queries) DeleteBindingsForSource(ctx context.Context, sourceID int64) error {
	_, err := q.db.ExecContext(ctx, deleteBindingsForSource, sourceID)
	return err
}

const deleteDataSource = `-- name: DeleteDataSource :exec
DELETE FROM data_sources WHERE id = ?
`

func (q *Queries) DeleteDataSource(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDataSource, id)
	return err
}

const deleteDataSourceBinding = `-- name: DeleteDataSourceBinding :exec
DELETE FROM data_source_bindings
WHERE source_id = ? AND target_type = ? AND target_id = ?
`

type DeleteDataSourceBindingParams struct {
	SourceID   int64  `json:"source_id"`
	TargetType string `json:"target_type"`
	TargetID   int64  `json:"target_id"`
}

func (q *Queries) DeleteDataSourceBinding(ctx context.Context, arg DeleteDataSourceBindingParams) error {
	_, err := q.db.ExecContext(ctx, deleteDataSourceBinding, arg.SourceID, arg.TargetType, arg.TargetID)
	return err
}

const getDataSource = `-- name: GetDataSource :one
SELECT id, owner_type, owner_id, user_id, name, kind, config, scope_config, default_access_mode, require_confirm, last_verified_at, created_at, updated_at FROM data_sources WHERE id = ?
`

func (q *Queries) GetDataSource(ctx context.Context, id int64) (DataSource, error) {
	row := q.db.QueryRowContext(ctx, getDataSource, id)
	var i DataSource
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.ScopeConfig,
		&i.DefaultAccessMode,
		&i.RequireConfirm,
		&i.LastVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBindingsForSource = `-- name: ListBindingsForSource :many
SELECT id, source_id, target_type, target_id, created_at
FROM data_source_bindings
WHERE source_id = ?
ORDER BY target_type, target_id
`

func (q *Queries) ListBindingsForSource(ctx context.Context, sourceID int64) ([]DataSourceBinding, error) {
	rows, err := q.db.QueryContext(ctx, listBindingsForSource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DataSourceBinding{}
	for rows.Next() {
		var i DataSourceBinding
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetType,
			&i.TargetID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDataSourcesForOwners = `-- name: ListDataSourcesForOwners :many
SELECT id, owner_type, owner_id, user_id, name, kind, config, scope_config, default_access_mode, require_confirm, last_verified_at, created_at, updated_at FROM data_sources
WHERE (owner_type = 'user' AND owner_id = ?)
   OR (owner_type = 'org'  AND owner_id IN (/*SLICE:org_ids*/?))
ORDER BY created_at DESC
`

type ListDataSourcesForOwnersParams struct {
	OwnerID int64   `json:"owner_id"`
	OrgIds  []int64 `json:"org_ids"`
}

func (q *Queries) ListDataSourcesForOwners(ctx context.Context, arg ListDataSourcesForOwnersParams) ([]DataSource, error) {
	query := listDataSourcesForOwners
	var queryParams []interface{}
	queryParams = append(queryParams, arg.OwnerID)
	if len(arg.OrgIds) > 0 {
		for _, v := range arg.OrgIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:org_ids*/?", strings.Repeat(",?", len(arg.OrgIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:org_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DataSource{}
	for rows.Next() {
		var i DataSource
		if err := rows.Scan(
			&i.ID,
			&i.OwnerType,
			&i.OwnerID,
			&i.UserID,
			&i.Name,
			&i.Kind,
			&i.Config,
			&i.ScopeConfig,
			&i.DefaultAccessMode,
			&i.RequireConfirm,
			&i.LastVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceIDsBoundToTarget = `-- name: ListSourceIDsBoundToTarget :many
SELECT source_id FROM data_source_bindings
WHERE target_type = ? AND target_id = ?
`

type ListSourceIDsBoundToTargetParams struct {
	TargetType string `json:"target_type"`
	TargetID   int64  `json:"target_id"`
}

func (q *Queries) ListSourceIDsBoundToTarget(ctx context.Context, arg ListSourceIDsBoundToTargetParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listSourceIDsBoundToTarget, arg.TargetType, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var source_id int64
		if err := rows.Scan(&source_id); err != nil {
			return nil, err
		}
		items = append(items, source_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchDataSourceVerified = `-- name: TouchDataSourceVerified :exec
UPDATE data_sources SET last_verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) TouchDataSourceVerified(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchDataSourceVerified, id)
	return err
}

const updateDataSource = `-- name: UpdateDataSource :exec
UPDATE data_sources
SET name = ?, config = ?, scope_config = ?, default_access_mode = ?, require_confirm = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateDataSourceParams struct {
	Name              string `json:"name"`
	Config            string `json:"config"`
	ScopeConfig       string `json:"scope_config"`
	DefaultAccessMode string `json:"default_access_mode"`
	RequireConfirm    string `json:"require_confirm"`
	ID                int64  `json:"id"`
}

func (q *Queries) UpdateDataSource(ctx context.Context, arg UpdateDataSourceParams) error {
	_, err := q.db.ExecContext(ctx, updateDataSource,
		arg.Name,
		arg.Config,
		arg.ScopeConfig,
		arg.DefaultAccessMode,
		arg.RequireConfirm,
		arg.ID,
	)
	return err
}
