// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: env_providers.sql

package store

import (
	"context"
	"database/sql"
	"strings"
)

const clearProviderCooldown = `-- name: ClearProviderCooldown :exec
UPDATE env_providers SET cooldown_until = NULL, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

// Clears a provider's rate-limit cooldown (user-initiated reset, or when the
// stored value has passed and the provider should be retried immediately).
func (q *Queries) ClearProviderCooldown(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearProviderCooldown, id)
	return err
}

const createEnvProvider = `-- name: CreateEnvProvider :one
INSERT INTO env_providers (name, platform, description, base_urls, api_key, model, codex_model, haiku_model, sonnet_model, opus_model, subagent_model, extra_env, context_window, group_name, group_position, enabled, owner_type, owner_id, slug)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, platform, description, base_urls, api_key, model, haiku_model, sonnet_model, opus_model, subagent_model, codex_model, extra_env, context_window, group_name, group_position, enabled, cooldown_until, owner_type, owner_id, slug, created_at, updated_at
`

type CreateEnvProviderParams struct {
	Name          string `json:"name"`
	Platform      string `json:"platform"`
	Description   string `json:"description"`
	BaseUrls      string `json:"base_urls"`
	ApiKey        string `json:"api_key"`
	Model         string `json:"model"`
	CodexModel    string `json:"codex_model"`
	HaikuModel    string `json:"haiku_model"`
	SonnetModel   string `json:"sonnet_model"`
	OpusModel     string `json:"opus_model"`
	SubagentModel string `json:"subagent_model"`
	ExtraEnv      string `json:"extra_env"`
	ContextWindow int64  `json:"context_window"`
	GroupName     string `json:"group_name"`
	GroupPosition int64  `json:"group_position"`
	Enabled       int64  `json:"enabled"`
	OwnerType     string `json:"owner_type"`
	OwnerID       int64  `json:"owner_id"`
	Slug          string `json:"slug"`
}

func (q *Queries) CreateEnvProvider(ctx context.Context, arg CreateEnvProviderParams) (EnvProvider, error) {
	row := q.db.QueryRowContext(ctx, createEnvProvider,
		arg.Name,
		arg.Platform,
		arg.Description,
		arg.BaseUrls,
		arg.ApiKey,
		arg.Model,
		arg.CodexModel,
		arg.HaikuModel,
		arg.SonnetModel,
		arg.OpusModel,
		arg.SubagentModel,
		arg.ExtraEnv,
		arg.ContextWindow,
		arg.GroupName,
		arg.GroupPosition,
		arg.Enabled,
		arg.OwnerType,
		arg.OwnerID,
		arg.Slug,
	)
	var i EnvProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Platform,
		&i.Description,
		&i.BaseUrls,
		&i.ApiKey,
		&i.Model,
		&i.HaikuModel,
		&i.SonnetModel,
		&i.OpusModel,
		&i.SubagentModel,
		&i.CodexModel,
		&i.ExtraEnv,
		&i.ContextWindow,
		&i.GroupName,
		&i.GroupPosition,
		&i.Enabled,
		&i.CooldownUntil,
		&i.OwnerType,
		&i.OwnerID,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEnvProvider = `-- name: DeleteEnvProvider :exec
DELETE FROM env_providers WHERE id = ?
`

func (q *Queries) DeleteEnvProvider(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEnvProvider, id)
	return err
}

const getEnvProvider = `-- name: GetEnvProvider :one
SELECT id, name, platform, description, base_urls, api_key, model, haiku_model, sonnet_model, opus_model, subagent_model, codex_model, extra_env, context_window, group_name, group_position, enabled, cooldown_until, owner_type, owner_id, slug, created_at, updated_at FROM env_providers WHERE id = ?
`

func (q *Queries) GetEnvProvider(ctx context.Context, id int64) (EnvProvider, error) {
	row := q.db.QueryRowContext(ctx, getEnvProvider, id)
	var i EnvProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Platform,
		&i.Description,
		&i.BaseUrls,
		&i.ApiKey,
		&i.Model,
		&i.HaikuModel,
		&i.SonnetModel,
		&i.OpusModel,
		&i.SubagentModel,
		&i.CodexModel,
		&i.ExtraEnv,
		&i.ContextWindow,
		&i.GroupName,
		&i.GroupPosition,
		&i.Enabled,
		&i.CooldownUntil,
		&i.OwnerType,
		&i.OwnerID,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnvProviders = `-- name: ListEnvProviders :many
SELECT id, name, platform, description, base_urls, api_key, model, haiku_model, sonnet_model, opus_model, subagent_model, codex_model, extra_env, context_window, group_name, group_position, enabled, cooldown_until, owner_type, owner_id, slug, created_at, updated_at FROM env_providers ORDER BY name ASC
`

func (q *Queries) ListEnvProviders(ctx context.Context) ([]EnvProvider, error) {
	rows, err := q.db.QueryContext(ctx, listEnvProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvProvider{}
	for rows.Next() {
		var i EnvProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Platform,
			&i.Description,
			&i.BaseUrls,
			&i.ApiKey,
			&i.Model,
			&i.HaikuModel,
			&i.SonnetModel,
			&i.OpusModel,
			&i.SubagentModel,
			&i.CodexModel,
			&i.ExtraEnv,
			&i.ContextWindow,
			&i.GroupName,
			&i.GroupPosition,
			&i.Enabled,
			&i.CooldownUntil,
			&i.OwnerType,
			&i.OwnerID,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvProvidersForOwners = `-- name: ListEnvProvidersForOwners :many
SELECT id, name, platform, description, base_urls, api_key, model, haiku_model, sonnet_model, opus_model, subagent_model, codex_model, extra_env, context_window, group_name, group_position, enabled, cooldown_until, owner_type, owner_id, slug, created_at, updated_at FROM env_providers
WHERE (owner_type = 'user' AND owner_id = ?)
   OR (owner_type = 'org'  AND owner_id IN (/*SLICE:org_ids*/?))
   OR (owner_type = 'user' AND owner_id = 0)
ORDER BY created_at DESC
`

type ListEnvProvidersForOwnersParams struct {
	OwnerID int64   `json:"owner_id"`
	OrgIds  []int64 `json:"org_ids"`
}

// The third disjunct (owner_id = 0) surfaces system-wide defaults to every
// caller regardless of their personal or org scope, mirroring env_presets.
func (q *Queries) ListEnvProvidersForOwners(ctx context.Context, arg ListEnvProvidersForOwnersParams) ([]EnvProvider, error) {
	query := listEnvProvidersForOwners
	var queryParams []interface{}
	queryParams = append(queryParams, arg.OwnerID)
	if len(arg.OrgIds) > 0 {
		for _, v := range arg.OrgIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:org_ids*/?", strings.Repeat(",?", len(arg.OrgIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:org_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvProvider{}
	for rows.Next() {
		var i EnvProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Platform,
			&i.Description,
			&i.BaseUrls,
			&i.ApiKey,
			&i.Model,
			&i.HaikuModel,
			&i.SonnetModel,
			&i.OpusModel,
			&i.SubagentModel,
			&i.CodexModel,
			&i.ExtraEnv,
			&i.ContextWindow,
			&i.GroupName,
			&i.GroupPosition,
			&i.Enabled,
			&i.CooldownUntil,
			&i.OwnerType,
			&i.OwnerID,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxEnvProviderGroupPosition = `-- name: MaxEnvProviderGroupPosition :one
SELECT CAST(COALESCE(MAX(group_position), 0) AS INTEGER) AS max_pos
FROM env_providers
WHERE group_name = ? AND id != ?
`

type MaxEnvProviderGroupPositionParams struct {
	GroupName string `json:"group_name"`
	ID        int64  `json:"id"`
}

// Highest manual order within a group (0 = none). Used to APPEND a provider
// joining a group at the end of the fallback order (max+1) so a newcomer with
// the default position 0 never jumps ahead of manually ordered members.
// excludeID skips the provider itself (pass 0 for create) so a member moving
// within its own group does not count its old position.
func (q *Queries) MaxEnvProviderGroupPosition(ctx context.Context, arg MaxEnvProviderGroupPositionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxEnvProviderGroupPosition, arg.GroupName, arg.ID)
	var max_pos int64
	err := row.Scan(&max_pos)
	return max_pos, err
}

const setProviderCooldown = `-- name: SetProviderCooldown :exec
UPDATE env_providers SET cooldown_until = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type SetProviderCooldownParams struct {
	CooldownUntil sql.NullTime `json:"cooldown_until"`
	ID            int64        `json:"id"`
}

// Marks a provider as rate-limited until the given reset time (cooldown_until).
// While the value is in the future, sceneenv.ActiveProvider skips the provider
// and falls back to another member of its group.
func (q *Queries) SetProviderCooldown(ctx context.Context, arg SetProviderCooldownParams) error {
	_, err := q.db.ExecContext(ctx, setProviderCooldown, arg.CooldownUntil, arg.ID)
	return err
}

const setProviderEnabled = `-- name: SetProviderEnabled :exec
UPDATE env_providers SET enabled = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type SetProviderEnabledParams struct {
	Enabled int64 `json:"enabled"`
	ID      int64 `json:"id"`
}

// Manual on/off switch: enabled=0 takes the provider out of rotation (group
// fallback and binding both skip it) until the user re-enables it.
func (q *Queries) SetProviderEnabled(ctx context.Context, arg SetProviderEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setProviderEnabled, arg.Enabled, arg.ID)
	return err
}

const setProviderGroupPosition = `-- name: SetProviderGroupPosition :exec
UPDATE env_providers SET group_position = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type SetProviderGroupPositionParams struct {
	GroupPosition int64 `json:"group_position"`
	ID            int64 `json:"id"`
}

// Manual order within a group; smaller = used first as fallback. Reorder is a
// dedicated operation so it does not clobber the rest of the provider config.
func (q *Queries) SetProviderGroupPosition(ctx context.Context, arg SetProviderGroupPositionParams) error {
	_, err := q.db.ExecContext(ctx, setProviderGroupPosition, arg.GroupPosition, arg.ID)
	return err
}

const updateEnvProvider = `-- name: UpdateEnvProvider :exec
UPDATE env_providers
SET name = ?, platform = ?, description = ?, base_urls = ?, api_key = ?, model = ?, codex_model = ?,
    haiku_model = ?, sonnet_model = ?, opus_model = ?, subagent_model = ?, extra_env = ?, context_window = ?, group_name = ?, group_position = ?, enabled = ?, slug = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateEnvProviderParams struct {
	Name          string `json:"name"`
	Platform      string `json:"platform"`
	Description   string `json:"description"`
	BaseUrls      string `json:"base_urls"`
	ApiKey        string `json:"api_key"`
	Model         string `json:"model"`
	CodexModel    string `json:"codex_model"`
	HaikuModel    string `json:"haiku_model"`
	SonnetModel   string `json:"sonnet_model"`
	OpusModel     string `json:"opus_model"`
	SubagentModel string `json:"subagent_model"`
	ExtraEnv      string `json:"extra_env"`
	ContextWindow int64  `json:"context_window"`
	GroupName     string `json:"group_name"`
	GroupPosition int64  `json:"group_position"`
	Enabled       int64  `json:"enabled"`
	Slug          string `json:"slug"`
	ID            int64  `json:"id"`
}

func (q *Queries) UpdateEnvProvider(ctx context.Context, arg UpdateEnvProviderParams) error {
	_, err := q.db.ExecContext(ctx, updateEnvProvider,
		arg.Name,
		arg.Platform,
		arg.Description,
		arg.BaseUrls,
		arg.ApiKey,
		arg.Model,
		arg.CodexModel,
		arg.HaikuModel,
		arg.SonnetModel,
		arg.OpusModel,
		arg.SubagentModel,
		arg.ExtraEnv,
		arg.ContextWindow,
		arg.GroupName,
		arg.GroupPosition,
		arg.Enabled,
		arg.Slug,
		arg.ID,
	)
	return err
}
