// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: env_presets.sql

package store

import (
	"context"
)

const createEnvPreset = `-- name: CreateEnvPreset :one
INSERT INTO env_presets (name, description, env, owner_type, owner_id)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, description, env, owner_type, owner_id, slug, created_at, updated_at
`

type CreateEnvPresetParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Env         string `json:"env"`
	OwnerType   string `json:"owner_type"`
	OwnerID     int64  `json:"owner_id"`
}

func (q *Queries) CreateEnvPreset(ctx context.Context, arg CreateEnvPresetParams) (EnvPreset, error) {
	row := q.db.QueryRowContext(ctx, createEnvPreset,
		arg.Name,
		arg.Description,
		arg.Env,
		arg.OwnerType,
		arg.OwnerID,
	)
	var i EnvPreset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Env,
		&i.OwnerType,
		&i.OwnerID,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEnvPreset = `-- name: DeleteEnvPreset :exec
DELETE FROM env_presets WHERE id = ?
`

func (q *Queries) DeleteEnvPreset(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEnvPreset, id)
	return err
}

const getEnvPreset = `-- name: GetEnvPreset :one
SELECT id, name, description, env, owner_type, owner_id, slug, created_at, updated_at FROM env_presets WHERE id = ?
`

func (q *Queries) GetEnvPreset(ctx context.Context, id int64) (EnvPreset, error) {
	row := q.db.QueryRowContext(ctx, getEnvPreset, id)
	var i EnvPreset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Env,
		&i.OwnerType,
		&i.OwnerID,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvPresetCount = `-- name: GetEnvPresetCount :one
SELECT COUNT(*) FROM env_presets
`

func (q *Queries) GetEnvPresetCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getEnvPresetCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listEnvPresets = `-- name: ListEnvPresets :many
SELECT id, name, description, env, owner_type, owner_id, slug, created_at, updated_at FROM env_presets ORDER BY name ASC
`

func (q *Queries) ListEnvPresets(ctx context.Context) ([]EnvPreset, error) {
	rows, err := q.db.QueryContext(ctx, listEnvPresets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvPreset{}
	for rows.Next() {
		var i EnvPreset
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Env,
			&i.OwnerType,
			&i.OwnerID,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnvPreset = `-- name: UpdateEnvPreset :exec
UPDATE env_presets
SET name = ?, description = ?, env = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateEnvPresetParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Env         string `json:"env"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateEnvPreset(ctx context.Context, arg UpdateEnvPresetParams) error {
	_, err := q.db.ExecContext(ctx, updateEnvPreset,
		arg.Name,
		arg.Description,
		arg.Env,
		arg.ID,
	)
	return err
}
