// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: env_providers.sql

package store

import (
	"context"
	"strings"
)

const createEnvProvider = `-- name: CreateEnvProvider :one
INSERT INTO env_providers (name, platform, description, base_urls, api_key, model, haiku_model, sonnet_model, opus_model, subagent_model, extra_env, owner_type, owner_id, slug)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, platform, description, base_urls, api_key, model, haiku_model, sonnet_model, opus_model, subagent_model, extra_env, owner_type, owner_id, slug, created_at, updated_at
`

type CreateEnvProviderParams struct {
	Name          string `json:"name"`
	Platform      string `json:"platform"`
	Description   string `json:"description"`
	BaseUrls      string `json:"base_urls"`
	ApiKey        string `json:"api_key"`
	Model         string `json:"model"`
	HaikuModel    string `json:"haiku_model"`
	SonnetModel   string `json:"sonnet_model"`
	OpusModel     string `json:"opus_model"`
	SubagentModel string `json:"subagent_model"`
	ExtraEnv      string `json:"extra_env"`
	OwnerType     string `json:"owner_type"`
	OwnerID       int64  `json:"owner_id"`
	Slug          string `json:"slug"`
}

func (q *Queries) CreateEnvProvider(ctx context.Context, arg CreateEnvProviderParams) (EnvProvider, error) {
	row := q.db.QueryRowContext(ctx, createEnvProvider,
		arg.Name,
		arg.Platform,
		arg.Description,
		arg.BaseUrls,
		arg.ApiKey,
		arg.Model,
		arg.HaikuModel,
		arg.SonnetModel,
		arg.OpusModel,
		arg.SubagentModel,
		arg.ExtraEnv,
		arg.OwnerType,
		arg.OwnerID,
		arg.Slug,
	)
	var i EnvProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Platform,
		&i.Description,
		&i.BaseUrls,
		&i.ApiKey,
		&i.Model,
		&i.HaikuModel,
		&i.SonnetModel,
		&i.OpusModel,
		&i.SubagentModel,
		&i.ExtraEnv,
		&i.OwnerType,
		&i.OwnerID,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEnvProvider = `-- name: DeleteEnvProvider :exec
DELETE FROM env_providers WHERE id = ?
`

func (q *Queries) DeleteEnvProvider(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEnvProvider, id)
	return err
}

const getEnvProvider = `-- name: GetEnvProvider :one
SELECT id, name, platform, description, base_urls, api_key, model, haiku_model, sonnet_model, opus_model, subagent_model, extra_env, owner_type, owner_id, slug, created_at, updated_at FROM env_providers WHERE id = ?
`

func (q *Queries) GetEnvProvider(ctx context.Context, id int64) (EnvProvider, error) {
	row := q.db.QueryRowContext(ctx, getEnvProvider, id)
	var i EnvProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Platform,
		&i.Description,
		&i.BaseUrls,
		&i.ApiKey,
		&i.Model,
		&i.HaikuModel,
		&i.SonnetModel,
		&i.OpusModel,
		&i.SubagentModel,
		&i.ExtraEnv,
		&i.OwnerType,
		&i.OwnerID,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnvProviders = `-- name: ListEnvProviders :many
SELECT id, name, platform, description, base_urls, api_key, model, haiku_model, sonnet_model, opus_model, subagent_model, extra_env, owner_type, owner_id, slug, created_at, updated_at FROM env_providers ORDER BY name ASC
`

func (q *Queries) ListEnvProviders(ctx context.Context) ([]EnvProvider, error) {
	rows, err := q.db.QueryContext(ctx, listEnvProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvProvider{}
	for rows.Next() {
		var i EnvProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Platform,
			&i.Description,
			&i.BaseUrls,
			&i.ApiKey,
			&i.Model,
			&i.HaikuModel,
			&i.SonnetModel,
			&i.OpusModel,
			&i.SubagentModel,
			&i.ExtraEnv,
			&i.OwnerType,
			&i.OwnerID,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvProvidersForOwners = `-- name: ListEnvProvidersForOwners :many
SELECT id, name, platform, description, base_urls, api_key, model, haiku_model, sonnet_model, opus_model, subagent_model, extra_env, owner_type, owner_id, slug, created_at, updated_at FROM env_providers
WHERE (owner_type = 'user' AND owner_id = ?)
   OR (owner_type = 'org'  AND owner_id IN (/*SLICE:org_ids*/?))
   OR (owner_type = 'user' AND owner_id = 0)
ORDER BY created_at DESC
`

type ListEnvProvidersForOwnersParams struct {
	OwnerID int64   `json:"owner_id"`
	OrgIds  []int64 `json:"org_ids"`
}

// The third disjunct (owner_id = 0) surfaces system-wide defaults to every
// caller regardless of their personal or org scope, mirroring env_presets.
func (q *Queries) ListEnvProvidersForOwners(ctx context.Context, arg ListEnvProvidersForOwnersParams) ([]EnvProvider, error) {
	query := listEnvProvidersForOwners
	var queryParams []interface{}
	queryParams = append(queryParams, arg.OwnerID)
	if len(arg.OrgIds) > 0 {
		for _, v := range arg.OrgIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:org_ids*/?", strings.Repeat(",?", len(arg.OrgIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:org_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvProvider{}
	for rows.Next() {
		var i EnvProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Platform,
			&i.Description,
			&i.BaseUrls,
			&i.ApiKey,
			&i.Model,
			&i.HaikuModel,
			&i.SonnetModel,
			&i.OpusModel,
			&i.SubagentModel,
			&i.ExtraEnv,
			&i.OwnerType,
			&i.OwnerID,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnvProvider = `-- name: UpdateEnvProvider :exec
UPDATE env_providers
SET name = ?, platform = ?, description = ?, base_urls = ?, api_key = ?, model = ?,
    haiku_model = ?, sonnet_model = ?, opus_model = ?, subagent_model = ?, extra_env = ?, slug = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateEnvProviderParams struct {
	Name          string `json:"name"`
	Platform      string `json:"platform"`
	Description   string `json:"description"`
	BaseUrls      string `json:"base_urls"`
	ApiKey        string `json:"api_key"`
	Model         string `json:"model"`
	HaikuModel    string `json:"haiku_model"`
	SonnetModel   string `json:"sonnet_model"`
	OpusModel     string `json:"opus_model"`
	SubagentModel string `json:"subagent_model"`
	ExtraEnv      string `json:"extra_env"`
	Slug          string `json:"slug"`
	ID            int64  `json:"id"`
}

func (q *Queries) UpdateEnvProvider(ctx context.Context, arg UpdateEnvProviderParams) error {
	_, err := q.db.ExecContext(ctx, updateEnvProvider,
		arg.Name,
		arg.Platform,
		arg.Description,
		arg.BaseUrls,
		arg.ApiKey,
		arg.Model,
		arg.HaikuModel,
		arg.SonnetModel,
		arg.OpusModel,
		arg.SubagentModel,
		arg.ExtraEnv,
		arg.Slug,
		arg.ID,
	)
	return err
}
