// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: env_presets_owner_filter.sql

package store

import (
	"context"
	"strings"
)

const listEnvPresetsForOwners = `-- name: ListEnvPresetsForOwners :many
SELECT id, name, description, env, owner_type, owner_id, slug, created_at, updated_at FROM env_presets
WHERE (owner_type = 'user' AND owner_id = ?)
   OR (owner_type = 'org'  AND owner_id IN (/*SLICE:org_ids*/?))
   OR (owner_type = 'user' AND owner_id = 0)
ORDER BY created_at DESC
`

type ListEnvPresetsForOwnersParams struct {
	OwnerID int64   `json:"owner_id"`
	OrgIds  []int64 `json:"org_ids"`
}

// The third disjunct (owner_id = 0) surfaces system defaults seeded by
// EnvPresetService.SeedDefaults to every caller regardless of their personal
// or org scope. owner_id 0 is the schema-level sentinel for "no real owner"
// (real users start at id=1; the CHECK constraint forces owner_type='user'
// so seeded rows pass schema validation while still being globally visible).
func (q *Queries) ListEnvPresetsForOwners(ctx context.Context, arg ListEnvPresetsForOwnersParams) ([]EnvPreset, error) {
	query := listEnvPresetsForOwners
	var queryParams []interface{}
	queryParams = append(queryParams, arg.OwnerID)
	if len(arg.OrgIds) > 0 {
		for _, v := range arg.OrgIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:org_ids*/?", strings.Repeat(",?", len(arg.OrgIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:org_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvPreset{}
	for rows.Next() {
		var i EnvPreset
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Env,
			&i.OwnerType,
			&i.OwnerID,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
