// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: env_accounts.sql

package store

import (
	"context"
	"strings"
)

const createEnvAccount = `-- name: CreateEnvAccount :one
INSERT INTO env_accounts (name, platform, description, api_key, owner_type, owner_id, slug)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, platform, description, api_key, owner_type, owner_id, slug, created_at, updated_at
`

type CreateEnvAccountParams struct {
	Name        string `json:"name"`
	Platform    string `json:"platform"`
	Description string `json:"description"`
	ApiKey      string `json:"api_key"`
	OwnerType   string `json:"owner_type"`
	OwnerID     int64  `json:"owner_id"`
	Slug        string `json:"slug"`
}

func (q *Queries) CreateEnvAccount(ctx context.Context, arg CreateEnvAccountParams) (EnvAccount, error) {
	row := q.db.QueryRowContext(ctx, createEnvAccount,
		arg.Name,
		arg.Platform,
		arg.Description,
		arg.ApiKey,
		arg.OwnerType,
		arg.OwnerID,
		arg.Slug,
	)
	var i EnvAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Platform,
		&i.Description,
		&i.ApiKey,
		&i.OwnerType,
		&i.OwnerID,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEnvAccount = `-- name: DeleteEnvAccount :exec
DELETE FROM env_accounts WHERE id = ?
`

func (q *Queries) DeleteEnvAccount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEnvAccount, id)
	return err
}

const getEnvAccount = `-- name: GetEnvAccount :one
SELECT id, name, platform, description, api_key, owner_type, owner_id, slug, created_at, updated_at FROM env_accounts WHERE id = ?
`

func (q *Queries) GetEnvAccount(ctx context.Context, id int64) (EnvAccount, error) {
	row := q.db.QueryRowContext(ctx, getEnvAccount, id)
	var i EnvAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Platform,
		&i.Description,
		&i.ApiKey,
		&i.OwnerType,
		&i.OwnerID,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvAccountByName = `-- name: GetEnvAccountByName :one
SELECT id, name, platform, description, api_key, owner_type, owner_id, slug, created_at, updated_at FROM env_accounts WHERE name = ?
`

func (q *Queries) GetEnvAccountByName(ctx context.Context, name string) (EnvAccount, error) {
	row := q.db.QueryRowContext(ctx, getEnvAccountByName, name)
	var i EnvAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Platform,
		&i.Description,
		&i.ApiKey,
		&i.OwnerType,
		&i.OwnerID,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnvAccounts = `-- name: ListEnvAccounts :many
SELECT id, name, platform, description, api_key, owner_type, owner_id, slug, created_at, updated_at FROM env_accounts ORDER BY name ASC
`

func (q *Queries) ListEnvAccounts(ctx context.Context) ([]EnvAccount, error) {
	rows, err := q.db.QueryContext(ctx, listEnvAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvAccount{}
	for rows.Next() {
		var i EnvAccount
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Platform,
			&i.Description,
			&i.ApiKey,
			&i.OwnerType,
			&i.OwnerID,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvAccountsForOwners = `-- name: ListEnvAccountsForOwners :many
SELECT id, name, platform, description, api_key, owner_type, owner_id, slug, created_at, updated_at FROM env_accounts
WHERE (owner_type = 'user' AND owner_id = ?)
   OR (owner_type = 'org'  AND owner_id IN (/*SLICE:org_ids*/?))
   OR (owner_type = 'user' AND owner_id = 0)
ORDER BY created_at DESC
`

type ListEnvAccountsForOwnersParams struct {
	OwnerID int64   `json:"owner_id"`
	OrgIds  []int64 `json:"org_ids"`
}

// The third disjunct (owner_id = 0) surfaces system-wide defaults to every
// caller regardless of their personal or org scope, mirroring env_presets.
func (q *Queries) ListEnvAccountsForOwners(ctx context.Context, arg ListEnvAccountsForOwnersParams) ([]EnvAccount, error) {
	query := listEnvAccountsForOwners
	var queryParams []interface{}
	queryParams = append(queryParams, arg.OwnerID)
	if len(arg.OrgIds) > 0 {
		for _, v := range arg.OrgIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:org_ids*/?", strings.Repeat(",?", len(arg.OrgIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:org_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvAccount{}
	for rows.Next() {
		var i EnvAccount
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Platform,
			&i.Description,
			&i.ApiKey,
			&i.OwnerType,
			&i.OwnerID,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnvAccount = `-- name: UpdateEnvAccount :exec
UPDATE env_accounts
SET name = ?, platform = ?, description = ?, api_key = ?, slug = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateEnvAccountParams struct {
	Name        string `json:"name"`
	Platform    string `json:"platform"`
	Description string `json:"description"`
	ApiKey      string `json:"api_key"`
	Slug        string `json:"slug"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateEnvAccount(ctx context.Context, arg UpdateEnvAccountParams) error {
	_, err := q.db.ExecContext(ctx, updateEnvAccount,
		arg.Name,
		arg.Platform,
		arg.Description,
		arg.ApiKey,
		arg.Slug,
		arg.ID,
	)
	return err
}
