// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: external_issues.sql

package store

import (
	"context"
	"database/sql"
	"strings"
)

const batchFindImportedExternalIDs = `-- name: BatchFindImportedExternalIDs :many
SELECT i.external_id, i.id AS issue_id, i.column_id
FROM issues i
JOIN columns c ON c.id = i.column_id
WHERE c.project_id = ? AND i.external_source = ?
  AND i.external_id IN (/*SLICE:external_ids*/?)
`

type BatchFindImportedExternalIDsParams struct {
	ProjectID      int64            `json:"project_id"`
	ExternalSource sql.NullString   `json:"external_source"`
	ExternalIds    []sql.NullString `json:"external_ids"`
}

type BatchFindImportedExternalIDsRow struct {
	ExternalID sql.NullString `json:"external_id"`
	IssueID    int64          `json:"issue_id"`
	ColumnID   int64          `json:"column_id"`
}

// Bulk "already imported" badge query for the browse panel. The slice
// placeholder expands into an IN list at code-gen time (sqlc.slice is
// supported by sqlc v1.30.0; see issue_assignees.sql / labels.sql for
// prior art in this repo).
func (q *Queries) BatchFindImportedExternalIDs(ctx context.Context, arg BatchFindImportedExternalIDsParams) ([]BatchFindImportedExternalIDsRow, error) {
	query := batchFindImportedExternalIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ProjectID)
	queryParams = append(queryParams, arg.ExternalSource)
	if len(arg.ExternalIds) > 0 {
		for _, v := range arg.ExternalIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:external_ids*/?", strings.Repeat(",?", len(arg.ExternalIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:external_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatchFindImportedExternalIDsRow{}
	for rows.Next() {
		var i BatchFindImportedExternalIDsRow
		if err := rows.Scan(&i.ExternalID, &i.IssueID, &i.ColumnID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findIssueByExternalKey = `-- name: FindIssueByExternalKey :one
SELECT i.id, i.column_id, i.title, i.description, i.priority, i.position, i.lifecycle_status, i.start_date, i.due_date, i.estimate_type, i.estimate, i.actual_time, i.external_source, i.external_id, i.external_url, i.external_snapshot_at, i.external_comments_snapshot, i.external_comments_snapshot_at, i.goal_condition, i.parent_issue_id, i.issue_type, i.exec_wave, i.exec_status, i.exec_status_reason, i.created_at, i.updated_at, i.created_by FROM issues i
JOIN columns c ON c.id = i.column_id
WHERE c.project_id = ? AND i.external_source = ? AND i.external_id = ?
`

type FindIssueByExternalKeyParams struct {
	ProjectID      int64          `json:"project_id"`
	ExternalSource sql.NullString `json:"external_source"`
	ExternalID     sql.NullString `json:"external_id"`
}

// Look up whether (provider, external_id) has already been imported into a
// given project. Returns the niuniu issue row when present.
func (q *Queries) FindIssueByExternalKey(ctx context.Context, arg FindIssueByExternalKeyParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, findIssueByExternalKey, arg.ProjectID, arg.ExternalSource, arg.ExternalID)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Position,
		&i.LifecycleStatus,
		&i.StartDate,
		&i.DueDate,
		&i.EstimateType,
		&i.Estimate,
		&i.ActualTime,
		&i.ExternalSource,
		&i.ExternalID,
		&i.ExternalUrl,
		&i.ExternalSnapshotAt,
		&i.ExternalCommentsSnapshot,
		&i.ExternalCommentsSnapshotAt,
		&i.GoalCondition,
		&i.ParentIssueID,
		&i.IssueType,
		&i.ExecWave,
		&i.ExecStatus,
		&i.ExecStatusReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const insertImportedIssue = `-- name: InsertImportedIssue :one
INSERT OR IGNORE INTO issues (
    column_id, title, description, position,
    external_source, external_id, external_url, external_snapshot_at
) VALUES (?, ?, ?, 0, ?, ?, ?, CURRENT_TIMESTAMP)
RETURNING id, column_id, title, description, priority, position, lifecycle_status, start_date, due_date, estimate_type, estimate, actual_time, external_source, external_id, external_url, external_snapshot_at, external_comments_snapshot, external_comments_snapshot_at, goal_condition, parent_issue_id, issue_type, exec_wave, exec_status, exec_status_reason, created_at, updated_at, created_by
`

type InsertImportedIssueParams struct {
	ColumnID       int64          `json:"column_id"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	ExternalSource sql.NullString `json:"external_source"`
	ExternalID     sql.NullString `json:"external_id"`
	ExternalUrl    sql.NullString `json:"external_url"`
}

// INSERT OR IGNORE so a concurrent import retry on the same external key
// is a no-op (the SQLite engine returns no row, the PG wrapper rewrites to
// ON CONFLICT DO NOTHING). The caller treats sql.ErrNoRows as "already
// imported, look it up via FindIssueByExternalKey".
func (q *Queries) InsertImportedIssue(ctx context.Context, arg InsertImportedIssueParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, insertImportedIssue,
		arg.ColumnID,
		arg.Title,
		arg.Description,
		arg.ExternalSource,
		arg.ExternalID,
		arg.ExternalUrl,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Position,
		&i.LifecycleStatus,
		&i.StartDate,
		&i.DueDate,
		&i.EstimateType,
		&i.Estimate,
		&i.ActualTime,
		&i.ExternalSource,
		&i.ExternalID,
		&i.ExternalUrl,
		&i.ExternalSnapshotAt,
		&i.ExternalCommentsSnapshot,
		&i.ExternalCommentsSnapshotAt,
		&i.GoalCondition,
		&i.ParentIssueID,
		&i.IssueType,
		&i.ExecWave,
		&i.ExecStatus,
		&i.ExecStatusReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const refreshIssueSnapshot = `-- name: RefreshIssueSnapshot :one
UPDATE issues
SET title = ?, description = ?,
    external_snapshot_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND external_source != ''
RETURNING id, column_id, title, description, priority, position, lifecycle_status, start_date, due_date, estimate_type, estimate, actual_time, external_source, external_id, external_url, external_snapshot_at, external_comments_snapshot, external_comments_snapshot_at, goal_condition, parent_issue_id, issue_type, exec_wave, exec_status, exec_status_reason, created_at, updated_at, created_by
`

type RefreshIssueSnapshotParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	ID          int64          `json:"id"`
}

// Re-pull title/description from the upstream source. Guarded by
// external_source != ” so a stray refresh against a niuniu-only issue
// is a no-op (returns no row).
func (q *Queries) RefreshIssueSnapshot(ctx context.Context, arg RefreshIssueSnapshotParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, refreshIssueSnapshot, arg.Title, arg.Description, arg.ID)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Position,
		&i.LifecycleStatus,
		&i.StartDate,
		&i.DueDate,
		&i.EstimateType,
		&i.Estimate,
		&i.ActualTime,
		&i.ExternalSource,
		&i.ExternalID,
		&i.ExternalUrl,
		&i.ExternalSnapshotAt,
		&i.ExternalCommentsSnapshot,
		&i.ExternalCommentsSnapshotAt,
		&i.GoalCondition,
		&i.ParentIssueID,
		&i.IssueType,
		&i.ExecWave,
		&i.ExecStatus,
		&i.ExecStatusReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const updateIssueExternalCommentsSnapshot = `-- name: UpdateIssueExternalCommentsSnapshot :exec
UPDATE issues
SET external_comments_snapshot = ?,
    external_comments_snapshot_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND external_source != ''
`

type UpdateIssueExternalCommentsSnapshotParams struct {
	ExternalCommentsSnapshot sql.NullString `json:"external_comments_snapshot"`
	ID                       int64          `json:"id"`
}

// v1.1: store the JSON-serialized read-only snapshot of external comments
// pulled by RefreshFromExternal. Guarded by external_source != ” so a
// stray write to a niuniu-only issue is a no-op.
func (q *Queries) UpdateIssueExternalCommentsSnapshot(ctx context.Context, arg UpdateIssueExternalCommentsSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, updateIssueExternalCommentsSnapshot, arg.ExternalCommentsSnapshot, arg.ID)
	return err
}
