// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: external_providers.sql

package store

import (
	"context"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO external_api_audit (user_id, provider_id, method, path, status_code)
VALUES (?, ?, ?, ?, ?)
`

type CreateAuditLogParams struct {
	UserID     int64  `json:"user_id"`
	ProviderID int64  `json:"provider_id"`
	Method     string `json:"method"`
	Path       string `json:"path"`
	StatusCode int64  `json:"status_code"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, createAuditLog,
		arg.UserID,
		arg.ProviderID,
		arg.Method,
		arg.Path,
		arg.StatusCode,
	)
	return err
}

const createProvider = `-- name: CreateProvider :one
INSERT INTO external_providers (name, label, api_base_url, auth_type, auth_header, auth_prefix, profile, openapi_url, whitelist, enabled, created_by)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, label, api_base_url, auth_type, auth_header, auth_prefix, profile, openapi_url, whitelist, enabled, created_by, created_at, updated_at
`

type CreateProviderParams struct {
	Name       string `json:"name"`
	Label      string `json:"label"`
	ApiBaseUrl string `json:"api_base_url"`
	AuthType   string `json:"auth_type"`
	AuthHeader string `json:"auth_header"`
	AuthPrefix string `json:"auth_prefix"`
	Profile    string `json:"profile"`
	OpenapiUrl string `json:"openapi_url"`
	Whitelist  string `json:"whitelist"`
	Enabled    int64  `json:"enabled"`
	CreatedBy  string `json:"created_by"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (ExternalProvider, error) {
	row := q.db.QueryRowContext(ctx, createProvider,
		arg.Name,
		arg.Label,
		arg.ApiBaseUrl,
		arg.AuthType,
		arg.AuthHeader,
		arg.AuthPrefix,
		arg.Profile,
		arg.OpenapiUrl,
		arg.Whitelist,
		arg.Enabled,
		arg.CreatedBy,
	)
	var i ExternalProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Label,
		&i.ApiBaseUrl,
		&i.AuthType,
		&i.AuthHeader,
		&i.AuthPrefix,
		&i.Profile,
		&i.OpenapiUrl,
		&i.Whitelist,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProvider = `-- name: DeleteProvider :exec
DELETE FROM external_providers WHERE id = ?
`

func (q *Queries) DeleteProvider(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProvider, id)
	return err
}

const getAPIWritePrefs = `-- name: GetAPIWritePrefs :one
SELECT user_id, provider_id, enabled FROM external_api_write_prefs WHERE user_id = ? AND provider_id = ?
`

type GetAPIWritePrefsParams struct {
	UserID     int64 `json:"user_id"`
	ProviderID int64 `json:"provider_id"`
}

func (q *Queries) GetAPIWritePrefs(ctx context.Context, arg GetAPIWritePrefsParams) (ExternalApiWritePref, error) {
	row := q.db.QueryRowContext(ctx, getAPIWritePrefs, arg.UserID, arg.ProviderID)
	var i ExternalApiWritePref
	err := row.Scan(&i.UserID, &i.ProviderID, &i.Enabled)
	return i, err
}

const getProviderByID = `-- name: GetProviderByID :one
SELECT id, name, label, api_base_url, auth_type, auth_header, auth_prefix, profile, openapi_url, whitelist, enabled, created_by, created_at, updated_at FROM external_providers WHERE id = ?
`

func (q *Queries) GetProviderByID(ctx context.Context, id int64) (ExternalProvider, error) {
	row := q.db.QueryRowContext(ctx, getProviderByID, id)
	var i ExternalProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Label,
		&i.ApiBaseUrl,
		&i.AuthType,
		&i.AuthHeader,
		&i.AuthPrefix,
		&i.Profile,
		&i.OpenapiUrl,
		&i.Whitelist,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderByName = `-- name: GetProviderByName :one
SELECT id, name, label, api_base_url, auth_type, auth_header, auth_prefix, profile, openapi_url, whitelist, enabled, created_by, created_at, updated_at FROM external_providers WHERE name = ?
`

func (q *Queries) GetProviderByName(ctx context.Context, name string) (ExternalProvider, error) {
	row := q.db.QueryRowContext(ctx, getProviderByName, name)
	var i ExternalProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Label,
		&i.ApiBaseUrl,
		&i.AuthType,
		&i.AuthHeader,
		&i.AuthPrefix,
		&i.Profile,
		&i.OpenapiUrl,
		&i.Whitelist,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPIWritePrefsForUser = `-- name: ListAPIWritePrefsForUser :many
SELECT user_id, provider_id, enabled FROM external_api_write_prefs WHERE user_id = ?
`

func (q *Queries) ListAPIWritePrefsForUser(ctx context.Context, userID int64) ([]ExternalApiWritePref, error) {
	rows, err := q.db.QueryContext(ctx, listAPIWritePrefsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalApiWritePref{}
	for rows.Next() {
		var i ExternalApiWritePref
		if err := rows.Scan(&i.UserID, &i.ProviderID, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, user_id, provider_id, method, path, status_code, created_at FROM external_api_audit ORDER BY created_at DESC LIMIT ?
`

func (q *Queries) ListAuditLogs(ctx context.Context, limit int64) ([]ExternalApiAudit, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalApiAudit{}
	for rows.Next() {
		var i ExternalApiAudit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProviderID,
			&i.Method,
			&i.Path,
			&i.StatusCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviders = `-- name: ListProviders :many
SELECT id, name, label, api_base_url, auth_type, auth_header, auth_prefix, profile, openapi_url, whitelist, enabled, created_by, created_at, updated_at FROM external_providers ORDER BY name
`

func (q *Queries) ListProviders(ctx context.Context) ([]ExternalProvider, error) {
	rows, err := q.db.QueryContext(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalProvider{}
	for rows.Next() {
		var i ExternalProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Label,
			&i.ApiBaseUrl,
			&i.AuthType,
			&i.AuthHeader,
			&i.AuthPrefix,
			&i.Profile,
			&i.OpenapiUrl,
			&i.Whitelist,
			&i.Enabled,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE external_providers
SET label = ?, api_base_url = ?, auth_type = ?, auth_header = ?, auth_prefix = ?,
    profile = ?, openapi_url = ?, whitelist = ?, enabled = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, label, api_base_url, auth_type, auth_header, auth_prefix, profile, openapi_url, whitelist, enabled, created_by, created_at, updated_at
`

type UpdateProviderParams struct {
	Label      string `json:"label"`
	ApiBaseUrl string `json:"api_base_url"`
	AuthType   string `json:"auth_type"`
	AuthHeader string `json:"auth_header"`
	AuthPrefix string `json:"auth_prefix"`
	Profile    string `json:"profile"`
	OpenapiUrl string `json:"openapi_url"`
	Whitelist  string `json:"whitelist"`
	Enabled    int64  `json:"enabled"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (ExternalProvider, error) {
	row := q.db.QueryRowContext(ctx, updateProvider,
		arg.Label,
		arg.ApiBaseUrl,
		arg.AuthType,
		arg.AuthHeader,
		arg.AuthPrefix,
		arg.Profile,
		arg.OpenapiUrl,
		arg.Whitelist,
		arg.Enabled,
		arg.ID,
	)
	var i ExternalProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Label,
		&i.ApiBaseUrl,
		&i.AuthType,
		&i.AuthHeader,
		&i.AuthPrefix,
		&i.Profile,
		&i.OpenapiUrl,
		&i.Whitelist,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAPIWritePrefs = `-- name: UpsertAPIWritePrefs :exec
INSERT INTO external_api_write_prefs (user_id, provider_id, enabled)
VALUES (?, ?, ?)
ON CONFLICT(user_id, provider_id) DO UPDATE SET enabled = excluded.enabled
`

type UpsertAPIWritePrefsParams struct {
	UserID     int64 `json:"user_id"`
	ProviderID int64 `json:"provider_id"`
	Enabled    int64 `json:"enabled"`
}

func (q *Queries) UpsertAPIWritePrefs(ctx context.Context, arg UpsertAPIWritePrefsParams) error {
	_, err := q.db.ExecContext(ctx, upsertAPIWritePrefs, arg.UserID, arg.ProviderID, arg.Enabled)
	return err
}
