// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: external_credentials.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const countSourcesUsingCredential = `-- name: CountSourcesUsingCredential :one
SELECT COUNT(*) FROM project_external_sources WHERE credential_id = ?
`

func (q *Queries) CountSourcesUsingCredential(ctx context.Context, credentialID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSourcesUsingCredential, credentialID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExternalCredential = `-- name: CreateExternalCredential :one
INSERT INTO external_provider_credentials (
    owner_type, owner_id, user_id, provider, alias, config, last_verified_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, owner_type, owner_id, user_id, provider, alias, config, last_verified_at, created_at, updated_at
`

type CreateExternalCredentialParams struct {
	OwnerType      string       `json:"owner_type"`
	OwnerID        int64        `json:"owner_id"`
	UserID         int64        `json:"user_id"`
	Provider       string       `json:"provider"`
	Alias          string       `json:"alias"`
	Config         string       `json:"config"`
	LastVerifiedAt sql.NullTime `json:"last_verified_at"`
}

func (q *Queries) CreateExternalCredential(ctx context.Context, arg CreateExternalCredentialParams) (ExternalProviderCredential, error) {
	row := q.db.QueryRowContext(ctx, createExternalCredential,
		arg.OwnerType,
		arg.OwnerID,
		arg.UserID,
		arg.Provider,
		arg.Alias,
		arg.Config,
		arg.LastVerifiedAt,
	)
	var i ExternalProviderCredential
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.UserID,
		&i.Provider,
		&i.Alias,
		&i.Config,
		&i.LastVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExternalCredentialByID = `-- name: DeleteExternalCredentialByID :exec
DELETE FROM external_provider_credentials
WHERE id = ? AND owner_type = ? AND owner_id = ? AND user_id = ?
`

type DeleteExternalCredentialByIDParams struct {
	ID        int64  `json:"id"`
	OwnerType string `json:"owner_type"`
	OwnerID   int64  `json:"owner_id"`
	UserID    int64  `json:"user_id"`
}

func (q *Queries) DeleteExternalCredentialByID(ctx context.Context, arg DeleteExternalCredentialByIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteExternalCredentialByID,
		arg.ID,
		arg.OwnerType,
		arg.OwnerID,
		arg.UserID,
	)
	return err
}

const getExternalCredentialByID = `-- name: GetExternalCredentialByID :one
SELECT id, owner_type, owner_id, user_id, provider, alias, config, last_verified_at, created_at, updated_at FROM external_provider_credentials
WHERE id = ? AND owner_type = ? AND owner_id = ? AND user_id = ?
`

type GetExternalCredentialByIDParams struct {
	ID        int64  `json:"id"`
	OwnerType string `json:"owner_type"`
	OwnerID   int64  `json:"owner_id"`
	UserID    int64  `json:"user_id"`
}

func (q *Queries) GetExternalCredentialByID(ctx context.Context, arg GetExternalCredentialByIDParams) (ExternalProviderCredential, error) {
	row := q.db.QueryRowContext(ctx, getExternalCredentialByID,
		arg.ID,
		arg.OwnerType,
		arg.OwnerID,
		arg.UserID,
	)
	var i ExternalProviderCredential
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.UserID,
		&i.Provider,
		&i.Alias,
		&i.Config,
		&i.LastVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExternalCredentialsForUser = `-- name: ListExternalCredentialsForUser :many
SELECT id, owner_type, owner_id, user_id, provider, alias, config, last_verified_at, created_at, updated_at FROM external_provider_credentials
WHERE owner_type = ? AND owner_id = ? AND user_id = ?
ORDER BY provider, alias
`

type ListExternalCredentialsForUserParams struct {
	OwnerType string `json:"owner_type"`
	OwnerID   int64  `json:"owner_id"`
	UserID    int64  `json:"user_id"`
}

func (q *Queries) ListExternalCredentialsForUser(ctx context.Context, arg ListExternalCredentialsForUserParams) ([]ExternalProviderCredential, error) {
	rows, err := q.db.QueryContext(ctx, listExternalCredentialsForUser, arg.OwnerType, arg.OwnerID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalProviderCredential{}
	for rows.Next() {
		var i ExternalProviderCredential
		if err := rows.Scan(
			&i.ID,
			&i.OwnerType,
			&i.OwnerID,
			&i.UserID,
			&i.Provider,
			&i.Alias,
			&i.Config,
			&i.LastVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalCredentialsForUserByProvider = `-- name: ListExternalCredentialsForUserByProvider :many
SELECT id, owner_type, owner_id, user_id, provider, alias, config, last_verified_at, created_at, updated_at FROM external_provider_credentials
WHERE owner_type = ? AND owner_id = ? AND user_id = ? AND provider = ?
ORDER BY alias
`

type ListExternalCredentialsForUserByProviderParams struct {
	OwnerType string `json:"owner_type"`
	OwnerID   int64  `json:"owner_id"`
	UserID    int64  `json:"user_id"`
	Provider  string `json:"provider"`
}

func (q *Queries) ListExternalCredentialsForUserByProvider(ctx context.Context, arg ListExternalCredentialsForUserByProviderParams) ([]ExternalProviderCredential, error) {
	rows, err := q.db.QueryContext(ctx, listExternalCredentialsForUserByProvider,
		arg.OwnerType,
		arg.OwnerID,
		arg.UserID,
		arg.Provider,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalProviderCredential{}
	for rows.Next() {
		var i ExternalProviderCredential
		if err := rows.Scan(
			&i.ID,
			&i.OwnerType,
			&i.OwnerID,
			&i.UserID,
			&i.Provider,
			&i.Alias,
			&i.Config,
			&i.LastVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourcesUsingCredential = `-- name: ListSourcesUsingCredential :many
SELECT pes.id, pes.project_id, pes.provider, pes.source_key, pes.credential_id, pes.config, pes.created_at, p.name AS project_name
FROM project_external_sources pes
JOIN projects p ON p.id = pes.project_id
WHERE pes.credential_id = ?
ORDER BY p.name, pes.source_key
`

type ListSourcesUsingCredentialRow struct {
	ID           int64         `json:"id"`
	ProjectID    int64         `json:"project_id"`
	Provider     string        `json:"provider"`
	SourceKey    string        `json:"source_key"`
	CredentialID sql.NullInt64 `json:"credential_id"`
	Config       string        `json:"config"`
	CreatedAt    time.Time     `json:"created_at"`
	ProjectName  string        `json:"project_name"`
}

func (q *Queries) ListSourcesUsingCredential(ctx context.Context, credentialID sql.NullInt64) ([]ListSourcesUsingCredentialRow, error) {
	rows, err := q.db.QueryContext(ctx, listSourcesUsingCredential, credentialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSourcesUsingCredentialRow{}
	for rows.Next() {
		var i ListSourcesUsingCredentialRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Provider,
			&i.SourceKey,
			&i.CredentialID,
			&i.Config,
			&i.CreatedAt,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameExternalCredential = `-- name: RenameExternalCredential :one
UPDATE external_provider_credentials
SET alias = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND owner_type = ? AND owner_id = ? AND user_id = ?
RETURNING id, owner_type, owner_id, user_id, provider, alias, config, last_verified_at, created_at, updated_at
`

type RenameExternalCredentialParams struct {
	Alias     string `json:"alias"`
	ID        int64  `json:"id"`
	OwnerType string `json:"owner_type"`
	OwnerID   int64  `json:"owner_id"`
	UserID    int64  `json:"user_id"`
}

func (q *Queries) RenameExternalCredential(ctx context.Context, arg RenameExternalCredentialParams) (ExternalProviderCredential, error) {
	row := q.db.QueryRowContext(ctx, renameExternalCredential,
		arg.Alias,
		arg.ID,
		arg.OwnerType,
		arg.OwnerID,
		arg.UserID,
	)
	var i ExternalProviderCredential
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.UserID,
		&i.Provider,
		&i.Alias,
		&i.Config,
		&i.LastVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchCredentialVerifiedAtByID = `-- name: TouchCredentialVerifiedAtByID :exec
UPDATE external_provider_credentials
SET last_verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND owner_type = ? AND owner_id = ? AND user_id = ?
`

type TouchCredentialVerifiedAtByIDParams struct {
	ID        int64  `json:"id"`
	OwnerType string `json:"owner_type"`
	OwnerID   int64  `json:"owner_id"`
	UserID    int64  `json:"user_id"`
}

func (q *Queries) TouchCredentialVerifiedAtByID(ctx context.Context, arg TouchCredentialVerifiedAtByIDParams) error {
	_, err := q.db.ExecContext(ctx, touchCredentialVerifiedAtByID,
		arg.ID,
		arg.OwnerType,
		arg.OwnerID,
		arg.UserID,
	)
	return err
}

const updateExternalCredentialConfig = `-- name: UpdateExternalCredentialConfig :one
UPDATE external_provider_credentials
SET config = ?, last_verified_at = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND owner_type = ? AND owner_id = ? AND user_id = ?
RETURNING id, owner_type, owner_id, user_id, provider, alias, config, last_verified_at, created_at, updated_at
`

type UpdateExternalCredentialConfigParams struct {
	Config    string `json:"config"`
	ID        int64  `json:"id"`
	OwnerType string `json:"owner_type"`
	OwnerID   int64  `json:"owner_id"`
	UserID    int64  `json:"user_id"`
}

func (q *Queries) UpdateExternalCredentialConfig(ctx context.Context, arg UpdateExternalCredentialConfigParams) (ExternalProviderCredential, error) {
	row := q.db.QueryRowContext(ctx, updateExternalCredentialConfig,
		arg.Config,
		arg.ID,
		arg.OwnerType,
		arg.OwnerID,
		arg.UserID,
	)
	var i ExternalProviderCredential
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.UserID,
		&i.Provider,
		&i.Alias,
		&i.Config,
		&i.LastVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
