// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: harnesses.sql

// harnesses, harness_phases, harness_phase_agents, harness_phase_gates removed
// in Phase 7 (drop_legacy_phase7_v1). All queries were deleted.

package store
