// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: harness_specs.sql

package store

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const createHarnessCheck = `-- name: CreateHarnessCheck :one

INSERT INTO harness_checks (workspace_id, run_id, spec_id, phase_name, status, message, details, duration_ms, cost_usd)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, workspace_id, run_id, spec_id, phase_name, status, message, details, duration_ms, cost_usd, created_at
`

type CreateHarnessCheckParams struct {
	WorkspaceID int64         `json:"workspace_id"`
	RunID       sql.NullInt64 `json:"run_id"`
	SpecID      int64         `json:"spec_id"`
	PhaseName   string        `json:"phase_name"`
	Status      string        `json:"status"`
	Message     string        `json:"message"`
	Details     string        `json:"details"`
	DurationMs  int64         `json:"duration_ms"`
	CostUsd     float64       `json:"cost_usd"`
}

// GetProjectIDForWorkspace is defined in workspaces.sql; reuse it from there
// for project-scoped pre_commit and on_schedule lookup (per workspace-model
// architecture: workspace <-> issue <-> project is 1:1).
func (q *Queries) CreateHarnessCheck(ctx context.Context, arg CreateHarnessCheckParams) (HarnessCheck, error) {
	row := q.db.QueryRowContext(ctx, createHarnessCheck,
		arg.WorkspaceID,
		arg.RunID,
		arg.SpecID,
		arg.PhaseName,
		arg.Status,
		arg.Message,
		arg.Details,
		arg.DurationMs,
		arg.CostUsd,
	)
	var i HarnessCheck
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RunID,
		&i.SpecID,
		&i.PhaseName,
		&i.Status,
		&i.Message,
		&i.Details,
		&i.DurationMs,
		&i.CostUsd,
		&i.CreatedAt,
	)
	return i, err
}

const createHarnessSpec = `-- name: CreateHarnessSpec :one
INSERT INTO harness_specs (
    category, name, enabled, severity, config,
    kind, target, pattern, pattern_flags, command, timeout_sec,
    expected_exit_code, extract_regex, threshold_value, threshold_op,
    file_paths, trigger_on, judge_prompt, judge_model
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, category, name, enabled, severity, config, kind, target, pattern, pattern_flags, command, timeout_sec, expected_exit_code, extract_regex, threshold_value, threshold_op, file_paths, trigger_on, judge_prompt, judge_model, created_at, updated_at
`

type CreateHarnessSpecParams struct {
	Category         string  `json:"category"`
	Name             string  `json:"name"`
	Enabled          int64   `json:"enabled"`
	Severity         string  `json:"severity"`
	Config           string  `json:"config"`
	Kind             string  `json:"kind"`
	Target           string  `json:"target"`
	Pattern          string  `json:"pattern"`
	PatternFlags     string  `json:"pattern_flags"`
	Command          string  `json:"command"`
	TimeoutSec       int64   `json:"timeout_sec"`
	ExpectedExitCode int64   `json:"expected_exit_code"`
	ExtractRegex     string  `json:"extract_regex"`
	ThresholdValue   float64 `json:"threshold_value"`
	ThresholdOp      string  `json:"threshold_op"`
	FilePaths        string  `json:"file_paths"`
	TriggerOn        string  `json:"trigger_on"`
	JudgePrompt      string  `json:"judge_prompt"`
	JudgeModel       string  `json:"judge_model"`
}

func (q *Queries) CreateHarnessSpec(ctx context.Context, arg CreateHarnessSpecParams) (HarnessSpec, error) {
	row := q.db.QueryRowContext(ctx, createHarnessSpec,
		arg.Category,
		arg.Name,
		arg.Enabled,
		arg.Severity,
		arg.Config,
		arg.Kind,
		arg.Target,
		arg.Pattern,
		arg.PatternFlags,
		arg.Command,
		arg.TimeoutSec,
		arg.ExpectedExitCode,
		arg.ExtractRegex,
		arg.ThresholdValue,
		arg.ThresholdOp,
		arg.FilePaths,
		arg.TriggerOn,
		arg.JudgePrompt,
		arg.JudgeModel,
	)
	var i HarnessSpec
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Name,
		&i.Enabled,
		&i.Severity,
		&i.Config,
		&i.Kind,
		&i.Target,
		&i.Pattern,
		&i.PatternFlags,
		&i.Command,
		&i.TimeoutSec,
		&i.ExpectedExitCode,
		&i.ExtractRegex,
		&i.ThresholdValue,
		&i.ThresholdOp,
		&i.FilePaths,
		&i.TriggerOn,
		&i.JudgePrompt,
		&i.JudgeModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHarnessSpec = `-- name: DeleteHarnessSpec :exec
DELETE FROM harness_specs WHERE id = ?
`

func (q *Queries) DeleteHarnessSpec(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteHarnessSpec, id)
	return err
}

const getHarnessSpec = `-- name: GetHarnessSpec :one
SELECT id, category, name, enabled, severity, config, kind, target, pattern, pattern_flags, command, timeout_sec, expected_exit_code, extract_regex, threshold_value, threshold_op, file_paths, trigger_on, judge_prompt, judge_model, created_at, updated_at FROM harness_specs WHERE id = ?
`

func (q *Queries) GetHarnessSpec(ctx context.Context, id int64) (HarnessSpec, error) {
	row := q.db.QueryRowContext(ctx, getHarnessSpec, id)
	var i HarnessSpec
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Name,
		&i.Enabled,
		&i.Severity,
		&i.Config,
		&i.Kind,
		&i.Target,
		&i.Pattern,
		&i.PatternFlags,
		&i.Command,
		&i.TimeoutSec,
		&i.ExpectedExitCode,
		&i.ExtractRegex,
		&i.ThresholdValue,
		&i.ThresholdOp,
		&i.FilePaths,
		&i.TriggerOn,
		&i.JudgePrompt,
		&i.JudgeModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHarnessSpecsByIDs = `-- name: GetHarnessSpecsByIDs :many
SELECT id, category, name, enabled, severity, config, kind, target, pattern, pattern_flags, command, timeout_sec, expected_exit_code, extract_regex, threshold_value, threshold_op, file_paths, trigger_on, judge_prompt, judge_model, created_at, updated_at FROM harness_specs WHERE id IN (/*SLICE:ids*/?)
`

// Batched form of GetHarnessSpec for resolving many specs at once (e.g. the
// gate-spec briefs across a project's columns) instead of one query per spec.
func (q *Queries) GetHarnessSpecsByIDs(ctx context.Context, ids []int64) ([]HarnessSpec, error) {
	query := getHarnessSpecsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HarnessSpec{}
	for rows.Next() {
		var i HarnessSpec
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Name,
			&i.Enabled,
			&i.Severity,
			&i.Config,
			&i.Kind,
			&i.Target,
			&i.Pattern,
			&i.PatternFlags,
			&i.Command,
			&i.TimeoutSec,
			&i.ExpectedExitCode,
			&i.ExtractRegex,
			&i.ThresholdValue,
			&i.ThresholdOp,
			&i.FilePaths,
			&i.TriggerOn,
			&i.JudgePrompt,
			&i.JudgeModel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalHarnessSpecs = `-- name: ListGlobalHarnessSpecs :many
SELECT id, category, name, enabled, severity, config, kind, target, pattern, pattern_flags, command, timeout_sec, expected_exit_code, extract_regex, threshold_value, threshold_op, file_paths, trigger_on, judge_prompt, judge_model, created_at, updated_at FROM harness_specs ORDER BY category, name
`

// harness_specs is one global library (no owner / no scope columns).
func (q *Queries) ListGlobalHarnessSpecs(ctx context.Context) ([]HarnessSpec, error) {
	rows, err := q.db.QueryContext(ctx, listGlobalHarnessSpecs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HarnessSpec{}
	for rows.Next() {
		var i HarnessSpec
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Name,
			&i.Enabled,
			&i.Severity,
			&i.Config,
			&i.Kind,
			&i.Target,
			&i.Pattern,
			&i.PatternFlags,
			&i.Command,
			&i.TimeoutSec,
			&i.ExpectedExitCode,
			&i.ExtractRegex,
			&i.ThresholdValue,
			&i.ThresholdOp,
			&i.FilePaths,
			&i.TriggerOn,
			&i.JudgePrompt,
			&i.JudgeModel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHarnessChecksByRun = `-- name: ListHarnessChecksByRun :many
SELECT hc.id, hc.workspace_id, hc.run_id, hc.spec_id, hc.phase_name, hc.status, hc.message, hc.details, hc.duration_ms, hc.cost_usd, hc.created_at, hs.category, hs.name AS spec_name, hs.severity
FROM harness_checks hc
JOIN harness_specs hs ON hc.spec_id = hs.id
WHERE hc.run_id = ?
ORDER BY hc.created_at DESC
`

type ListHarnessChecksByRunRow struct {
	ID          int64         `json:"id"`
	WorkspaceID int64         `json:"workspace_id"`
	RunID       sql.NullInt64 `json:"run_id"`
	SpecID      int64         `json:"spec_id"`
	PhaseName   string        `json:"phase_name"`
	Status      string        `json:"status"`
	Message     string        `json:"message"`
	Details     string        `json:"details"`
	DurationMs  int64         `json:"duration_ms"`
	CostUsd     float64       `json:"cost_usd"`
	CreatedAt   time.Time     `json:"created_at"`
	Category    string        `json:"category"`
	SpecName    string        `json:"spec_name"`
	Severity    string        `json:"severity"`
}

func (q *Queries) ListHarnessChecksByRun(ctx context.Context, runID sql.NullInt64) ([]ListHarnessChecksByRunRow, error) {
	rows, err := q.db.QueryContext(ctx, listHarnessChecksByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHarnessChecksByRunRow{}
	for rows.Next() {
		var i ListHarnessChecksByRunRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RunID,
			&i.SpecID,
			&i.PhaseName,
			&i.Status,
			&i.Message,
			&i.Details,
			&i.DurationMs,
			&i.CostUsd,
			&i.CreatedAt,
			&i.Category,
			&i.SpecName,
			&i.Severity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHarnessChecksByWorkspace = `-- name: ListHarnessChecksByWorkspace :many
SELECT hc.id, hc.workspace_id, hc.run_id, hc.spec_id, hc.phase_name, hc.status, hc.message, hc.details, hc.duration_ms, hc.cost_usd, hc.created_at, hs.category, hs.name AS spec_name, hs.severity
FROM harness_checks hc
JOIN harness_specs hs ON hc.spec_id = hs.id
WHERE hc.workspace_id = ?
ORDER BY hc.created_at DESC
`

type ListHarnessChecksByWorkspaceRow struct {
	ID          int64         `json:"id"`
	WorkspaceID int64         `json:"workspace_id"`
	RunID       sql.NullInt64 `json:"run_id"`
	SpecID      int64         `json:"spec_id"`
	PhaseName   string        `json:"phase_name"`
	Status      string        `json:"status"`
	Message     string        `json:"message"`
	Details     string        `json:"details"`
	DurationMs  int64         `json:"duration_ms"`
	CostUsd     float64       `json:"cost_usd"`
	CreatedAt   time.Time     `json:"created_at"`
	Category    string        `json:"category"`
	SpecName    string        `json:"spec_name"`
	Severity    string        `json:"severity"`
}

func (q *Queries) ListHarnessChecksByWorkspace(ctx context.Context, workspaceID int64) ([]ListHarnessChecksByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listHarnessChecksByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHarnessChecksByWorkspaceRow{}
	for rows.Next() {
		var i ListHarnessChecksByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RunID,
			&i.SpecID,
			&i.PhaseName,
			&i.Status,
			&i.Message,
			&i.Details,
			&i.DurationMs,
			&i.CostUsd,
			&i.CreatedAt,
			&i.Category,
			&i.SpecName,
			&i.Severity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHarnessSpecsByTrigger = `-- name: ListHarnessSpecsByTrigger :many
SELECT id, category, name, enabled, severity, config, kind, target, pattern, pattern_flags, command, timeout_sec, expected_exit_code, extract_regex, threshold_value, threshold_op, file_paths, trigger_on, judge_prompt, judge_model, created_at, updated_at FROM harness_specs
WHERE enabled = 1 AND trigger_on = ?
ORDER BY category, name
`

func (q *Queries) ListHarnessSpecsByTrigger(ctx context.Context, triggerOn string) ([]HarnessSpec, error) {
	rows, err := q.db.QueryContext(ctx, listHarnessSpecsByTrigger, triggerOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HarnessSpec{}
	for rows.Next() {
		var i HarnessSpec
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Name,
			&i.Enabled,
			&i.Severity,
			&i.Config,
			&i.Kind,
			&i.Target,
			&i.Pattern,
			&i.PatternFlags,
			&i.Command,
			&i.TimeoutSec,
			&i.ExpectedExitCode,
			&i.ExtractRegex,
			&i.ThresholdValue,
			&i.ThresholdOp,
			&i.FilePaths,
			&i.TriggerOn,
			&i.JudgePrompt,
			&i.JudgeModel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHarnessSpec = `-- name: UpdateHarnessSpec :exec
UPDATE harness_specs SET
    enabled = ?, severity = ?, config = ?,
    kind = ?, target = ?, pattern = ?, pattern_flags = ?, command = ?,
    timeout_sec = ?, expected_exit_code = ?, extract_regex = ?,
    threshold_value = ?, threshold_op = ?, file_paths = ?, trigger_on = ?,
    judge_prompt = ?, judge_model = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateHarnessSpecParams struct {
	Enabled          int64   `json:"enabled"`
	Severity         string  `json:"severity"`
	Config           string  `json:"config"`
	Kind             string  `json:"kind"`
	Target           string  `json:"target"`
	Pattern          string  `json:"pattern"`
	PatternFlags     string  `json:"pattern_flags"`
	Command          string  `json:"command"`
	TimeoutSec       int64   `json:"timeout_sec"`
	ExpectedExitCode int64   `json:"expected_exit_code"`
	ExtractRegex     string  `json:"extract_regex"`
	ThresholdValue   float64 `json:"threshold_value"`
	ThresholdOp      string  `json:"threshold_op"`
	FilePaths        string  `json:"file_paths"`
	TriggerOn        string  `json:"trigger_on"`
	JudgePrompt      string  `json:"judge_prompt"`
	JudgeModel       string  `json:"judge_model"`
	ID               int64   `json:"id"`
}

func (q *Queries) UpdateHarnessSpec(ctx context.Context, arg UpdateHarnessSpecParams) error {
	_, err := q.db.ExecContext(ctx, updateHarnessSpec,
		arg.Enabled,
		arg.Severity,
		arg.Config,
		arg.Kind,
		arg.Target,
		arg.Pattern,
		arg.PatternFlags,
		arg.Command,
		arg.TimeoutSec,
		arg.ExpectedExitCode,
		arg.ExtractRegex,
		arg.ThresholdValue,
		arg.ThresholdOp,
		arg.FilePaths,
		arg.TriggerOn,
		arg.JudgePrompt,
		arg.JudgeModel,
		arg.ID,
	)
	return err
}
