// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issue_exec_events.sql

package store

import (
	"context"
	"database/sql"
)

const insertIssueExecEvent = `-- name: InsertIssueExecEvent :exec
INSERT INTO issue_exec_events (issue_id, workspace_id, kind, summary, detail_json, cost_usd)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertIssueExecEventParams struct {
	IssueID     int64          `json:"issue_id"`
	WorkspaceID sql.NullInt64  `json:"workspace_id"`
	Kind        string         `json:"kind"`
	Summary     string         `json:"summary"`
	DetailJson  sql.NullString `json:"detail_json"`
	CostUsd     float64        `json:"cost_usd"`
}

// Append one execution-timeline event for an issue (spec section 23.7).
func (q *Queries) InsertIssueExecEvent(ctx context.Context, arg InsertIssueExecEventParams) error {
	_, err := q.db.ExecContext(ctx, insertIssueExecEvent,
		arg.IssueID,
		arg.WorkspaceID,
		arg.Kind,
		arg.Summary,
		arg.DetailJson,
		arg.CostUsd,
	)
	return err
}

const listIssueExecEvents = `-- name: ListIssueExecEvents :many
SELECT id, issue_id, workspace_id, kind, summary, detail_json, cost_usd, created_at
FROM issue_exec_events
WHERE issue_id = ?
ORDER BY created_at ASC, id ASC
`

// Full execution timeline for an issue, oldest first. issue_id anchors the param.
func (q *Queries) ListIssueExecEvents(ctx context.Context, issueID int64) ([]IssueExecEvent, error) {
	rows, err := q.db.QueryContext(ctx, listIssueExecEvents, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssueExecEvent{}
	for rows.Next() {
		var i IssueExecEvent
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.WorkspaceID,
			&i.Kind,
			&i.Summary,
			&i.DetailJson,
			&i.CostUsd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumIssueExecCost = `-- name: SumIssueExecCost :one
SELECT CAST(COALESCE(SUM(cost_usd), 0) AS REAL) FROM issue_exec_events WHERE issue_id = ?
`

// Cumulative recorded cost for an issue (cost chip on the card). CAST keeps the
// result a concrete float on both SQLite (REAL affinity) and Postgres.
func (q *Queries) SumIssueExecCost(ctx context.Context, issueID int64) (float64, error) {
	row := q.db.QueryRowContext(ctx, sumIssueExecCost, issueID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}
