// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issue_assignees.sql

package store

import (
	"context"
	"strings"
)

const addIssueAssignee = `-- name: AddIssueAssignee :exec
INSERT OR IGNORE INTO issue_assignees (issue_id, user_id) VALUES (?, ?)
`

type AddIssueAssigneeParams struct {
	IssueID int64 `json:"issue_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) AddIssueAssignee(ctx context.Context, arg AddIssueAssigneeParams) error {
	_, err := q.db.ExecContext(ctx, addIssueAssignee, arg.IssueID, arg.UserID)
	return err
}

const clearIssueAssignees = `-- name: ClearIssueAssignees :exec
DELETE FROM issue_assignees WHERE issue_id = ?
`

func (q *Queries) ClearIssueAssignees(ctx context.Context, issueID int64) error {
	_, err := q.db.ExecContext(ctx, clearIssueAssignees, issueID)
	return err
}

const deleteIssueAssigneesForUserInOrg = `-- name: DeleteIssueAssigneesForUserInOrg :execrows
DELETE FROM issue_assignees
WHERE user_id = ?
  AND issue_id IN (
    SELECT i.id FROM issues i
    JOIN columns c  ON c.id = i.column_id
    JOIN projects p ON p.id = c.project_id
    WHERE p.owner_type = 'org' AND p.owner_id = ?
  )
`

type DeleteIssueAssigneesForUserInOrgParams struct {
	UserID  int64 `json:"user_id"`
	OwnerID int64 `json:"owner_id"`
}

func (q *Queries) DeleteIssueAssigneesForUserInOrg(ctx context.Context, arg DeleteIssueAssigneesForUserInOrgParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteIssueAssigneesForUserInOrg, arg.UserID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAffectedIssueIDsForUserInOrg = `-- name: ListAffectedIssueIDsForUserInOrg :many
SELECT i.id FROM issues i
JOIN issue_assignees ia ON ia.issue_id = i.id
JOIN columns c          ON c.id = i.column_id
JOIN projects p         ON p.id = c.project_id
WHERE ia.user_id = ?
  AND p.owner_type = 'org' AND p.owner_id = ?
ORDER BY i.id
`

type ListAffectedIssueIDsForUserInOrgParams struct {
	UserID  int64 `json:"user_id"`
	OwnerID int64 `json:"owner_id"`
}

// Used to populate audit before the cascade DELETE. No LIMIT - the audit
// payload should reflect the full set; the bottleneck is the DELETE, not the
// TEXT column. A user with thousands of assignments is rare and the cleanup
// gets logged exactly once on member removal.
func (q *Queries) ListAffectedIssueIDsForUserInOrg(ctx context.Context, arg ListAffectedIssueIDsForUserInOrgParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listAffectedIssueIDsForUserInOrg, arg.UserID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueAssignees = `-- name: ListIssueAssignees :many
SELECT u.id, u.username, u.display_name
FROM issue_assignees ia
JOIN users u ON u.id = ia.user_id
WHERE ia.issue_id = ?
ORDER BY u.display_name, u.username
`

type ListIssueAssigneesRow struct {
	ID          int64  `json:"id"`
	Username    string `json:"username"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) ListIssueAssignees(ctx context.Context, issueID int64) ([]ListIssueAssigneesRow, error) {
	rows, err := q.db.QueryContext(ctx, listIssueAssignees, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssueAssigneesRow{}
	for rows.Next() {
		var i ListIssueAssigneesRow
		if err := rows.Scan(&i.ID, &i.Username, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueAssigneesByIssueIDs = `-- name: ListIssueAssigneesByIssueIDs :many
SELECT ia.issue_id, u.id, u.username, u.display_name
FROM issue_assignees ia
JOIN users u ON u.id = ia.user_id
WHERE ia.issue_id IN (/*SLICE:issue_ids*/?)
ORDER BY ia.issue_id, u.display_name
`

type ListIssueAssigneesByIssueIDsRow struct {
	IssueID     int64  `json:"issue_id"`
	ID          int64  `json:"id"`
	Username    string `json:"username"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) ListIssueAssigneesByIssueIDs(ctx context.Context, issueIds []int64) ([]ListIssueAssigneesByIssueIDsRow, error) {
	query := listIssueAssigneesByIssueIDs
	var queryParams []interface{}
	if len(issueIds) > 0 {
		for _, v := range issueIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:issue_ids*/?", strings.Repeat(",?", len(issueIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:issue_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssueAssigneesByIssueIDsRow{}
	for rows.Next() {
		var i ListIssueAssigneesByIssueIDsRow
		if err := rows.Scan(
			&i.IssueID,
			&i.ID,
			&i.Username,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
