// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issue_comments.sql

package store

import (
	"context"
)

const createIssueComment = `-- name: CreateIssueComment :one
INSERT INTO issue_comments (issue_id, author, content) VALUES (?, ?, ?) RETURNING id, issue_id, author, content, created_at, updated_at
`

type CreateIssueCommentParams struct {
	IssueID int64  `json:"issue_id"`
	Author  string `json:"author"`
	Content string `json:"content"`
}

func (q *Queries) CreateIssueComment(ctx context.Context, arg CreateIssueCommentParams) (IssueComment, error) {
	row := q.db.QueryRowContext(ctx, createIssueComment, arg.IssueID, arg.Author, arg.Content)
	var i IssueComment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Author,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIssueComment = `-- name: DeleteIssueComment :exec
DELETE FROM issue_comments WHERE id = ?
`

func (q *Queries) DeleteIssueComment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteIssueComment, id)
	return err
}

const getIssueComment = `-- name: GetIssueComment :one
SELECT id, issue_id, author, content, created_at, updated_at FROM issue_comments WHERE id = ?
`

func (q *Queries) GetIssueComment(ctx context.Context, id int64) (IssueComment, error) {
	row := q.db.QueryRowContext(ctx, getIssueComment, id)
	var i IssueComment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Author,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIssueComments = `-- name: ListIssueComments :many
SELECT id, issue_id, author, content, created_at, updated_at FROM issue_comments WHERE issue_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListIssueComments(ctx context.Context, issueID int64) ([]IssueComment, error) {
	rows, err := q.db.QueryContext(ctx, listIssueComments, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssueComment{}
	for rows.Next() {
		var i IssueComment
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Author,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIssueComment = `-- name: UpdateIssueComment :one
UPDATE issue_comments SET content = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, issue_id, author, content, created_at, updated_at
`

type UpdateIssueCommentParams struct {
	Content string `json:"content"`
	ID      int64  `json:"id"`
}

func (q *Queries) UpdateIssueComment(ctx context.Context, arg UpdateIssueCommentParams) (IssueComment, error) {
	row := q.db.QueryRowContext(ctx, updateIssueComment, arg.Content, arg.ID)
	var i IssueComment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Author,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
