// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issue_activities.sql

package store

import (
	"context"
	"database/sql"
)

const createActivity = `-- name: CreateActivity :exec
INSERT INTO issue_activities (issue_id, action, field, old_value, new_value, author) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateActivityParams struct {
	IssueID  int64          `json:"issue_id"`
	Action   string         `json:"action"`
	Field    sql.NullString `json:"field"`
	OldValue sql.NullString `json:"old_value"`
	NewValue sql.NullString `json:"new_value"`
	Author   sql.NullString `json:"author"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) error {
	_, err := q.db.ExecContext(ctx, createActivity,
		arg.IssueID,
		arg.Action,
		arg.Field,
		arg.OldValue,
		arg.NewValue,
		arg.Author,
	)
	return err
}

const listActivitiesByIssue = `-- name: ListActivitiesByIssue :many
SELECT id, issue_id, "action", field, old_value, new_value, author, created_at FROM issue_activities WHERE issue_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListActivitiesByIssue(ctx context.Context, issueID int64) ([]IssueActivity, error) {
	rows, err := q.db.QueryContext(ctx, listActivitiesByIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssueActivity{}
	for rows.Next() {
		var i IssueActivity
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Action,
			&i.Field,
			&i.OldValue,
			&i.NewValue,
			&i.Author,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
