// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issue_labels.sql

package store

import (
	"context"
)

const addIssueLabel = `-- name: AddIssueLabel :exec
INSERT OR IGNORE INTO issue_labels (issue_id, label_id) VALUES (?, ?)
`

type AddIssueLabelParams struct {
	IssueID int64 `json:"issue_id"`
	LabelID int64 `json:"label_id"`
}

func (q *Queries) AddIssueLabel(ctx context.Context, arg AddIssueLabelParams) error {
	_, err := q.db.ExecContext(ctx, addIssueLabel, arg.IssueID, arg.LabelID)
	return err
}

const clearIssueLabels = `-- name: ClearIssueLabels :exec
DELETE FROM issue_labels WHERE issue_id = ?
`

func (q *Queries) ClearIssueLabels(ctx context.Context, issueID int64) error {
	_, err := q.db.ExecContext(ctx, clearIssueLabels, issueID)
	return err
}

const listIssueLabelIDs = `-- name: ListIssueLabelIDs :many
SELECT label_id FROM issue_labels WHERE issue_id = ?
`

func (q *Queries) ListIssueLabelIDs(ctx context.Context, issueID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listIssueLabelIDs, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var label_id int64
		if err := rows.Scan(&label_id); err != nil {
			return nil, err
		}
		items = append(items, label_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeIssueLabel = `-- name: RemoveIssueLabel :exec
DELETE FROM issue_labels WHERE issue_id = ? AND label_id = ?
`

type RemoveIssueLabelParams struct {
	IssueID int64 `json:"issue_id"`
	LabelID int64 `json:"label_id"`
}

func (q *Queries) RemoveIssueLabel(ctx context.Context, arg RemoveIssueLabelParams) error {
	_, err := q.db.ExecContext(ctx, removeIssueLabel, arg.IssueID, arg.LabelID)
	return err
}
