// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issue_checklists.sql

package store

import (
	"context"
)

const createChecklist = `-- name: CreateChecklist :one
INSERT INTO issue_checklists (issue_id, title, position)
VALUES (?, ?, COALESCE((SELECT MAX(ic.position) FROM issue_checklists ic WHERE ic.issue_id = ?), -1) + 1)
RETURNING id, issue_id, title, is_completed, position, created_at, updated_at
`

type CreateChecklistParams struct {
	IssueID   int64  `json:"issue_id"`
	Title     string `json:"title"`
	IssueID_2 int64  `json:"issue_id_2"`
}

func (q *Queries) CreateChecklist(ctx context.Context, arg CreateChecklistParams) (IssueChecklist, error) {
	row := q.db.QueryRowContext(ctx, createChecklist, arg.IssueID, arg.Title, arg.IssueID_2)
	var i IssueChecklist
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Title,
		&i.IsCompleted,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChecklist = `-- name: DeleteChecklist :exec
DELETE FROM issue_checklists WHERE id = ?
`

func (q *Queries) DeleteChecklist(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteChecklist, id)
	return err
}

const getChecklist = `-- name: GetChecklist :one
SELECT id, issue_id, title, is_completed, position, created_at, updated_at FROM issue_checklists WHERE id = ?
`

func (q *Queries) GetChecklist(ctx context.Context, id int64) (IssueChecklist, error) {
	row := q.db.QueryRowContext(ctx, getChecklist, id)
	var i IssueChecklist
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Title,
		&i.IsCompleted,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChecklistStats = `-- name: GetChecklistStats :one
SELECT
    COUNT(*) as total,
    CAST(COALESCE(SUM(CASE WHEN is_completed = 1 THEN 1 ELSE 0 END), 0) AS INTEGER) as completed
FROM issue_checklists WHERE issue_id = ?
`

type GetChecklistStatsRow struct {
	Total     int64 `json:"total"`
	Completed int64 `json:"completed"`
}

func (q *Queries) GetChecklistStats(ctx context.Context, issueID int64) (GetChecklistStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getChecklistStats, issueID)
	var i GetChecklistStatsRow
	err := row.Scan(&i.Total, &i.Completed)
	return i, err
}

const listChecklistsByIssue = `-- name: ListChecklistsByIssue :many
SELECT id, issue_id, title, is_completed, position, created_at, updated_at FROM issue_checklists WHERE issue_id = ? ORDER BY position
`

func (q *Queries) ListChecklistsByIssue(ctx context.Context, issueID int64) ([]IssueChecklist, error) {
	rows, err := q.db.QueryContext(ctx, listChecklistsByIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssueChecklist{}
	for rows.Next() {
		var i IssueChecklist
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Title,
			&i.IsCompleted,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChecklist = `-- name: UpdateChecklist :one
UPDATE issue_checklists SET title = ?, is_completed = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, issue_id, title, is_completed, position, created_at, updated_at
`

type UpdateChecklistParams struct {
	Title       string `json:"title"`
	IsCompleted int64  `json:"is_completed"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateChecklist(ctx context.Context, arg UpdateChecklistParams) (IssueChecklist, error) {
	row := q.db.QueryRowContext(ctx, updateChecklist, arg.Title, arg.IsCompleted, arg.ID)
	var i IssueChecklist
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Title,
		&i.IsCompleted,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChecklistPosition = `-- name: UpdateChecklistPosition :exec
UPDATE issue_checklists SET position = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateChecklistPositionParams struct {
	Position int64 `json:"position"`
	ID       int64 `json:"id"`
}

func (q *Queries) UpdateChecklistPosition(ctx context.Context, arg UpdateChecklistPositionParams) error {
	_, err := q.db.ExecContext(ctx, updateChecklistPosition, arg.Position, arg.ID)
	return err
}
