// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: knowledge_bases.sql

package store

import (
	"context"
)

const createKBBinding = `-- name: CreateKBBinding :exec
INSERT INTO kb_bindings (kb_id, target_type, target_id)
VALUES (?, ?, ?)
ON CONFLICT(kb_id, target_type, target_id) DO NOTHING
`

type CreateKBBindingParams struct {
	KbID       int64  `json:"kb_id"`
	TargetType string `json:"target_type"`
	TargetID   int64  `json:"target_id"`
}

func (q *Queries) CreateKBBinding(ctx context.Context, arg CreateKBBindingParams) error {
	_, err := q.db.ExecContext(ctx, createKBBinding, arg.KbID, arg.TargetType, arg.TargetID)
	return err
}

const createKnowledgeBase = `-- name: CreateKnowledgeBase :one
INSERT INTO knowledge_bases (owner_type, owner_id, name, description, source_kind, source_addr, source_config)
VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id, owner_type, owner_id, name, description, source_kind, source_addr, source_config, status, created_at, updated_at
`

type CreateKnowledgeBaseParams struct {
	OwnerType    string `json:"owner_type"`
	OwnerID      int64  `json:"owner_id"`
	Name         string `json:"name"`
	Description  string `json:"description"`
	SourceKind   string `json:"source_kind"`
	SourceAddr   string `json:"source_addr"`
	SourceConfig string `json:"source_config"`
}

func (q *Queries) CreateKnowledgeBase(ctx context.Context, arg CreateKnowledgeBaseParams) (KnowledgeBase, error) {
	row := q.db.QueryRowContext(ctx, createKnowledgeBase,
		arg.OwnerType,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.SourceKind,
		arg.SourceAddr,
		arg.SourceConfig,
	)
	var i KnowledgeBase
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.SourceKind,
		&i.SourceAddr,
		&i.SourceConfig,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteKBBinding = `-- name: DeleteKBBinding :exec
DELETE FROM kb_bindings WHERE kb_id = ? AND target_type = ? AND target_id = ?
`

type DeleteKBBindingParams struct {
	KbID       int64  `json:"kb_id"`
	TargetType string `json:"target_type"`
	TargetID   int64  `json:"target_id"`
}

func (q *Queries) DeleteKBBinding(ctx context.Context, arg DeleteKBBindingParams) error {
	_, err := q.db.ExecContext(ctx, deleteKBBinding, arg.KbID, arg.TargetType, arg.TargetID)
	return err
}

const deleteKBDocumentsForKB = `-- name: DeleteKBDocumentsForKB :exec
DELETE FROM kb_documents WHERE kb_id = ?
`

func (q *Queries) DeleteKBDocumentsForKB(ctx context.Context, kbID int64) error {
	_, err := q.db.ExecContext(ctx, deleteKBDocumentsForKB, kbID)
	return err
}

const deleteKnowledgeBase = `-- name: DeleteKnowledgeBase :exec
DELETE FROM knowledge_bases WHERE id = ?
`

func (q *Queries) DeleteKnowledgeBase(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteKnowledgeBase, id)
	return err
}

const getKBDocumentByPath = `-- name: GetKBDocumentByPath :one
SELECT id, kb_id, rel_path, uri, content_hash, chunk_count, byte_size, created_at, updated_at FROM kb_documents WHERE kb_id = ? AND rel_path = ?
`

type GetKBDocumentByPathParams struct {
	KbID    int64  `json:"kb_id"`
	RelPath string `json:"rel_path"`
}

func (q *Queries) GetKBDocumentByPath(ctx context.Context, arg GetKBDocumentByPathParams) (KbDocument, error) {
	row := q.db.QueryRowContext(ctx, getKBDocumentByPath, arg.KbID, arg.RelPath)
	var i KbDocument
	err := row.Scan(
		&i.ID,
		&i.KbID,
		&i.RelPath,
		&i.Uri,
		&i.ContentHash,
		&i.ChunkCount,
		&i.ByteSize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKnowledgeBase = `-- name: GetKnowledgeBase :one
SELECT id, owner_type, owner_id, name, description, source_kind, source_addr, source_config, status, created_at, updated_at FROM knowledge_bases WHERE id = ?
`

func (q *Queries) GetKnowledgeBase(ctx context.Context, id int64) (KnowledgeBase, error) {
	row := q.db.QueryRowContext(ctx, getKnowledgeBase, id)
	var i KnowledgeBase
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.SourceKind,
		&i.SourceAddr,
		&i.SourceConfig,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKnowledgeBaseByOwnerAndName = `-- name: GetKnowledgeBaseByOwnerAndName :one
SELECT id, owner_type, owner_id, name, description, source_kind, source_addr, source_config, status, created_at, updated_at FROM knowledge_bases WHERE owner_type = ? AND owner_id = ? AND name = ?
`

type GetKnowledgeBaseByOwnerAndNameParams struct {
	OwnerType string `json:"owner_type"`
	OwnerID   int64  `json:"owner_id"`
	Name      string `json:"name"`
}

// KB names are unique per owner (UNIQUE(owner_type, owner_id, name)). Scope the
// lookup by owner so one owner's KB never blocks another from reusing the name.
func (q *Queries) GetKnowledgeBaseByOwnerAndName(ctx context.Context, arg GetKnowledgeBaseByOwnerAndNameParams) (KnowledgeBase, error) {
	row := q.db.QueryRowContext(ctx, getKnowledgeBaseByOwnerAndName, arg.OwnerType, arg.OwnerID, arg.Name)
	var i KnowledgeBase
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.SourceKind,
		&i.SourceAddr,
		&i.SourceConfig,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listKBBindingsForKB = `-- name: ListKBBindingsForKB :many
SELECT id, kb_id, target_type, target_id, created_at FROM kb_bindings WHERE kb_id = ? ORDER BY id ASC
`

func (q *Queries) ListKBBindingsForKB(ctx context.Context, kbID int64) ([]KbBinding, error) {
	rows, err := q.db.QueryContext(ctx, listKBBindingsForKB, kbID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KbBinding{}
	for rows.Next() {
		var i KbBinding
		if err := rows.Scan(
			&i.ID,
			&i.KbID,
			&i.TargetType,
			&i.TargetID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKBBindingsForTarget = `-- name: ListKBBindingsForTarget :many
SELECT id, kb_id, target_type, target_id, created_at FROM kb_bindings WHERE target_type = ? AND target_id = ? ORDER BY id ASC
`

type ListKBBindingsForTargetParams struct {
	TargetType string `json:"target_type"`
	TargetID   int64  `json:"target_id"`
}

func (q *Queries) ListKBBindingsForTarget(ctx context.Context, arg ListKBBindingsForTargetParams) ([]KbBinding, error) {
	rows, err := q.db.QueryContext(ctx, listKBBindingsForTarget, arg.TargetType, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KbBinding{}
	for rows.Next() {
		var i KbBinding
		if err := rows.Scan(
			&i.ID,
			&i.KbID,
			&i.TargetType,
			&i.TargetID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKBDocuments = `-- name: ListKBDocuments :many
SELECT id, kb_id, rel_path, uri, content_hash, chunk_count, byte_size, created_at, updated_at FROM kb_documents WHERE kb_id = ? ORDER BY rel_path ASC
`

func (q *Queries) ListKBDocuments(ctx context.Context, kbID int64) ([]KbDocument, error) {
	rows, err := q.db.QueryContext(ctx, listKBDocuments, kbID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KbDocument{}
	for rows.Next() {
		var i KbDocument
		if err := rows.Scan(
			&i.ID,
			&i.KbID,
			&i.RelPath,
			&i.Uri,
			&i.ContentHash,
			&i.ChunkCount,
			&i.ByteSize,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnowledgeBasesForOwner = `-- name: ListKnowledgeBasesForOwner :many
SELECT id, owner_type, owner_id, name, description, source_kind, source_addr, source_config, status, created_at, updated_at FROM knowledge_bases WHERE owner_type = ? AND owner_id = ? ORDER BY created_at DESC
`

type ListKnowledgeBasesForOwnerParams struct {
	OwnerType string `json:"owner_type"`
	OwnerID   int64  `json:"owner_id"`
}

func (q *Queries) ListKnowledgeBasesForOwner(ctx context.Context, arg ListKnowledgeBasesForOwnerParams) ([]KnowledgeBase, error) {
	rows, err := q.db.QueryContext(ctx, listKnowledgeBasesForOwner, arg.OwnerType, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KnowledgeBase{}
	for rows.Next() {
		var i KnowledgeBase
		if err := rows.Scan(
			&i.ID,
			&i.OwnerType,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.SourceKind,
			&i.SourceAddr,
			&i.SourceConfig,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnowledgeBasesForProject = `-- name: ListKnowledgeBasesForProject :many
SELECT kb.id, kb.owner_type, kb.owner_id, kb.name, kb.description, kb.source_kind, kb.source_addr, kb.source_config, kb.status, kb.created_at, kb.updated_at FROM knowledge_bases kb
JOIN kb_bindings b ON b.kb_id = kb.id
WHERE b.target_type = 'project'
  AND b.target_id = ?
  AND kb.owner_type = ?
  AND kb.owner_id = ?
  AND kb.status <> 'disabled'
ORDER BY kb.created_at DESC
`

type ListKnowledgeBasesForProjectParams struct {
	TargetID  int64  `json:"target_id"`
	OwnerType string `json:"owner_type"`
	OwnerID   int64  `json:"owner_id"`
}

// KBs visible to a workspace: owned by the given owner AND bound (kb_bindings)
// to the project. A KB with no project binding is intentionally NOT returned
// (unbound is invisible). owner_type/owner_id enforce tenant isolation on top of
// the binding so a stray cross-owner binding can never leak a KB. A disabled KB
// (status = 'disabled', set by the management UI start/stop toggle) is excluded
// so disabling actually stops both kb_search and the agent direct-read mount.
func (q *Queries) ListKnowledgeBasesForProject(ctx context.Context, arg ListKnowledgeBasesForProjectParams) ([]KnowledgeBase, error) {
	rows, err := q.db.QueryContext(ctx, listKnowledgeBasesForProject, arg.TargetID, arg.OwnerType, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KnowledgeBase{}
	for rows.Next() {
		var i KnowledgeBase
		if err := rows.Scan(
			&i.ID,
			&i.OwnerType,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.SourceKind,
			&i.SourceAddr,
			&i.SourceConfig,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKnowledgeBase = `-- name: UpdateKnowledgeBase :one
UPDATE knowledge_bases
SET name = ?, description = ?, source_kind = ?, source_addr = ?, source_config = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? RETURNING id, owner_type, owner_id, name, description, source_kind, source_addr, source_config, status, created_at, updated_at
`

type UpdateKnowledgeBaseParams struct {
	Name         string `json:"name"`
	Description  string `json:"description"`
	SourceKind   string `json:"source_kind"`
	SourceAddr   string `json:"source_addr"`
	SourceConfig string `json:"source_config"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateKnowledgeBase(ctx context.Context, arg UpdateKnowledgeBaseParams) (KnowledgeBase, error) {
	row := q.db.QueryRowContext(ctx, updateKnowledgeBase,
		arg.Name,
		arg.Description,
		arg.SourceKind,
		arg.SourceAddr,
		arg.SourceConfig,
		arg.ID,
	)
	var i KnowledgeBase
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.SourceKind,
		&i.SourceAddr,
		&i.SourceConfig,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertKBDocument = `-- name: UpsertKBDocument :one
INSERT INTO kb_documents (kb_id, rel_path, uri, content_hash, chunk_count, byte_size)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(kb_id, rel_path) DO UPDATE SET
    uri = excluded.uri,
    content_hash = excluded.content_hash,
    chunk_count = excluded.chunk_count,
    byte_size = excluded.byte_size,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, kb_id, rel_path, uri, content_hash, chunk_count, byte_size, created_at, updated_at
`

type UpsertKBDocumentParams struct {
	KbID        int64  `json:"kb_id"`
	RelPath     string `json:"rel_path"`
	Uri         string `json:"uri"`
	ContentHash string `json:"content_hash"`
	ChunkCount  int64  `json:"chunk_count"`
	ByteSize    int64  `json:"byte_size"`
}

// Idempotent per (kb_id, rel_path): re-ingesting a changed file updates the hash
// and chunk bookkeeping in place rather than creating a duplicate row.
func (q *Queries) UpsertKBDocument(ctx context.Context, arg UpsertKBDocumentParams) (KbDocument, error) {
	row := q.db.QueryRowContext(ctx, upsertKBDocument,
		arg.KbID,
		arg.RelPath,
		arg.Uri,
		arg.ContentHash,
		arg.ChunkCount,
		arg.ByteSize,
	)
	var i KbDocument
	err := row.Scan(
		&i.ID,
		&i.KbID,
		&i.RelPath,
		&i.Uri,
		&i.ContentHash,
		&i.ChunkCount,
		&i.ByteSize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
