// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: labels.sql

package store

import (
	"context"
	"strings"
	"time"
)

const createLabel = `-- name: CreateLabel :one
INSERT INTO labels (project_id, name, color, description, created_by)
VALUES (?, ?, ?, ?, ?)
RETURNING id, project_id, name, color, description, created_at, created_by
`

type CreateLabelParams struct {
	ProjectID   int64  `json:"project_id"`
	Name        string `json:"name"`
	Color       string `json:"color"`
	Description string `json:"description"`
	CreatedBy   int64  `json:"created_by"`
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, createLabel,
		arg.ProjectID,
		arg.Name,
		arg.Color,
		arg.Description,
		arg.CreatedBy,
	)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteLabel = `-- name: DeleteLabel :exec
DELETE FROM labels WHERE id = ?
`

func (q *Queries) DeleteLabel(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLabel, id)
	return err
}

const getLabel = `-- name: GetLabel :one
SELECT id, project_id, name, color, description, created_at, created_by FROM labels WHERE id = ?
`

func (q *Queries) GetLabel(ctx context.Context, id int64) (Label, error) {
	row := q.db.QueryRowContext(ctx, getLabel, id)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getLabelByProjectAndName = `-- name: GetLabelByProjectAndName :one
SELECT id, project_id, name, color, description, created_at, created_by FROM labels WHERE project_id = ? AND name = ?
`

type GetLabelByProjectAndNameParams struct {
	ProjectID int64  `json:"project_id"`
	Name      string `json:"name"`
}

func (q *Queries) GetLabelByProjectAndName(ctx context.Context, arg GetLabelByProjectAndNameParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, getLabelByProjectAndName, arg.ProjectID, arg.Name)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listLabelsByIssue = `-- name: ListLabelsByIssue :many
SELECT l.id, l.project_id, l.name, l.color, l.description, l.created_at, l.created_by FROM labels l
JOIN issue_labels il ON il.label_id = l.id
WHERE il.issue_id = ?
ORDER BY l.name
`

func (q *Queries) ListLabelsByIssue(ctx context.Context, issueID int64) ([]Label, error) {
	rows, err := q.db.QueryContext(ctx, listLabelsByIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Label{}
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Color,
			&i.Description,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabelsByIssueIDs = `-- name: ListLabelsByIssueIDs :many
SELECT il.issue_id, l.id, l.project_id, l.name, l.color, l.description, l.created_at, l.created_by FROM labels l
JOIN issue_labels il ON il.label_id = l.id
WHERE il.issue_id IN (/*SLICE:issue_ids*/?)
ORDER BY il.issue_id, l.name
`

type ListLabelsByIssueIDsRow struct {
	IssueID     int64     `json:"issue_id"`
	ID          int64     `json:"id"`
	ProjectID   int64     `json:"project_id"`
	Name        string    `json:"name"`
	Color       string    `json:"color"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedBy   int64     `json:"created_by"`
}

func (q *Queries) ListLabelsByIssueIDs(ctx context.Context, issueIds []int64) ([]ListLabelsByIssueIDsRow, error) {
	query := listLabelsByIssueIDs
	var queryParams []interface{}
	if len(issueIds) > 0 {
		for _, v := range issueIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:issue_ids*/?", strings.Repeat(",?", len(issueIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:issue_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLabelsByIssueIDsRow{}
	for rows.Next() {
		var i ListLabelsByIssueIDsRow
		if err := rows.Scan(
			&i.IssueID,
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Color,
			&i.Description,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabelsByProject = `-- name: ListLabelsByProject :many
SELECT id, project_id, name, color, description, created_at, created_by FROM labels WHERE project_id = ? ORDER BY name
`

func (q *Queries) ListLabelsByProject(ctx context.Context, projectID int64) ([]Label, error) {
	rows, err := q.db.QueryContext(ctx, listLabelsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Label{}
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Color,
			&i.Description,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabelsByProjectWithUsage = `-- name: ListLabelsByProjectWithUsage :many
SELECT
    l.id, l.project_id, l.name, l.color, l.description, l.created_at, l.created_by,
    (SELECT COUNT(*) FROM issue_labels il WHERE il.label_id = l.id) AS usage_count
FROM labels l
WHERE l.project_id = ?
ORDER BY l.name
`

type ListLabelsByProjectWithUsageRow struct {
	ID          int64     `json:"id"`
	ProjectID   int64     `json:"project_id"`
	Name        string    `json:"name"`
	Color       string    `json:"color"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedBy   int64     `json:"created_by"`
	UsageCount  int64     `json:"usage_count"`
}

func (q *Queries) ListLabelsByProjectWithUsage(ctx context.Context, projectID int64) ([]ListLabelsByProjectWithUsageRow, error) {
	rows, err := q.db.QueryContext(ctx, listLabelsByProjectWithUsage, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLabelsByProjectWithUsageRow{}
	for rows.Next() {
		var i ListLabelsByProjectWithUsageRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Color,
			&i.Description,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UsageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLabel = `-- name: UpdateLabel :one
UPDATE labels SET name = ?, color = ?, description = ?
WHERE id = ?
RETURNING id, project_id, name, color, description, created_at, created_by
`

type UpdateLabelParams struct {
	Name        string `json:"name"`
	Color       string `json:"color"`
	Description string `json:"description"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateLabel(ctx context.Context, arg UpdateLabelParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, updateLabel,
		arg.Name,
		arg.Color,
		arg.Description,
		arg.ID,
	)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}
