// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mcp_session_tokens.sql

package store

import (
	"context"
	"time"
)

const createMCPSessionToken = `-- name: CreateMCPSessionToken :exec
INSERT INTO mcp_session_tokens (workspace_id, token_hash, expires_at)
VALUES (?, ?, ?)
`

type CreateMCPSessionTokenParams struct {
	WorkspaceID int64     `json:"workspace_id"`
	TokenHash   string    `json:"token_hash"`
	ExpiresAt   time.Time `json:"expires_at"`
}

func (q *Queries) CreateMCPSessionToken(ctx context.Context, arg CreateMCPSessionTokenParams) error {
	_, err := q.db.ExecContext(ctx, createMCPSessionToken, arg.WorkspaceID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const deleteExpiredMCPSessions = `-- name: DeleteExpiredMCPSessions :exec
DELETE FROM mcp_session_tokens WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredMCPSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredMCPSessions)
	return err
}

const deleteMCPSessionsForWorkspace = `-- name: DeleteMCPSessionsForWorkspace :exec
DELETE FROM mcp_session_tokens WHERE workspace_id = ?
`

func (q *Queries) DeleteMCPSessionsForWorkspace(ctx context.Context, workspaceID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMCPSessionsForWorkspace, workspaceID)
	return err
}

const getMCPSessionByHash = `-- name: GetMCPSessionByHash :one
SELECT id, workspace_id, token_hash, created_at, expires_at FROM mcp_session_tokens WHERE token_hash = ?
`

func (q *Queries) GetMCPSessionByHash(ctx context.Context, tokenHash string) (McpSessionToken, error) {
	row := q.db.QueryRowContext(ctx, getMCPSessionByHash, tokenHash)
	var i McpSessionToken
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const renewMCPSessionToken = `-- name: RenewMCPSessionToken :exec
UPDATE mcp_session_tokens SET expires_at = ? WHERE token_hash = ?
`

type RenewMCPSessionTokenParams struct {
	ExpiresAt time.Time `json:"expires_at"`
	TokenHash string    `json:"token_hash"`
}

func (q *Queries) RenewMCPSessionToken(ctx context.Context, arg RenewMCPSessionTokenParams) error {
	_, err := q.db.ExecContext(ctx, renewMCPSessionToken, arg.ExpiresAt, arg.TokenHash)
	return err
}

const renewMCPSessionsForWorkspace = `-- name: RenewMCPSessionsForWorkspace :exec
UPDATE mcp_session_tokens SET expires_at = ? WHERE workspace_id = ?
`

type RenewMCPSessionsForWorkspaceParams struct {
	ExpiresAt   time.Time `json:"expires_at"`
	WorkspaceID int64     `json:"workspace_id"`
}

func (q *Queries) RenewMCPSessionsForWorkspace(ctx context.Context, arg RenewMCPSessionsForWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, renewMCPSessionsForWorkspace, arg.ExpiresAt, arg.WorkspaceID)
	return err
}
