// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memories.sql

package store

import (
	"context"
	"database/sql"
)

const countMemoriesForOwner = `-- name: CountMemoriesForOwner :one
SELECT COUNT(*) AS count FROM memories
WHERE owner_type = ? AND owner_id = ? AND deleted_at IS NULL
`

type CountMemoriesForOwnerParams struct {
	OwnerType string `json:"owner_type"`
	OwnerID   int64  `json:"owner_id"`
}

func (q *Queries) CountMemoriesForOwner(ctx context.Context, arg CountMemoriesForOwnerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMemoriesForOwner, arg.OwnerType, arg.OwnerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMemory = `-- name: CreateMemory :one
INSERT INTO memories (owner_type, owner_id, project_id, workspace_id, mem_type, title, content, source, source_path, version)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 1)
RETURNING id, owner_type, owner_id, project_id, workspace_id, mem_type, title, content, source, source_path, version, reinforce_count, last_reinforced_at, superseded_by, pending_review, stale_reason, deleted_at, created_at, updated_at
`

type CreateMemoryParams struct {
	OwnerType   string        `json:"owner_type"`
	OwnerID     int64         `json:"owner_id"`
	ProjectID   sql.NullInt64 `json:"project_id"`
	WorkspaceID sql.NullInt64 `json:"workspace_id"`
	MemType     string        `json:"mem_type"`
	Title       string        `json:"title"`
	Content     string        `json:"content"`
	Source      string        `json:"source"`
	SourcePath  string        `json:"source_path"`
}

func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error) {
	row := q.db.QueryRowContext(ctx, createMemory,
		arg.OwnerType,
		arg.OwnerID,
		arg.ProjectID,
		arg.WorkspaceID,
		arg.MemType,
		arg.Title,
		arg.Content,
		arg.Source,
		arg.SourcePath,
	)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.MemType,
		&i.Title,
		&i.Content,
		&i.Source,
		&i.SourcePath,
		&i.Version,
		&i.ReinforceCount,
		&i.LastReinforcedAt,
		&i.SupersededBy,
		&i.PendingReview,
		&i.StaleReason,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMemorySweepRun = `-- name: CreateMemorySweepRun :one
INSERT INTO memory_sweep_runs (project_id, trigger, scanned, auto_deleted, queued, detail)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, project_id, "trigger", scanned, auto_deleted, queued, detail, created_at
`

type CreateMemorySweepRunParams struct {
	ProjectID   int64  `json:"project_id"`
	Trigger     string `json:"trigger"`
	Scanned     int64  `json:"scanned"`
	AutoDeleted int64  `json:"auto_deleted"`
	Queued      int64  `json:"queued"`
	Detail      string `json:"detail"`
}

// Record one automatic staleness-sweep execution for a project (user-visible log).
func (q *Queries) CreateMemorySweepRun(ctx context.Context, arg CreateMemorySweepRunParams) (MemorySweepRun, error) {
	row := q.db.QueryRowContext(ctx, createMemorySweepRun,
		arg.ProjectID,
		arg.Trigger,
		arg.Scanned,
		arg.AutoDeleted,
		arg.Queued,
		arg.Detail,
	)
	var i MemorySweepRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Trigger,
		&i.Scanned,
		&i.AutoDeleted,
		&i.Queued,
		&i.Detail,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMemorySweepRunsForProject = `-- name: DeleteMemorySweepRunsForProject :exec
DELETE FROM memory_sweep_runs WHERE project_id = ?
`

// Clear a project's automatic-maintenance run log.
func (q *Queries) DeleteMemorySweepRunsForProject(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMemorySweepRunsForProject, projectID)
	return err
}

const flagStaleMemory = `-- name: FlagStaleMemory :exec
UPDATE memories
SET deleted_at = CURRENT_TIMESTAMP, stale_reason = ?, pending_review = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
`

type FlagStaleMemoryParams struct {
	StaleReason   string `json:"stale_reason"`
	PendingReview int64  `json:"pending_review"`
	ID            int64  `json:"id"`
}

// Soft-delete a memory judged stale, recording the reason and whether the
// removal awaits human review (pending_review=1) or was auto-applied (=0). The
// deleted_at IS NULL guard makes it idempotent and prevents an in-flight sweep
// from re-deleting a memory a human just restored.
func (q *Queries) FlagStaleMemory(ctx context.Context, arg FlagStaleMemoryParams) error {
	_, err := q.db.ExecContext(ctx, flagStaleMemory, arg.StaleReason, arg.PendingReview, arg.ID)
	return err
}

const getMemory = `-- name: GetMemory :one
SELECT id, owner_type, owner_id, project_id, workspace_id, mem_type, title, content, source, source_path, version, reinforce_count, last_reinforced_at, superseded_by, pending_review, stale_reason, deleted_at, created_at, updated_at FROM memories WHERE id = ?
`

func (q *Queries) GetMemory(ctx context.Context, id int64) (Memory, error) {
	row := q.db.QueryRowContext(ctx, getMemory, id)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.MemType,
		&i.Title,
		&i.Content,
		&i.Source,
		&i.SourcePath,
		&i.Version,
		&i.ReinforceCount,
		&i.LastReinforcedAt,
		&i.SupersededBy,
		&i.PendingReview,
		&i.StaleReason,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemoryVersion = `-- name: GetMemoryVersion :one
SELECT id, memory_id, version, mem_type, title, content, source, source_path, created_at FROM memory_versions WHERE memory_id = ? AND version = ?
`

type GetMemoryVersionParams struct {
	MemoryID int64 `json:"memory_id"`
	Version  int64 `json:"version"`
}

func (q *Queries) GetMemoryVersion(ctx context.Context, arg GetMemoryVersionParams) (MemoryVersion, error) {
	row := q.db.QueryRowContext(ctx, getMemoryVersion, arg.MemoryID, arg.Version)
	var i MemoryVersion
	err := row.Scan(
		&i.ID,
		&i.MemoryID,
		&i.Version,
		&i.MemType,
		&i.Title,
		&i.Content,
		&i.Source,
		&i.SourcePath,
		&i.CreatedAt,
	)
	return i, err
}

const hardDeleteMemory = `-- name: HardDeleteMemory :exec
DELETE FROM memories WHERE id = ?
`

func (q *Queries) HardDeleteMemory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, hardDeleteMemory, id)
	return err
}

const insertMemoryVersion = `-- name: InsertMemoryVersion :one
INSERT INTO memory_versions (memory_id, version, mem_type, title, content, source, source_path)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, memory_id, version, mem_type, title, content, source, source_path, created_at
`

type InsertMemoryVersionParams struct {
	MemoryID   int64  `json:"memory_id"`
	Version    int64  `json:"version"`
	MemType    string `json:"mem_type"`
	Title      string `json:"title"`
	Content    string `json:"content"`
	Source     string `json:"source"`
	SourcePath string `json:"source_path"`
}

func (q *Queries) InsertMemoryVersion(ctx context.Context, arg InsertMemoryVersionParams) (MemoryVersion, error) {
	row := q.db.QueryRowContext(ctx, insertMemoryVersion,
		arg.MemoryID,
		arg.Version,
		arg.MemType,
		arg.Title,
		arg.Content,
		arg.Source,
		arg.SourcePath,
	)
	var i MemoryVersion
	err := row.Scan(
		&i.ID,
		&i.MemoryID,
		&i.Version,
		&i.MemType,
		&i.Title,
		&i.Content,
		&i.Source,
		&i.SourcePath,
		&i.CreatedAt,
	)
	return i, err
}

const listDeletedMemoriesForOwner = `-- name: ListDeletedMemoriesForOwner :many
SELECT id, owner_type, owner_id, project_id, workspace_id, mem_type, title, content, source, source_path, version, reinforce_count, last_reinforced_at, superseded_by, pending_review, stale_reason, deleted_at, created_at, updated_at FROM memories
WHERE owner_type = ? AND owner_id = ? AND deleted_at IS NOT NULL
ORDER BY updated_at DESC
`

type ListDeletedMemoriesForOwnerParams struct {
	OwnerType string `json:"owner_type"`
	OwnerID   int64  `json:"owner_id"`
}

func (q *Queries) ListDeletedMemoriesForOwner(ctx context.Context, arg ListDeletedMemoriesForOwnerParams) ([]Memory, error) {
	rows, err := q.db.QueryContext(ctx, listDeletedMemoriesForOwner, arg.OwnerType, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memory{}
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.OwnerType,
			&i.OwnerID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.MemType,
			&i.Title,
			&i.Content,
			&i.Source,
			&i.SourcePath,
			&i.Version,
			&i.ReinforceCount,
			&i.LastReinforcedAt,
			&i.SupersededBy,
			&i.PendingReview,
			&i.StaleReason,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoriesForOwner = `-- name: ListMemoriesForOwner :many
SELECT id, owner_type, owner_id, project_id, workspace_id, mem_type, title, content, source, source_path, version, reinforce_count, last_reinforced_at, superseded_by, pending_review, stale_reason, deleted_at, created_at, updated_at FROM memories
WHERE owner_type = ? AND owner_id = ? AND deleted_at IS NULL
ORDER BY updated_at DESC
`

type ListMemoriesForOwnerParams struct {
	OwnerType string `json:"owner_type"`
	OwnerID   int64  `json:"owner_id"`
}

func (q *Queries) ListMemoriesForOwner(ctx context.Context, arg ListMemoriesForOwnerParams) ([]Memory, error) {
	rows, err := q.db.QueryContext(ctx, listMemoriesForOwner, arg.OwnerType, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memory{}
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.OwnerType,
			&i.OwnerID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.MemType,
			&i.Title,
			&i.Content,
			&i.Source,
			&i.SourcePath,
			&i.Version,
			&i.ReinforceCount,
			&i.LastReinforcedAt,
			&i.SupersededBy,
			&i.PendingReview,
			&i.StaleReason,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoriesForProject = `-- name: ListMemoriesForProject :many
SELECT id, owner_type, owner_id, project_id, workspace_id, mem_type, title, content, source, source_path, version, reinforce_count, last_reinforced_at, superseded_by, pending_review, stale_reason, deleted_at, created_at, updated_at FROM memories
WHERE project_id = ? AND deleted_at IS NULL
ORDER BY updated_at DESC
`

func (q *Queries) ListMemoriesForProject(ctx context.Context, projectID sql.NullInt64) ([]Memory, error) {
	rows, err := q.db.QueryContext(ctx, listMemoriesForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memory{}
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.OwnerType,
			&i.OwnerID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.MemType,
			&i.Title,
			&i.Content,
			&i.Source,
			&i.SourcePath,
			&i.Version,
			&i.ReinforceCount,
			&i.LastReinforcedAt,
			&i.SupersededBy,
			&i.PendingReview,
			&i.StaleReason,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemorySweepRunsForProject = `-- name: ListMemorySweepRunsForProject :many
SELECT id, project_id, "trigger", scanned, auto_deleted, queued, detail, created_at FROM memory_sweep_runs
WHERE project_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListMemorySweepRunsForProjectParams struct {
	ProjectID int64 `json:"project_id"`
	Limit     int64 `json:"limit"`
}

func (q *Queries) ListMemorySweepRunsForProject(ctx context.Context, arg ListMemorySweepRunsForProjectParams) ([]MemorySweepRun, error) {
	rows, err := q.db.QueryContext(ctx, listMemorySweepRunsForProject, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemorySweepRun{}
	for rows.Next() {
		var i MemorySweepRun
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Trigger,
			&i.Scanned,
			&i.AutoDeleted,
			&i.Queued,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryVersions = `-- name: ListMemoryVersions :many
SELECT id, memory_id, version, mem_type, title, content, source, source_path, created_at FROM memory_versions WHERE memory_id = ? ORDER BY version DESC
`

func (q *Queries) ListMemoryVersions(ctx context.Context, memoryID int64) ([]MemoryVersion, error) {
	rows, err := q.db.QueryContext(ctx, listMemoryVersions, memoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemoryVersion{}
	for rows.Next() {
		var i MemoryVersion
		if err := rows.Scan(
			&i.ID,
			&i.MemoryID,
			&i.Version,
			&i.MemType,
			&i.Title,
			&i.Content,
			&i.Source,
			&i.SourcePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingReviewForProject = `-- name: ListPendingReviewForProject :many
SELECT id, owner_type, owner_id, project_id, workspace_id, mem_type, title, content, source, source_path, version, reinforce_count, last_reinforced_at, superseded_by, pending_review, stale_reason, deleted_at, created_at, updated_at FROM memories
WHERE project_id = ? AND pending_review = 1
ORDER BY updated_at DESC
`

// The review queue: memories soft-deleted by staleness detection but awaiting a
// human keep/delete decision.
func (q *Queries) ListPendingReviewForProject(ctx context.Context, projectID sql.NullInt64) ([]Memory, error) {
	rows, err := q.db.QueryContext(ctx, listPendingReviewForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memory{}
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.OwnerType,
			&i.OwnerID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.MemType,
			&i.Title,
			&i.Content,
			&i.Source,
			&i.SourcePath,
			&i.Version,
			&i.ReinforceCount,
			&i.LastReinforcedAt,
			&i.SupersededBy,
			&i.PendingReview,
			&i.StaleReason,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reinforceMemory = `-- name: ReinforceMemory :exec
UPDATE memories
SET reinforce_count = reinforce_count + 1, last_reinforced_at = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type ReinforceMemoryParams struct {
	LastReinforcedAt sql.NullTime `json:"last_reinforced_at"`
	ID               int64        `json:"id"`
}

func (q *Queries) ReinforceMemory(ctx context.Context, arg ReinforceMemoryParams) error {
	_, err := q.db.ExecContext(ctx, reinforceMemory, arg.LastReinforcedAt, arg.ID)
	return err
}

const resolveStaleReview = `-- name: ResolveStaleReview :exec
UPDATE memories
SET pending_review = 0, stale_reason = '', updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

// Clear the review flag and reason (used when a queued memory is kept/restored).
func (q *Queries) ResolveStaleReview(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, resolveStaleReview, id)
	return err
}

const restoreMemory = `-- name: RestoreMemory :exec
UPDATE memories SET deleted_at = NULL, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) RestoreMemory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, restoreMemory, id)
	return err
}

const softDeleteMemory = `-- name: SoftDeleteMemory :exec
UPDATE memories SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) SoftDeleteMemory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteMemory, id)
	return err
}

const supersedeMemory = `-- name: SupersedeMemory :exec
UPDATE memories
SET superseded_by = ?, deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type SupersedeMemoryParams struct {
	SupersededBy sql.NullInt64 `json:"superseded_by"`
	ID           int64         `json:"id"`
}

func (q *Queries) SupersedeMemory(ctx context.Context, arg SupersedeMemoryParams) error {
	_, err := q.db.ExecContext(ctx, supersedeMemory, arg.SupersededBy, arg.ID)
	return err
}

const updateMemoryContent = `-- name: UpdateMemoryContent :one
UPDATE memories
SET mem_type = ?, title = ?, content = ?, source = ?, source_path = ?, version = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, owner_type, owner_id, project_id, workspace_id, mem_type, title, content, source, source_path, version, reinforce_count, last_reinforced_at, superseded_by, pending_review, stale_reason, deleted_at, created_at, updated_at
`

type UpdateMemoryContentParams struct {
	MemType    string `json:"mem_type"`
	Title      string `json:"title"`
	Content    string `json:"content"`
	Source     string `json:"source"`
	SourcePath string `json:"source_path"`
	Version    int64  `json:"version"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateMemoryContent(ctx context.Context, arg UpdateMemoryContentParams) (Memory, error) {
	row := q.db.QueryRowContext(ctx, updateMemoryContent,
		arg.MemType,
		arg.Title,
		arg.Content,
		arg.Source,
		arg.SourcePath,
		arg.Version,
		arg.ID,
	)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.MemType,
		&i.Title,
		&i.Content,
		&i.Source,
		&i.SourcePath,
		&i.Version,
		&i.ReinforceCount,
		&i.LastReinforcedAt,
		&i.SupersededBy,
		&i.PendingReview,
		&i.StaleReason,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMemorySweepRunDetail = `-- name: UpdateMemorySweepRunDetail :exec
UPDATE memory_sweep_runs SET detail = ? WHERE id = ?
`

type UpdateMemorySweepRunDetailParams struct {
	Detail string `json:"detail"`
	ID     int64  `json:"id"`
}

// Backfill a run's JSON detail once the maintenance workspace finishes.
func (q *Queries) UpdateMemorySweepRunDetail(ctx context.Context, arg UpdateMemorySweepRunDetailParams) error {
	_, err := q.db.ExecContext(ctx, updateMemorySweepRunDetail, arg.Detail, arg.ID)
	return err
}
