// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
	"time"
)

type Agent struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Description  string         `json:"description"`
	DirPath      string         `json:"dir_path"`
	FileHash     string         `json:"file_hash"`
	SourceUrl    sql.NullString `json:"source_url"`
	Driver       string         `json:"driver"`
	Capabilities string         `json:"capabilities"`
	OwnerType    string         `json:"owner_type"`
	OwnerID      int64          `json:"owner_id"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type AgentAskUserRequest struct {
	ID             int64          `json:"id"`
	WorkspaceID    int64          `json:"workspace_id"`
	OwnerType      string         `json:"owner_type"`
	OwnerID        int64          `json:"owner_id"`
	SessionID      string         `json:"session_id"`
	QuestionsJson  string         `json:"questions_json"`
	Status         string         `json:"status"`
	DecisionSource sql.NullString `json:"decision_source"`
	DecidedBy      sql.NullInt64  `json:"decided_by"`
	AnswersJson    sql.NullString `json:"answers_json"`
	RequestedAt    time.Time      `json:"requested_at"`
	DecidedAt      sql.NullTime   `json:"decided_at"`
	ExpiresAt      time.Time      `json:"expires_at"`
}

type AgentMessage struct {
	ID               string          `json:"id"`
	WorkspaceID      int64           `json:"workspace_id"`
	Role             string          `json:"role"`
	Content          string          `json:"content"`
	MessageID        string          `json:"message_id"`
	EventType        string          `json:"event_type"`
	ToolName         sql.NullString  `json:"tool_name"`
	ToolInput        sql.NullString  `json:"tool_input"`
	ToolUseID        sql.NullString  `json:"tool_use_id"`
	IsError          int64           `json:"is_error"`
	CostUsd          sql.NullFloat64 `json:"cost_usd"`
	NumTurns         sql.NullInt64   `json:"num_turns"`
	DurationMs       sql.NullInt64   `json:"duration_ms"`
	InputTokens      sql.NullInt64   `json:"input_tokens"`
	OutputTokens     sql.NullInt64   `json:"output_tokens"`
	HarnessRunID     sql.NullInt64   `json:"harness_run_id"`
	Attachments      sql.NullString  `json:"attachments"`
	WorkspaceAgentID sql.NullInt64   `json:"workspace_agent_id"`
	CreatedAt        time.Time       `json:"created_at"`
}

type AgentPermissionAllowlist struct {
	ID           int64         `json:"id"`
	WorkspaceID  int64         `json:"workspace_id"`
	ToolName     string        `json:"tool_name"`
	MatcherKind  string        `json:"matcher_kind"`
	MatcherValue string        `json:"matcher_value"`
	CreatedBy    sql.NullInt64 `json:"created_by"`
	CreatedAt    time.Time     `json:"created_at"`
}

type AgentPermissionRequest struct {
	ID             int64          `json:"id"`
	WorkspaceID    int64          `json:"workspace_id"`
	OwnerType      string         `json:"owner_type"`
	OwnerID        int64          `json:"owner_id"`
	SessionID      string         `json:"session_id"`
	ToolName       string         `json:"tool_name"`
	ToolInput      string         `json:"tool_input"`
	Status         string         `json:"status"`
	DecisionSource sql.NullString `json:"decision_source"`
	DecidedBy      sql.NullInt64  `json:"decided_by"`
	DenyMessage    sql.NullString `json:"deny_message"`
	MatcherUsed    sql.NullString `json:"matcher_used"`
	RequestedAt    time.Time      `json:"requested_at"`
	DecidedAt      sql.NullTime   `json:"decided_at"`
	ExpiresAt      time.Time      `json:"expires_at"`
}

type AppLicense struct {
	ID             int64     `json:"id"`
	LicenseBlob    string    `json:"license_blob"`
	IsTrial        int64     `json:"is_trial"`
	TrialStartedAt int64     `json:"trial_started_at"`
	HighWaterMark  int64     `json:"high_water_mark"`
	Customer       string    `json:"customer"`
	MaxSeats       int64     `json:"max_seats"`
	IssuedAt       int64     `json:"issued_at"`
	ExpiresAt      int64     `json:"expires_at"`
	LicenseID      string    `json:"license_id"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type BlackboardEntry struct {
	ID            int64          `json:"id"`
	WorkspaceID   int64          `json:"workspace_id"`
	ProducerAgent string         `json:"producer_agent"`
	EntryType     string         `json:"entry_type"`
	EntryKey      string         `json:"entry_key"`
	Content       string         `json:"content"`
	Metadata      string         `json:"metadata"`
	RefPath       sql.NullString `json:"ref_path"`
	HarnessRunID  sql.NullInt64  `json:"harness_run_id"`
	CreatedAt     time.Time      `json:"created_at"`
}

type Column struct {
	ID               int64          `json:"id"`
	ProjectID        int64          `json:"project_id"`
	Name             string         `json:"name"`
	Position         int64          `json:"position"`
	LifecycleMapping string         `json:"lifecycle_mapping"`
	ReviewerAgent    sql.NullString `json:"reviewer_agent"`
	PhasePrompt      sql.NullString `json:"phase_prompt"`
	AutoAdvance      int64          `json:"auto_advance"`
}

type ColumnGateSpec struct {
	ColumnID      int64  `json:"column_id"`
	SpecID        int64  `json:"spec_id"`
	Position      int64  `json:"position"`
	Applicability string `json:"applicability"`
}

type Comment struct {
	ID          int64         `json:"id"`
	WorkspaceID int64         `json:"workspace_id"`
	Repo        string        `json:"repo"`
	FilePath    string        `json:"file_path"`
	LineNumber  sql.NullInt64 `json:"line_number"`
	Content     string        `json:"content"`
	SentToAgent sql.NullBool  `json:"sent_to_agent"`
	CreatedAt   time.Time     `json:"created_at"`
}

type CommunityAgent struct {
	ID           string    `json:"id"`
	RegistryName string    `json:"registry_name"`
	Name         string    `json:"name"`
	Description  string    `json:"description"`
	Content      string    `json:"content"`
	Author       string    `json:"author"`
	Tags         string    `json:"tags"`
	SourceUrl    string    `json:"source_url"`
	CachedAt     time.Time `json:"cached_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Dashboard struct {
	ID        int64     `json:"id"`
	OwnerType string    `json:"owner_type"`
	OwnerID   int64     `json:"owner_id"`
	Name      string    `json:"name"`
	Layout    string    `json:"layout"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type DashboardPanel struct {
	ID                 int64     `json:"id"`
	DashboardID        int64     `json:"dashboard_id"`
	SavedQueryID       int64     `json:"saved_query_id"`
	Title              string    `json:"title"`
	VizType            string    `json:"viz_type"`
	ChartSpec          string    `json:"chart_spec"`
	GridX              int64     `json:"grid_x"`
	GridY              int64     `json:"grid_y"`
	GridW              int64     `json:"grid_w"`
	GridH              int64     `json:"grid_h"`
	RefreshIntervalSec int64     `json:"refresh_interval_sec"`
	CreatedAt          time.Time `json:"created_at"`
}

type DataSource struct {
	ID                int64        `json:"id"`
	OwnerType         string       `json:"owner_type"`
	OwnerID           int64        `json:"owner_id"`
	UserID            int64        `json:"user_id"`
	Name              string       `json:"name"`
	Kind              string       `json:"kind"`
	Config            string       `json:"config"`
	ScopeConfig       string       `json:"scope_config"`
	DefaultAccessMode string       `json:"default_access_mode"`
	RequireConfirm    string       `json:"require_confirm"`
	LastVerifiedAt    sql.NullTime `json:"last_verified_at"`
	CreatedAt         time.Time    `json:"created_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
}

type DataSourceAudit struct {
	ID               int64     `json:"id"`
	UserID           int64     `json:"user_id"`
	SourceID         int64     `json:"source_id"`
	AccessMode       string    `json:"access_mode"`
	DatabaseName     string    `json:"database_name"`
	Objects          string    `json:"objects"`
	StatementSummary string    `json:"statement_summary"`
	Status           string    `json:"status"`
	Rows             int64     `json:"rows"`
	DurationMs       int64     `json:"duration_ms"`
	CreatedAt        time.Time `json:"created_at"`
}

type DataSourceBinding struct {
	ID         int64     `json:"id"`
	SourceID   int64     `json:"source_id"`
	TargetType string    `json:"target_type"`
	TargetID   int64     `json:"target_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type DefaultProjectBlueprint struct {
	OwnerType   string    `json:"owner_type"`
	OwnerID     int64     `json:"owner_id"`
	BlueprintID int64     `json:"blueprint_id"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type EnvAccount struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Platform    string    `json:"platform"`
	Description string    `json:"description"`
	ApiKey      string    `json:"api_key"`
	OwnerType   string    `json:"owner_type"`
	OwnerID     int64     `json:"owner_id"`
	Slug        string    `json:"slug"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type EnvPreset struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Env         string    `json:"env"`
	OwnerType   string    `json:"owner_type"`
	OwnerID     int64     `json:"owner_id"`
	Slug        string    `json:"slug"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type EnvProvider struct {
	ID            int64     `json:"id"`
	Name          string    `json:"name"`
	Platform      string    `json:"platform"`
	Description   string    `json:"description"`
	BaseUrls      string    `json:"base_urls"`
	ApiKey        string    `json:"api_key"`
	Model         string    `json:"model"`
	HaikuModel    string    `json:"haiku_model"`
	SonnetModel   string    `json:"sonnet_model"`
	OpusModel     string    `json:"opus_model"`
	SubagentModel string    `json:"subagent_model"`
	ExtraEnv      string    `json:"extra_env"`
	OwnerType     string    `json:"owner_type"`
	OwnerID       int64     `json:"owner_id"`
	Slug          string    `json:"slug"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type ExternalApiAudit struct {
	ID         int64     `json:"id"`
	UserID     int64     `json:"user_id"`
	ProviderID int64     `json:"provider_id"`
	Method     string    `json:"method"`
	Path       string    `json:"path"`
	StatusCode int64     `json:"status_code"`
	CreatedAt  time.Time `json:"created_at"`
}

type ExternalApiWritePref struct {
	UserID     int64 `json:"user_id"`
	ProviderID int64 `json:"provider_id"`
	Enabled    int64 `json:"enabled"`
}

type ExternalProvider struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	Label      string    `json:"label"`
	ApiBaseUrl string    `json:"api_base_url"`
	AuthType   string    `json:"auth_type"`
	AuthHeader string    `json:"auth_header"`
	AuthPrefix string    `json:"auth_prefix"`
	Profile    string    `json:"profile"`
	OpenapiUrl string    `json:"openapi_url"`
	Whitelist  string    `json:"whitelist"`
	Enabled    int64     `json:"enabled"`
	CreatedBy  string    `json:"created_by"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type ExternalProviderCredential struct {
	ID             int64        `json:"id"`
	OwnerType      string       `json:"owner_type"`
	OwnerID        int64        `json:"owner_id"`
	UserID         int64        `json:"user_id"`
	Provider       string       `json:"provider"`
	Alias          string       `json:"alias"`
	Config         string       `json:"config"`
	LastVerifiedAt sql.NullTime `json:"last_verified_at"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
}

type ExternalUserIdentity struct {
	ID           int64     `json:"id"`
	UserID       int64     `json:"user_id"`
	Provider     string    `json:"provider"`
	ExternalUser string    `json:"external_user"`
	DisplayName  string    `json:"display_name"`
	AvatarUrl    string    `json:"avatar_url"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type ExternalWritePref struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	Provider  string    `json:"provider"`
	Enabled   int64     `json:"enabled"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type GitRemoteCredential struct {
	ID          int64        `json:"id"`
	UserID      int64        `json:"user_id"`
	Host        string       `json:"host"`
	Username    string       `json:"username"`
	Encrypted   string       `json:"encrypted"`
	PublicKey   string       `json:"public_key"`
	Fingerprint string       `json:"fingerprint"`
	LastUsedAt  sql.NullTime `json:"last_used_at"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
}

type HarnessCheck struct {
	ID          int64         `json:"id"`
	WorkspaceID int64         `json:"workspace_id"`
	RunID       sql.NullInt64 `json:"run_id"`
	SpecID      int64         `json:"spec_id"`
	PhaseName   string        `json:"phase_name"`
	Status      string        `json:"status"`
	Message     string        `json:"message"`
	Details     string        `json:"details"`
	DurationMs  int64         `json:"duration_ms"`
	CostUsd     float64       `json:"cost_usd"`
	CreatedAt   time.Time     `json:"created_at"`
}

type HarnessSpec struct {
	ID               int64     `json:"id"`
	Category         string    `json:"category"`
	Name             string    `json:"name"`
	Enabled          int64     `json:"enabled"`
	Severity         string    `json:"severity"`
	Config           string    `json:"config"`
	Kind             string    `json:"kind"`
	Target           string    `json:"target"`
	Pattern          string    `json:"pattern"`
	PatternFlags     string    `json:"pattern_flags"`
	Command          string    `json:"command"`
	TimeoutSec       int64     `json:"timeout_sec"`
	ExpectedExitCode int64     `json:"expected_exit_code"`
	ExtractRegex     string    `json:"extract_regex"`
	ThresholdValue   float64   `json:"threshold_value"`
	ThresholdOp      string    `json:"threshold_op"`
	FilePaths        string    `json:"file_paths"`
	TriggerOn        string    `json:"trigger_on"`
	JudgePrompt      string    `json:"judge_prompt"`
	JudgeModel       string    `json:"judge_model"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type ImBotChannel struct {
	ID                    int64     `json:"id"`
	OwnerType             string    `json:"owner_type"`
	OwnerID               int64     `json:"owner_id"`
	CredentialFingerprint string    `json:"credential_fingerprint"`
	ChannelType           string    `json:"channel_type"`
	Name                  string    `json:"name"`
	ConnectionMode        string    `json:"connection_mode"`
	CredentialEnc         string    `json:"credential_enc"`
	WebhookSecret         string    `json:"webhook_secret"`
	Status                string    `json:"status"`
	CreatedAt             time.Time `json:"created_at"`
	UpdatedAt             time.Time `json:"updated_at"`
}

type ImBotChat struct {
	ID            int64         `json:"id"`
	ChannelID     int64         `json:"channel_id"`
	ProjectID     sql.NullInt64 `json:"project_id"`
	ChatExtID     string        `json:"chat_ext_id"`
	ChatName      string        `json:"chat_name"`
	BindMode      string        `json:"bind_mode"`
	PinnedIssueID sql.NullInt64 `json:"pinned_issue_id"`
	ActiveIssueID sql.NullInt64 `json:"active_issue_id"`
	Status        string        `json:"status"`
	PairedBy      sql.NullInt64 `json:"paired_by"`
	CreatedAt     time.Time     `json:"created_at"`
	UpdatedAt     time.Time     `json:"updated_at"`
}

type ImBotInbox struct {
	ID         int64     `json:"id"`
	ChannelID  int64     `json:"channel_id"`
	EventExtID string    `json:"event_ext_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type ImBotOnboardingToken struct {
	ID             int64        `json:"id"`
	TokenHash      string       `json:"token_hash"`
	ProjectID      int64        `json:"project_id"`
	Platform       string       `json:"platform"`
	ChannelName    string       `json:"channel_name"`
	ConnectionMode string       `json:"connection_mode"`
	ExpiresAt      time.Time    `json:"expires_at"`
	UsedAt         sql.NullTime `json:"used_at"`
	CreatedAt      time.Time    `json:"created_at"`
}

type ImBotThread struct {
	ID          int64     `json:"id"`
	ChatID      int64     `json:"chat_id"`
	ThreadExtID string    `json:"thread_ext_id"`
	IssueID     int64     `json:"issue_id"`
	WorkspaceID int64     `json:"workspace_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type IpLockout struct {
	Ip          string       `json:"ip"`
	FailCount   int64        `json:"fail_count"`
	LockedUntil sql.NullTime `json:"locked_until"`
	UpdatedAt   time.Time    `json:"updated_at"`
}

type Issue struct {
	ID                         int64           `json:"id"`
	ColumnID                   int64           `json:"column_id"`
	Title                      string          `json:"title"`
	Description                sql.NullString  `json:"description"`
	Priority                   sql.NullInt64   `json:"priority"`
	Position                   int64           `json:"position"`
	LifecycleStatus            string          `json:"lifecycle_status"`
	StartDate                  sql.NullString  `json:"start_date"`
	DueDate                    sql.NullString  `json:"due_date"`
	EstimateType               sql.NullString  `json:"estimate_type"`
	Estimate                   sql.NullFloat64 `json:"estimate"`
	ActualTime                 sql.NullFloat64 `json:"actual_time"`
	ExternalSource             sql.NullString  `json:"external_source"`
	ExternalID                 sql.NullString  `json:"external_id"`
	ExternalUrl                sql.NullString  `json:"external_url"`
	ExternalSnapshotAt         sql.NullTime    `json:"external_snapshot_at"`
	ExternalCommentsSnapshot   sql.NullString  `json:"external_comments_snapshot"`
	ExternalCommentsSnapshotAt sql.NullTime    `json:"external_comments_snapshot_at"`
	GoalCondition              string          `json:"goal_condition"`
	ParentIssueID              sql.NullInt64   `json:"parent_issue_id"`
	IssueType                  string          `json:"issue_type"`
	ExecWave                   int64           `json:"exec_wave"`
	ExecStatus                 string          `json:"exec_status"`
	ExecStatusReason           sql.NullString  `json:"exec_status_reason"`
	CreatedAt                  time.Time       `json:"created_at"`
	UpdatedAt                  time.Time       `json:"updated_at"`
	CreatedBy                  sql.NullInt64   `json:"created_by"`
}

type IssueActivity struct {
	ID        int64          `json:"id"`
	IssueID   int64          `json:"issue_id"`
	Action    string         `json:"action"`
	Field     sql.NullString `json:"field"`
	OldValue  sql.NullString `json:"old_value"`
	NewValue  sql.NullString `json:"new_value"`
	Author    sql.NullString `json:"author"`
	CreatedAt time.Time      `json:"created_at"`
}

type IssueAssignee struct {
	IssueID    int64     `json:"issue_id"`
	UserID     int64     `json:"user_id"`
	AssignedAt time.Time `json:"assigned_at"`
}

type IssueChecklist struct {
	ID          int64     `json:"id"`
	IssueID     int64     `json:"issue_id"`
	Title       string    `json:"title"`
	IsCompleted int64     `json:"is_completed"`
	Position    int64     `json:"position"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type IssueComment struct {
	ID        int64     `json:"id"`
	IssueID   int64     `json:"issue_id"`
	Author    string    `json:"author"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type IssueExecEvent struct {
	ID          int64          `json:"id"`
	IssueID     int64          `json:"issue_id"`
	WorkspaceID sql.NullInt64  `json:"workspace_id"`
	Kind        string         `json:"kind"`
	Summary     string         `json:"summary"`
	DetailJson  sql.NullString `json:"detail_json"`
	CostUsd     float64        `json:"cost_usd"`
	CreatedAt   time.Time      `json:"created_at"`
}

type IssueLabel struct {
	IssueID int64 `json:"issue_id"`
	LabelID int64 `json:"label_id"`
}

type IssueRouteVisit struct {
	IssueID    int64 `json:"issue_id"`
	ColumnID   int64 `json:"column_id"`
	VisitCount int64 `json:"visit_count"`
}

type KbBinding struct {
	ID         int64     `json:"id"`
	KbID       int64     `json:"kb_id"`
	TargetType string    `json:"target_type"`
	TargetID   int64     `json:"target_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type KbDocument struct {
	ID          int64     `json:"id"`
	KbID        int64     `json:"kb_id"`
	RelPath     string    `json:"rel_path"`
	Uri         string    `json:"uri"`
	ContentHash string    `json:"content_hash"`
	ChunkCount  int64     `json:"chunk_count"`
	ByteSize    int64     `json:"byte_size"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type KnowledgeBase struct {
	ID           int64     `json:"id"`
	OwnerType    string    `json:"owner_type"`
	OwnerID      int64     `json:"owner_id"`
	Name         string    `json:"name"`
	Description  string    `json:"description"`
	SourceKind   string    `json:"source_kind"`
	SourceAddr   string    `json:"source_addr"`
	SourceConfig string    `json:"source_config"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Label struct {
	ID          int64     `json:"id"`
	ProjectID   int64     `json:"project_id"`
	Name        string    `json:"name"`
	Color       string    `json:"color"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedBy   int64     `json:"created_by"`
}

type LoginAttempt struct {
	ID        int64         `json:"id"`
	UserID    sql.NullInt64 `json:"user_id"`
	Username  string        `json:"username"`
	Ip        string        `json:"ip"`
	UserAgent string        `json:"user_agent"`
	Success   int64         `json:"success"`
	Reason    string        `json:"reason"`
	CreatedAt time.Time     `json:"created_at"`
}

type McpSessionToken struct {
	ID          int64     `json:"id"`
	WorkspaceID int64     `json:"workspace_id"`
	TokenHash   string    `json:"token_hash"`
	CreatedAt   time.Time `json:"created_at"`
	ExpiresAt   time.Time `json:"expires_at"`
}

type Memory struct {
	ID               int64         `json:"id"`
	OwnerType        string        `json:"owner_type"`
	OwnerID          int64         `json:"owner_id"`
	ProjectID        sql.NullInt64 `json:"project_id"`
	WorkspaceID      sql.NullInt64 `json:"workspace_id"`
	MemType          string        `json:"mem_type"`
	Title            string        `json:"title"`
	Content          string        `json:"content"`
	Source           string        `json:"source"`
	SourcePath       string        `json:"source_path"`
	Version          int64         `json:"version"`
	ReinforceCount   int64         `json:"reinforce_count"`
	LastReinforcedAt sql.NullTime  `json:"last_reinforced_at"`
	SupersededBy     sql.NullInt64 `json:"superseded_by"`
	PendingReview    int64         `json:"pending_review"`
	StaleReason      string        `json:"stale_reason"`
	DeletedAt        sql.NullTime  `json:"deleted_at"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
}

type MemorySweepRun struct {
	ID          int64     `json:"id"`
	ProjectID   int64     `json:"project_id"`
	Trigger     string    `json:"trigger"`
	Scanned     int64     `json:"scanned"`
	AutoDeleted int64     `json:"auto_deleted"`
	Queued      int64     `json:"queued"`
	Detail      string    `json:"detail"`
	CreatedAt   time.Time `json:"created_at"`
}

type MemoryVersion struct {
	ID         int64     `json:"id"`
	MemoryID   int64     `json:"memory_id"`
	Version    int64     `json:"version"`
	MemType    string    `json:"mem_type"`
	Title      string    `json:"title"`
	Content    string    `json:"content"`
	Source     string    `json:"source"`
	SourcePath string    `json:"source_path"`
	CreatedAt  time.Time `json:"created_at"`
}

type MfaTrustedDevice struct {
	ID         int64     `json:"id"`
	UserID     int64     `json:"user_id"`
	TokenHash  string    `json:"token_hash"`
	UserAgent  string    `json:"user_agent"`
	LastSeenAt time.Time `json:"last_seen_at"`
	ExpiresAt  time.Time `json:"expires_at"`
	CreatedAt  time.Time `json:"created_at"`
}

type OrgAuditLog struct {
	ID          int64         `json:"id"`
	OrgID       int64         `json:"org_id"`
	ActorUserID sql.NullInt64 `json:"actor_user_id"`
	ActorLabel  string        `json:"actor_label"`
	Action      string        `json:"action"`
	TargetType  string        `json:"target_type"`
	TargetID    int64         `json:"target_id"`
	Payload     string        `json:"payload"`
	CreatedAt   time.Time     `json:"created_at"`
}

type OrgMember struct {
	OrgID     int64     `json:"org_id"`
	UserID    int64     `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Organization struct {
	ID                int64          `json:"id"`
	Slug              string         `json:"slug"`
	Name              string         `json:"name"`
	Description       string         `json:"description"`
	ExternalAccountID sql.NullString `json:"external_account_id"`
	QuotaJson         string         `json:"quota_json"`
	CreatedBy         int64          `json:"created_by"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

type PinnedMessage struct {
	ID          int64     `json:"id"`
	WorkspaceID int64     `json:"workspace_id"`
	MessageID   string    `json:"message_id"`
	Role        string    `json:"role"`
	Preview     string    `json:"preview"`
	CreatedAt   time.Time `json:"created_at"`
}

type Project struct {
	ID                  int64          `json:"id"`
	Name                string         `json:"name"`
	Description         sql.NullString `json:"description"`
	Status              string         `json:"status"`
	OwnerType           string         `json:"owner_type"`
	OwnerID             int64          `json:"owner_id"`
	Color               sql.NullString `json:"color"`
	MemorySweepCron     string         `json:"memory_sweep_cron"`
	DefaultCliType      string         `json:"default_cli_type"`
	CleanupEnabled      int64          `json:"cleanup_enabled"`
	CleanupInactiveDays int64          `json:"cleanup_inactive_days"`
	CleanupStatuses     string         `json:"cleanup_statuses"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
}

type ProjectBlueprint struct {
	ID          int64     `json:"id"`
	OwnerType   string    `json:"owner_type"`
	OwnerID     int64     `json:"owner_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Content     string    `json:"content"`
	Source      string    `json:"source"`
	Slug        string    `json:"slug"`
	IsDefault   int64     `json:"is_default"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ProjectDefaultScene struct {
	ID        int64     `json:"id"`
	ProjectID int64     `json:"project_id"`
	SceneID   int64     `json:"scene_id"`
	Position  int64     `json:"position"`
	CreatedAt time.Time `json:"created_at"`
}

type ProjectExternalSource struct {
	ID           int64         `json:"id"`
	ProjectID    int64         `json:"project_id"`
	Provider     string        `json:"provider"`
	SourceKey    string        `json:"source_key"`
	CredentialID sql.NullInt64 `json:"credential_id"`
	Config       string        `json:"config"`
	CreatedAt    time.Time     `json:"created_at"`
}

type ProjectRepository struct {
	ProjectID     int64     `json:"project_id"`
	RepositoryID  int64     `json:"repository_id"`
	DefaultBranch string    `json:"default_branch"`
	CreatedAt     time.Time `json:"created_at"`
}

type QuickAction struct {
	ID        int64     `json:"id"`
	Label     string    `json:"label"`
	Content   string    `json:"content"`
	AutoSend  int64     `json:"auto_send"`
	Position  int64     `json:"position"`
	OwnerType string    `json:"owner_type"`
	OwnerID   int64     `json:"owner_id"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type RefreshToken struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Repository struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Path          string         `json:"path"`
	GitRemote     sql.NullString `json:"git_remote"`
	DefaultBranch sql.NullString `json:"default_branch"`
	OwnerType     string         `json:"owner_type"`
	OwnerID       int64          `json:"owner_id"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type SavedQuery struct {
	ID          int64         `json:"id"`
	OwnerType   string        `json:"owner_type"`
	OwnerID     int64         `json:"owner_id"`
	SourceID    sql.NullInt64 `json:"source_id"`
	WorkspaceID sql.NullInt64 `json:"workspace_id"`
	Name        string        `json:"name"`
	Operation   string        `json:"operation"`
	ChartSpec   string        `json:"chart_spec"`
	Snapshot    string        `json:"snapshot"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
}

type Scene struct {
	ID          int64     `json:"id"`
	OwnerType   string    `json:"owner_type"`
	OwnerID     int64     `json:"owner_id"`
	Slug        string    `json:"slug"`
	DisplayName string    `json:"display_name"`
	Description string    `json:"description"`
	Tags        string    `json:"tags"`
	Source      string    `json:"source"`
	SourceSlug  string    `json:"source_slug"`
	Definition  string    `json:"definition"`
	ContentHash string    `json:"content_hash"`
	Enabled     int64     `json:"enabled"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type SceneAssetImport struct {
	ID          int64     `json:"id"`
	WorkspaceID int64     `json:"workspace_id"`
	SceneID     int64     `json:"scene_id"`
	AssetKind   string    `json:"asset_kind"`
	AssetID     int64     `json:"asset_id"`
	ImportedAt  time.Time `json:"imported_at"`
}

type ScheduleRun struct {
	ID          int64     `json:"id"`
	ScheduleID  int64     `json:"schedule_id"`
	WorkspaceID int64     `json:"workspace_id"`
	Status      string    `json:"status"`
	Message     string    `json:"message"`
	CreatedAt   time.Time `json:"created_at"`
}

type ServerSetting struct {
	Key       string        `json:"key"`
	Value     string        `json:"value"`
	UpdatedAt time.Time     `json:"updated_at"`
	UpdatedBy sql.NullInt64 `json:"updated_by"`
}

type SessionState struct {
	ID          int64     `json:"id"`
	WorkspaceID int64     `json:"workspace_id"`
	SessionID   string    `json:"session_id"`
	RepoStates  string    `json:"repo_states"`
	LastUserMsg string    `json:"last_user_msg"`
	SnapshotAt  time.Time `json:"snapshot_at"`
}

type User struct {
	ID                    int64        `json:"id"`
	Username              string       `json:"username"`
	PasswordHash          string       `json:"password_hash"`
	DisplayName           string       `json:"display_name"`
	Email                 string       `json:"email"`
	Role                  string       `json:"role"`
	LockedUntil           sql.NullTime `json:"locked_until"`
	LockoutCount          int64        `json:"lockout_count"`
	RequirePasswordChange int64        `json:"require_password_change"`
	PasswordChangedAt     sql.NullTime `json:"password_changed_at"`
	MfaEnabled            int64        `json:"mfa_enabled"`
	CreatedAt             time.Time    `json:"created_at"`
	UpdatedAt             time.Time    `json:"updated_at"`
}

type UserConsent struct {
	UserID   int64     `json:"user_id"`
	Version  string    `json:"version"`
	AgreedAt time.Time `json:"agreed_at"`
}

type UserMfa struct {
	UserID           int64        `json:"user_id"`
	Method           string       `json:"method"`
	SecretCiphertext []byte       `json:"secret_ciphertext"`
	EnabledAt        sql.NullTime `json:"enabled_at"`
	ConfirmedAt      sql.NullTime `json:"confirmed_at"`
	CreatedAt        time.Time    `json:"created_at"`
}

type UserMfaBackupCode struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	CodeHash  string       `json:"code_hash"`
	UsedAt    sql.NullTime `json:"used_at"`
	CreatedAt time.Time    `json:"created_at"`
}

type UserRepositoryGitIdentity struct {
	ID           int64     `json:"id"`
	UserID       int64     `json:"user_id"`
	RepositoryID int64     `json:"repository_id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Workspace struct {
	ID                   int64          `json:"id"`
	IssueID              sql.NullInt64  `json:"issue_id"`
	Name                 string         `json:"name"`
	Path                 string         `json:"path"`
	Status               string         `json:"status"`
	AgentPid             sql.NullInt64  `json:"agent_pid"`
	AgentStatus          sql.NullString `json:"agent_status"`
	SessionID            sql.NullString `json:"session_id"`
	SessionStatus        sql.NullString `json:"session_status"`
	OwnerType            string         `json:"owner_type"`
	OwnerID              int64          `json:"owner_id"`
	CurrentSessionUserID sql.NullInt64  `json:"current_session_user_id"`
	CreatedBy            sql.NullInt64  `json:"created_by"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	IsTemporary          int64          `json:"is_temporary"`
	IsArchived           int64          `json:"is_archived"`
	ArchivedAt           sql.NullTime   `json:"archived_at"`
	McpServers           string         `json:"mcp_servers"`
	CliType              string         `json:"cli_type"`
	CodexSandboxMode     string         `json:"codex_sandbox_mode"`
	CodexApprovalPolicy  string         `json:"codex_approval_policy"`
	IsStudio             int64          `json:"is_studio"`
	StrictMcpConfig      int64          `json:"strict_mcp_config"`
	Language             string         `json:"language"`
	EnvProviderID        sql.NullInt64  `json:"env_provider_id"`
}

type WorkspaceCost struct {
	ID           int64          `json:"id"`
	WorkspaceID  int64          `json:"workspace_id"`
	SessionID    sql.NullString `json:"session_id"`
	MessageID    sql.NullString `json:"message_id"`
	CostUsd      float64        `json:"cost_usd"`
	NumTurns     int64          `json:"num_turns"`
	DurationMs   int64          `json:"duration_ms"`
	HarnessRunID sql.NullInt64  `json:"harness_run_id"`
	CreatedAt    time.Time      `json:"created_at"`
}

type WorkspaceEnv struct {
	ID          int64     `json:"id"`
	WorkspaceID int64     `json:"workspace_id"`
	Key         string    `json:"key"`
	Value       string    `json:"value"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type WorkspaceLocalRunner struct {
	WorkspaceID        int64     `json:"workspace_id"`
	LocalDir           string    `json:"local_dir"`
	PromptSnippet      string    `json:"prompt_snippet"`
	AllowedCommands    string    `json:"allowed_commands"`
	AlwaysAllowPersist int64     `json:"always_allow_persist"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type WorkspacePin struct {
	ID          int64     `json:"id"`
	UserID      int64     `json:"user_id"`
	WorkspaceID int64     `json:"workspace_id"`
	PinnedAt    time.Time `json:"pinned_at"`
}

type WorkspaceQueue struct {
	ID          int64          `json:"id"`
	WorkspaceID int64          `json:"workspace_id"`
	Content     string         `json:"content"`
	Position    float64        `json:"position"`
	Source      string         `json:"source"`
	Attachments sql.NullString `json:"attachments"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type WorkspaceSceneLayer struct {
	ID             int64         `json:"id"`
	WorkspaceID    int64         `json:"workspace_id"`
	SceneID        sql.NullInt64 `json:"scene_id"`
	Position       int64         `json:"position"`
	IsBase         int64         `json:"is_base"`
	BaseDefinition string        `json:"base_definition"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
}

type WorkspaceSceneProjection struct {
	WorkspaceID         int64        `json:"workspace_id"`
	Digest              string       `json:"digest"`
	ProjectedDefinition string       `json:"projected_definition"`
	MissingCredentials  string       `json:"missing_credentials"`
	InstallFailures     string       `json:"install_failures"`
	HotAppliedAt        sql.NullTime `json:"hot_applied_at"`
	RestartRequired     int64        `json:"restart_required"`
	RecomputedAt        time.Time    `json:"recomputed_at"`
	DismissedPlugins    string       `json:"dismissed_plugins"`
}

type WorkspaceSchedule struct {
	ID             int64        `json:"id"`
	WorkspaceID    int64        `json:"workspace_id"`
	Name           string       `json:"name"`
	DefaultMessage string       `json:"default_message"`
	ScheduleType   string       `json:"schedule_type"`
	CronExpr       string       `json:"cron_expr"`
	RunAt          sql.NullTime `json:"run_at"`
	Enabled        int64        `json:"enabled"`
	FiredAt        sql.NullTime `json:"fired_at"`
	LastRunAt      sql.NullTime `json:"last_run_at"`
	ActionKind     string       `json:"action_kind"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
}

type WorkspaceStartQueue struct {
	ID         int64        `json:"id"`
	OwnerType  string       `json:"owner_type"`
	OwnerID    int64        `json:"owner_id"`
	IssueID    int64        `json:"issue_id"`
	Status     string       `json:"status"`
	EnqueuedAt time.Time    `json:"enqueued_at"`
	StartedAt  sql.NullTime `json:"started_at"`
}

type WorkspaceStat struct {
	WorkspaceID         int64        `json:"workspace_id"`
	OwnerType           string       `json:"owner_type"`
	OwnerID             int64        `json:"owner_id"`
	UserMessageCount    int64        `json:"user_message_count"`
	AiMessageCount      int64        `json:"ai_message_count"`
	InteractionCount    int64        `json:"interaction_count"`
	TotalTurns          int64        `json:"total_turns"`
	TotalDurationMs     int64        `json:"total_duration_ms"`
	InputTokens         int64        `json:"input_tokens"`
	OutputTokens        int64        `json:"output_tokens"`
	CacheCreationTokens int64        `json:"cache_creation_tokens"`
	CacheReadTokens     int64        `json:"cache_read_tokens"`
	LastActivityAt      sql.NullTime `json:"last_activity_at"`
	UpdatedAt           time.Time    `json:"updated_at"`
}

type WorkspaceTask struct {
	ID           int64         `json:"id"`
	WorkspaceID  int64         `json:"workspace_id"`
	AgentTaskID  string        `json:"agent_task_id"`
	Subject      string        `json:"subject"`
	Description  string        `json:"description"`
	ActiveForm   string        `json:"active_form"`
	Status       string        `json:"status"`
	Phase        string        `json:"phase"`
	MessageID    string        `json:"message_id"`
	BatchID      string        `json:"batch_id"`
	HarnessRunID sql.NullInt64 `json:"harness_run_id"`
	StartedAt    sql.NullTime  `json:"started_at"`
	CompletedAt  sql.NullTime  `json:"completed_at"`
	CreatedAt    time.Time     `json:"created_at"`
	UpdatedAt    time.Time     `json:"updated_at"`
}

type WorkspaceTokenHourly struct {
	WorkspaceID         int64     `json:"workspace_id"`
	BucketHour          time.Time `json:"bucket_hour"`
	InputTokens         int64     `json:"input_tokens"`
	OutputTokens        int64     `json:"output_tokens"`
	CacheCreationTokens int64     `json:"cache_creation_tokens"`
	CacheReadTokens     int64     `json:"cache_read_tokens"`
	InteractionCount    int64     `json:"interaction_count"`
}

type Worktree struct {
	ID           int64     `json:"id"`
	WorkspaceID  int64     `json:"workspace_id"`
	RepositoryID int64     `json:"repository_id"`
	WorktreePath string    `json:"worktree_path"`
	Branch       string    `json:"branch"`
	BaseBranch   string    `json:"base_branch"`
	CreatedAt    time.Time `json:"created_at"`
}
