// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orchestration_guard.sql

package store

import (
	"context"
	"database/sql"
)

const countActiveWorkspacesForOwner = `-- name: CountActiveWorkspacesForOwner :one
SELECT COUNT(*)
FROM workspaces
WHERE owner_type = ? AND owner_id = ? AND is_archived = 0 AND status <> 'completed'
`

type CountActiveWorkspacesForOwnerParams struct {
	OwnerType string `json:"owner_type"`
	OwnerID   int64  `json:"owner_id"`
}

// Count an owner's concurrently-active workspaces: non-archived workspaces that
// have not yet completed. Drives the per-owner concurrent-workspace cap. A
// completed or archived workspace frees a slot. Uses workspace.status (not the
// linked issue's exec_status) because start_workspace-dispatched children do not
// flip exec_status to 'running' on the create hook.
func (q *Queries) CountActiveWorkspacesForOwner(ctx context.Context, arg CountActiveWorkspacesForOwnerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveWorkspacesForOwner, arg.OwnerType, arg.OwnerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const sumEpicSubtreeCostUSD = `-- name: SumEpicSubtreeCostUSD :one
SELECT CAST(COALESCE(SUM(wc.cost_usd), 0.0) AS REAL) AS total_cost_usd
FROM workspace_costs wc
WHERE wc.workspace_id IN (
    SELECT w.id FROM workspaces w
    JOIN issues i ON w.issue_id = i.id
    WHERE i.id = ? OR i.parent_issue_id = ?
)
`

type SumEpicSubtreeCostUSDParams struct {
	ID            int64         `json:"id"`
	ParentIssueID sql.NullInt64 `json:"parent_issue_id"`
}

// Cumulative cost of one orchestration tree: the epic issue's workspace plus all
// of its child issues' workspaces. Both '?' anchor the typed issues.id /
// issues.parent_issue_id columns so PostgreSQL can infer the parameter type.
func (q *Queries) SumEpicSubtreeCostUSD(ctx context.Context, arg SumEpicSubtreeCostUSDParams) (float64, error) {
	row := q.db.QueryRowContext(ctx, sumEpicSubtreeCostUSD, arg.ID, arg.ParentIssueID)
	var total_cost_usd float64
	err := row.Scan(&total_cost_usd)
	return total_cost_usd, err
}
