// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: org_audit_log.sql

package store

import (
	"context"
	"database/sql"
)

const appendOrgAudit = `-- name: AppendOrgAudit :exec
INSERT INTO org_audit_log (org_id, actor_user_id, actor_label, action, target_type, target_id, payload)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type AppendOrgAuditParams struct {
	OrgID       int64         `json:"org_id"`
	ActorUserID sql.NullInt64 `json:"actor_user_id"`
	ActorLabel  string        `json:"actor_label"`
	Action      string        `json:"action"`
	TargetType  string        `json:"target_type"`
	TargetID    int64         `json:"target_id"`
	Payload     string        `json:"payload"`
}

func (q *Queries) AppendOrgAudit(ctx context.Context, arg AppendOrgAuditParams) error {
	_, err := q.db.ExecContext(ctx, appendOrgAudit,
		arg.OrgID,
		arg.ActorUserID,
		arg.ActorLabel,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Payload,
	)
	return err
}

const listOrgAudit = `-- name: ListOrgAudit :many
SELECT id, org_id, actor_user_id, actor_label, "action", target_type, target_id, payload, created_at FROM org_audit_log
WHERE org_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListOrgAuditParams struct {
	OrgID  int64 `json:"org_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListOrgAudit(ctx context.Context, arg ListOrgAuditParams) ([]OrgAuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listOrgAudit, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrgAuditLog{}
	for rows.Next() {
		var i OrgAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ActorUserID,
			&i.ActorLabel,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
