// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (slug, name, description, created_by)
VALUES (?, ?, ?, ?)
RETURNING id, slug, name, description, external_account_id, quota_json, created_by, created_at, updated_at
`

type CreateOrganizationParams struct {
	Slug        string `json:"slug"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CreatedBy   int64  `json:"created_by"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRowContext(ctx, createOrganization,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ExternalAccountID,
		&i.QuotaJson,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrganization = `-- name: DeleteOrganization :exec
DELETE FROM organizations WHERE id = ?
`

func (q *Queries) DeleteOrganization(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteOrganization, id)
	return err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, slug, name, description, external_account_id, quota_json, created_by, created_at, updated_at FROM organizations WHERE id = ?
`

func (q *Queries) GetOrganization(ctx context.Context, id int64) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ExternalAccountID,
		&i.QuotaJson,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, slug, name, description, external_account_id, quota_json, created_by, created_at, updated_at FROM organizations WHERE slug = ?
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ExternalAccountID,
		&i.QuotaJson,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllOrganizations = `-- name: ListAllOrganizations :many
SELECT o.id, o.slug, o.name, o.description, o.external_account_id, o.quota_json, o.created_by, o.created_at, o.updated_at, m.role
FROM organizations o
LEFT JOIN org_members m ON m.org_id = o.id AND m.user_id = ?
ORDER BY o.name
`

type ListAllOrganizationsRow struct {
	ID                int64          `json:"id"`
	Slug              string         `json:"slug"`
	Name              string         `json:"name"`
	Description       string         `json:"description"`
	ExternalAccountID sql.NullString `json:"external_account_id"`
	QuotaJson         string         `json:"quota_json"`
	CreatedBy         int64          `json:"created_by"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	Role              sql.NullString `json:"role"`
}

// Admin-only: every organization, with the caller's own membership role
// (NULL when the caller is not a member). Powers the global-admin overview.
func (q *Queries) ListAllOrganizations(ctx context.Context, userID int64) ([]ListAllOrganizationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllOrganizations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllOrganizationsRow{}
	for rows.Next() {
		var i ListAllOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.ExternalAccountID,
			&i.QuotaJson,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsForUser = `-- name: ListOrganizationsForUser :many
SELECT o.id, o.slug, o.name, o.description, o.external_account_id, o.quota_json, o.created_by, o.created_at, o.updated_at, m.role
FROM organizations o
JOIN org_members m ON m.org_id = o.id
WHERE m.user_id = ?
ORDER BY o.name
`

type ListOrganizationsForUserRow struct {
	ID                int64          `json:"id"`
	Slug              string         `json:"slug"`
	Name              string         `json:"name"`
	Description       string         `json:"description"`
	ExternalAccountID sql.NullString `json:"external_account_id"`
	QuotaJson         string         `json:"quota_json"`
	CreatedBy         int64          `json:"created_by"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	Role              string         `json:"role"`
}

func (q *Queries) ListOrganizationsForUser(ctx context.Context, userID int64) ([]ListOrganizationsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationsForUserRow{}
	for rows.Next() {
		var i ListOrganizationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.ExternalAccountID,
			&i.QuotaJson,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganization = `-- name: UpdateOrganization :exec
UPDATE organizations
SET name = ?, description = ?, slug = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateOrganizationParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Slug        string `json:"slug"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, updateOrganization,
		arg.Name,
		arg.Description,
		arg.Slug,
		arg.ID,
	)
	return err
}
