// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permission.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const cancelAllPendingPermissionRequests = `-- name: CancelAllPendingPermissionRequests :many
UPDATE agent_permission_requests
   SET status = 'cancelled',
       decision_source = 'session_end',
       decided_at = CURRENT_TIMESTAMP
 WHERE status = 'pending'
 RETURNING id, workspace_id
`

type CancelAllPendingPermissionRequestsRow struct {
	ID          int64 `json:"id"`
	WorkspaceID int64 `json:"workspace_id"`
}

func (q *Queries) CancelAllPendingPermissionRequests(ctx context.Context) ([]CancelAllPendingPermissionRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, cancelAllPendingPermissionRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CancelAllPendingPermissionRequestsRow{}
	for rows.Next() {
		var i CancelAllPendingPermissionRequestsRow
		if err := rows.Scan(&i.ID, &i.WorkspaceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cancelPendingPermissionRequestsByWorkspace = `-- name: CancelPendingPermissionRequestsByWorkspace :many
UPDATE agent_permission_requests
   SET status = 'cancelled',
       decision_source = ?,
       decided_at = CURRENT_TIMESTAMP
 WHERE workspace_id = ? AND status = 'pending'
 RETURNING id, owner_type, owner_id
`

type CancelPendingPermissionRequestsByWorkspaceParams struct {
	DecisionSource sql.NullString `json:"decision_source"`
	WorkspaceID    int64          `json:"workspace_id"`
}

type CancelPendingPermissionRequestsByWorkspaceRow struct {
	ID        int64  `json:"id"`
	OwnerType string `json:"owner_type"`
	OwnerID   int64  `json:"owner_id"`
}

func (q *Queries) CancelPendingPermissionRequestsByWorkspace(ctx context.Context, arg CancelPendingPermissionRequestsByWorkspaceParams) ([]CancelPendingPermissionRequestsByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, cancelPendingPermissionRequestsByWorkspace, arg.DecisionSource, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CancelPendingPermissionRequestsByWorkspaceRow{}
	for rows.Next() {
		var i CancelPendingPermissionRequestsByWorkspaceRow
		if err := rows.Scan(&i.ID, &i.OwnerType, &i.OwnerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePermissionAllowlist = `-- name: DeletePermissionAllowlist :execrows
DELETE FROM agent_permission_allowlist WHERE id = ?
`

func (q *Queries) DeletePermissionAllowlist(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePermissionAllowlist, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPermissionAllowlistEntryWorkspaceID = `-- name: GetPermissionAllowlistEntryWorkspaceID :one
SELECT workspace_id FROM agent_permission_allowlist WHERE id = ?
`

func (q *Queries) GetPermissionAllowlistEntryWorkspaceID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPermissionAllowlistEntryWorkspaceID, id)
	var workspace_id int64
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const getPermissionRequest = `-- name: GetPermissionRequest :one
SELECT id, workspace_id, owner_type, owner_id, session_id, tool_name, tool_input, status, decision_source, decided_by, deny_message, matcher_used, requested_at, decided_at, expires_at FROM agent_permission_requests WHERE id = ?
`

func (q *Queries) GetPermissionRequest(ctx context.Context, id int64) (AgentPermissionRequest, error) {
	row := q.db.QueryRowContext(ctx, getPermissionRequest, id)
	var i AgentPermissionRequest
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.OwnerType,
		&i.OwnerID,
		&i.SessionID,
		&i.ToolName,
		&i.ToolInput,
		&i.Status,
		&i.DecisionSource,
		&i.DecidedBy,
		&i.DenyMessage,
		&i.MatcherUsed,
		&i.RequestedAt,
		&i.DecidedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertPermissionAllowlist = `-- name: InsertPermissionAllowlist :exec
INSERT INTO agent_permission_allowlist
    (workspace_id, tool_name, matcher_kind, matcher_value, created_by)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (workspace_id, tool_name, matcher_kind, matcher_value) DO NOTHING
`

type InsertPermissionAllowlistParams struct {
	WorkspaceID  int64         `json:"workspace_id"`
	ToolName     string        `json:"tool_name"`
	MatcherKind  string        `json:"matcher_kind"`
	MatcherValue string        `json:"matcher_value"`
	CreatedBy    sql.NullInt64 `json:"created_by"`
}

func (q *Queries) InsertPermissionAllowlist(ctx context.Context, arg InsertPermissionAllowlistParams) error {
	_, err := q.db.ExecContext(ctx, insertPermissionAllowlist,
		arg.WorkspaceID,
		arg.ToolName,
		arg.MatcherKind,
		arg.MatcherValue,
		arg.CreatedBy,
	)
	return err
}

const insertPermissionRequest = `-- name: InsertPermissionRequest :one
INSERT INTO agent_permission_requests
    (workspace_id, owner_type, owner_id, session_id, tool_name, tool_input, status, requested_at, expires_at)
VALUES
    (?, ?, ?, ?, ?, ?, 'pending', CURRENT_TIMESTAMP, ?)
RETURNING id
`

type InsertPermissionRequestParams struct {
	WorkspaceID int64     `json:"workspace_id"`
	OwnerType   string    `json:"owner_type"`
	OwnerID     int64     `json:"owner_id"`
	SessionID   string    `json:"session_id"`
	ToolName    string    `json:"tool_name"`
	ToolInput   string    `json:"tool_input"`
	ExpiresAt   time.Time `json:"expires_at"`
}

func (q *Queries) InsertPermissionRequest(ctx context.Context, arg InsertPermissionRequestParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPermissionRequest,
		arg.WorkspaceID,
		arg.OwnerType,
		arg.OwnerID,
		arg.SessionID,
		arg.ToolName,
		arg.ToolInput,
		arg.ExpiresAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPermissionRequestAllowed = `-- name: InsertPermissionRequestAllowed :one
INSERT INTO agent_permission_requests
    (workspace_id, owner_type, owner_id, session_id, tool_name, tool_input, status, decision_source, matcher_used, requested_at, decided_at, expires_at)
VALUES
    (?, ?, ?, ?, ?, ?, 'allowed', 'allowlist', ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ?)
RETURNING id
`

type InsertPermissionRequestAllowedParams struct {
	WorkspaceID int64          `json:"workspace_id"`
	OwnerType   string         `json:"owner_type"`
	OwnerID     int64          `json:"owner_id"`
	SessionID   string         `json:"session_id"`
	ToolName    string         `json:"tool_name"`
	ToolInput   string         `json:"tool_input"`
	MatcherUsed sql.NullString `json:"matcher_used"`
	ExpiresAt   time.Time      `json:"expires_at"`
}

// Single-write path used by allowlist hits - atomically inserts a row in
// the terminal 'allowed' state. Avoids the two-write race in recordAllowlistHit.
func (q *Queries) InsertPermissionRequestAllowed(ctx context.Context, arg InsertPermissionRequestAllowedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPermissionRequestAllowed,
		arg.WorkspaceID,
		arg.OwnerType,
		arg.OwnerID,
		arg.SessionID,
		arg.ToolName,
		arg.ToolInput,
		arg.MatcherUsed,
		arg.ExpiresAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listPendingPermissionRequestsByWorkspace = `-- name: ListPendingPermissionRequestsByWorkspace :many
SELECT id, workspace_id, owner_type, owner_id, session_id, tool_name, tool_input, status, decision_source, decided_by, deny_message, matcher_used, requested_at, decided_at, expires_at FROM agent_permission_requests
 WHERE workspace_id = ? AND status = 'pending'
 ORDER BY requested_at ASC
`

func (q *Queries) ListPendingPermissionRequestsByWorkspace(ctx context.Context, workspaceID int64) ([]AgentPermissionRequest, error) {
	rows, err := q.db.QueryContext(ctx, listPendingPermissionRequestsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentPermissionRequest{}
	for rows.Next() {
		var i AgentPermissionRequest
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.OwnerType,
			&i.OwnerID,
			&i.SessionID,
			&i.ToolName,
			&i.ToolInput,
			&i.Status,
			&i.DecisionSource,
			&i.DecidedBy,
			&i.DenyMessage,
			&i.MatcherUsed,
			&i.RequestedAt,
			&i.DecidedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionAllowlistByWorkspace = `-- name: ListPermissionAllowlistByWorkspace :many
SELECT id, workspace_id, tool_name, matcher_kind, matcher_value, created_by, created_at FROM agent_permission_allowlist
 WHERE workspace_id = ?
 ORDER BY tool_name ASC, created_at DESC
`

func (q *Queries) ListPermissionAllowlistByWorkspace(ctx context.Context, workspaceID int64) ([]AgentPermissionAllowlist, error) {
	rows, err := q.db.QueryContext(ctx, listPermissionAllowlistByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentPermissionAllowlist{}
	for rows.Next() {
		var i AgentPermissionAllowlist
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ToolName,
			&i.MatcherKind,
			&i.MatcherValue,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionAllowlistByWorkspaceAndTool = `-- name: ListPermissionAllowlistByWorkspaceAndTool :many
SELECT id, workspace_id, tool_name, matcher_kind, matcher_value, created_by, created_at FROM agent_permission_allowlist
 WHERE workspace_id = ? AND tool_name = ?
`

type ListPermissionAllowlistByWorkspaceAndToolParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	ToolName    string `json:"tool_name"`
}

func (q *Queries) ListPermissionAllowlistByWorkspaceAndTool(ctx context.Context, arg ListPermissionAllowlistByWorkspaceAndToolParams) ([]AgentPermissionAllowlist, error) {
	rows, err := q.db.QueryContext(ctx, listPermissionAllowlistByWorkspaceAndTool, arg.WorkspaceID, arg.ToolName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentPermissionAllowlist{}
	for rows.Next() {
		var i AgentPermissionAllowlist
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ToolName,
			&i.MatcherKind,
			&i.MatcherValue,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPermissionRequestAllowed = `-- name: MarkPermissionRequestAllowed :execrows
UPDATE agent_permission_requests
   SET status = 'allowed',
       decision_source = ?,
       decided_by = ?,
       matcher_used = ?,
       decided_at = CURRENT_TIMESTAMP
 WHERE id = ? AND status = 'pending'
`

type MarkPermissionRequestAllowedParams struct {
	DecisionSource sql.NullString `json:"decision_source"`
	DecidedBy      sql.NullInt64  `json:"decided_by"`
	MatcherUsed    sql.NullString `json:"matcher_used"`
	ID             int64          `json:"id"`
}

func (q *Queries) MarkPermissionRequestAllowed(ctx context.Context, arg MarkPermissionRequestAllowedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markPermissionRequestAllowed,
		arg.DecisionSource,
		arg.DecidedBy,
		arg.MatcherUsed,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markPermissionRequestCancelled = `-- name: MarkPermissionRequestCancelled :execrows
UPDATE agent_permission_requests
   SET status = 'cancelled',
       decision_source = ?,
       decided_at = CURRENT_TIMESTAMP
 WHERE id = ? AND status = 'pending'
`

type MarkPermissionRequestCancelledParams struct {
	DecisionSource sql.NullString `json:"decision_source"`
	ID             int64          `json:"id"`
}

func (q *Queries) MarkPermissionRequestCancelled(ctx context.Context, arg MarkPermissionRequestCancelledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markPermissionRequestCancelled, arg.DecisionSource, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markPermissionRequestDenied = `-- name: MarkPermissionRequestDenied :execrows
UPDATE agent_permission_requests
   SET status = 'denied',
       decision_source = ?,
       decided_by = ?,
       deny_message = ?,
       decided_at = CURRENT_TIMESTAMP
 WHERE id = ? AND status = 'pending'
`

type MarkPermissionRequestDeniedParams struct {
	DecisionSource sql.NullString `json:"decision_source"`
	DecidedBy      sql.NullInt64  `json:"decided_by"`
	DenyMessage    sql.NullString `json:"deny_message"`
	ID             int64          `json:"id"`
}

func (q *Queries) MarkPermissionRequestDenied(ctx context.Context, arg MarkPermissionRequestDeniedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markPermissionRequestDenied,
		arg.DecisionSource,
		arg.DecidedBy,
		arg.DenyMessage,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markPermissionRequestTimeout = `-- name: MarkPermissionRequestTimeout :execrows
UPDATE agent_permission_requests
   SET status = 'timeout',
       decision_source = 'timeout',
       decided_at = CURRENT_TIMESTAMP
 WHERE id = ? AND status = 'pending'
`

func (q *Queries) MarkPermissionRequestTimeout(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, markPermissionRequestTimeout, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
