// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pinned_messages.sql

package store

import (
	"context"
)

const createPinnedMessage = `-- name: CreatePinnedMessage :one
INSERT INTO pinned_messages (workspace_id, message_id, role, preview)
VALUES (?, ?, ?, ?)
ON CONFLICT (workspace_id, message_id) DO UPDATE SET
    role = excluded.role,
    preview = excluded.preview
RETURNING id, workspace_id, message_id, role, preview, created_at
`

type CreatePinnedMessageParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	MessageID   string `json:"message_id"`
	Role        string `json:"role"`
	Preview     string `json:"preview"`
}

// Upsert: re-pinning the same message refreshes the captured preview/role.
func (q *Queries) CreatePinnedMessage(ctx context.Context, arg CreatePinnedMessageParams) (PinnedMessage, error) {
	row := q.db.QueryRowContext(ctx, createPinnedMessage,
		arg.WorkspaceID,
		arg.MessageID,
		arg.Role,
		arg.Preview,
	)
	var i PinnedMessage
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.MessageID,
		&i.Role,
		&i.Preview,
		&i.CreatedAt,
	)
	return i, err
}

const deletePinnedMessage = `-- name: DeletePinnedMessage :exec
DELETE FROM pinned_messages
WHERE id = ? AND workspace_id = ?
`

type DeletePinnedMessageParams struct {
	ID          int64 `json:"id"`
	WorkspaceID int64 `json:"workspace_id"`
}

func (q *Queries) DeletePinnedMessage(ctx context.Context, arg DeletePinnedMessageParams) error {
	_, err := q.db.ExecContext(ctx, deletePinnedMessage, arg.ID, arg.WorkspaceID)
	return err
}

const listPinnedMessages = `-- name: ListPinnedMessages :many
SELECT id, workspace_id, message_id, role, preview, created_at FROM pinned_messages
WHERE workspace_id = ?
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListPinnedMessages(ctx context.Context, workspaceID int64) ([]PinnedMessage, error) {
	rows, err := q.db.QueryContext(ctx, listPinnedMessages, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PinnedMessage{}
	for rows.Next() {
		var i PinnedMessage
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.MessageID,
			&i.Role,
			&i.Preview,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
