// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_external_sources.sql

package store

import (
	"context"
	"database/sql"
	"strings"
)

const addProjectExternalSource = `-- name: AddProjectExternalSource :one
INSERT INTO project_external_sources (project_id, provider, source_key, credential_id, config)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(project_id, provider, source_key) DO UPDATE SET
    credential_id = excluded.credential_id,
    config = excluded.config
RETURNING id, project_id, provider, source_key, credential_id, config, created_at
`

type AddProjectExternalSourceParams struct {
	ProjectID    int64         `json:"project_id"`
	Provider     string        `json:"provider"`
	SourceKey    string        `json:"source_key"`
	CredentialID sql.NullInt64 `json:"credential_id"`
	Config       string        `json:"config"`
}

func (q *Queries) AddProjectExternalSource(ctx context.Context, arg AddProjectExternalSourceParams) (ProjectExternalSource, error) {
	row := q.db.QueryRowContext(ctx, addProjectExternalSource,
		arg.ProjectID,
		arg.Provider,
		arg.SourceKey,
		arg.CredentialID,
		arg.Config,
	)
	var i ProjectExternalSource
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Provider,
		&i.SourceKey,
		&i.CredentialID,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProjectExternalSource = `-- name: DeleteProjectExternalSource :exec
DELETE FROM project_external_sources WHERE id = ?
`

func (q *Queries) DeleteProjectExternalSource(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProjectExternalSource, id)
	return err
}

const getProjectExternalSource = `-- name: GetProjectExternalSource :one
SELECT id, project_id, provider, source_key, credential_id, config, created_at FROM project_external_sources
WHERE id = ?
`

func (q *Queries) GetProjectExternalSource(ctx context.Context, id int64) (ProjectExternalSource, error) {
	row := q.db.QueryRowContext(ctx, getProjectExternalSource, id)
	var i ProjectExternalSource
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Provider,
		&i.SourceKey,
		&i.CredentialID,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectExternalSourceByKey = `-- name: GetProjectExternalSourceByKey :one
SELECT id, project_id, provider, source_key, credential_id, config, created_at FROM project_external_sources
WHERE project_id = ? AND provider = ? AND source_key = ?
`

type GetProjectExternalSourceByKeyParams struct {
	ProjectID int64  `json:"project_id"`
	Provider  string `json:"provider"`
	SourceKey string `json:"source_key"`
}

func (q *Queries) GetProjectExternalSourceByKey(ctx context.Context, arg GetProjectExternalSourceByKeyParams) (ProjectExternalSource, error) {
	row := q.db.QueryRowContext(ctx, getProjectExternalSourceByKey, arg.ProjectID, arg.Provider, arg.SourceKey)
	var i ProjectExternalSource
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Provider,
		&i.SourceKey,
		&i.CredentialID,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const listProjectExternalSources = `-- name: ListProjectExternalSources :many
SELECT id, project_id, provider, source_key, credential_id, config, created_at FROM project_external_sources
WHERE project_id = ?
ORDER BY provider, source_key
`

func (q *Queries) ListProjectExternalSources(ctx context.Context, projectID int64) ([]ProjectExternalSource, error) {
	rows, err := q.db.QueryContext(ctx, listProjectExternalSources, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectExternalSource{}
	for rows.Next() {
		var i ProjectExternalSource
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Provider,
			&i.SourceKey,
			&i.CredentialID,
			&i.Config,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectExternalSourcesForOwners = `-- name: ListProjectExternalSourcesForOwners :many
SELECT pes.id, pes.project_id, pes.provider, pes.source_key, pes.credential_id, pes.config, pes.created_at FROM project_external_sources pes
JOIN projects p ON p.id = pes.project_id
WHERE (p.owner_type = 'user' AND p.owner_id = ?)
   OR (p.owner_type = 'org'  AND p.owner_id IN (/*SLICE:org_ids*/?))
ORDER BY pes.provider, pes.source_key
`

type ListProjectExternalSourcesForOwnersParams struct {
	OwnerID int64   `json:"owner_id"`
	OrgIds  []int64 `json:"org_ids"`
}

func (q *Queries) ListProjectExternalSourcesForOwners(ctx context.Context, arg ListProjectExternalSourcesForOwnersParams) ([]ProjectExternalSource, error) {
	query := listProjectExternalSourcesForOwners
	var queryParams []interface{}
	queryParams = append(queryParams, arg.OwnerID)
	if len(arg.OrgIds) > 0 {
		for _, v := range arg.OrgIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:org_ids*/?", strings.Repeat(",?", len(arg.OrgIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:org_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectExternalSource{}
	for rows.Next() {
		var i ProjectExternalSource
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Provider,
			&i.SourceKey,
			&i.CredentialID,
			&i.Config,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectExternalSourceConfig = `-- name: UpdateProjectExternalSourceConfig :one
UPDATE project_external_sources
SET config = ?
WHERE id = ?
RETURNING id, project_id, provider, source_key, credential_id, config, created_at
`

type UpdateProjectExternalSourceConfigParams struct {
	Config string `json:"config"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateProjectExternalSourceConfig(ctx context.Context, arg UpdateProjectExternalSourceConfigParams) (ProjectExternalSource, error) {
	row := q.db.QueryRowContext(ctx, updateProjectExternalSourceConfig, arg.Config, arg.ID)
	var i ProjectExternalSource
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Provider,
		&i.SourceKey,
		&i.CredentialID,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}
