// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider_usage.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const createProviderRateLimitEvent = `-- name: CreateProviderRateLimitEvent :one
INSERT INTO provider_rate_limit_events (
    provider_id, workspace_id, owner_type, owner_id, triggered_at, reset_at, detail
) VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, provider_id, workspace_id, owner_type, owner_id, triggered_at, reset_at, resumed_at, cleared_manually, detail, created_at
`

type CreateProviderRateLimitEventParams struct {
	ProviderID  int64         `json:"provider_id"`
	WorkspaceID sql.NullInt64 `json:"workspace_id"`
	OwnerType   string        `json:"owner_type"`
	OwnerID     int64         `json:"owner_id"`
	TriggeredAt time.Time     `json:"triggered_at"`
	ResetAt     time.Time     `json:"reset_at"`
	Detail      string        `json:"detail"`
}

// Opens a rate-limit episode (resumed_at stays NULL until the provider is
// actually picked for a spawn again).
func (q *Queries) CreateProviderRateLimitEvent(ctx context.Context, arg CreateProviderRateLimitEventParams) (ProviderRateLimitEvent, error) {
	row := q.db.QueryRowContext(ctx, createProviderRateLimitEvent,
		arg.ProviderID,
		arg.WorkspaceID,
		arg.OwnerType,
		arg.OwnerID,
		arg.TriggeredAt,
		arg.ResetAt,
		arg.Detail,
	)
	var i ProviderRateLimitEvent
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.WorkspaceID,
		&i.OwnerType,
		&i.OwnerID,
		&i.TriggeredAt,
		&i.ResetAt,
		&i.ResumedAt,
		&i.ClearedManually,
		&i.Detail,
		&i.CreatedAt,
	)
	return i, err
}

const extendProviderRateLimitEvent = `-- name: ExtendProviderRateLimitEvent :exec
UPDATE provider_rate_limit_events
SET reset_at = ?, detail = ?
WHERE id = ?
`

type ExtendProviderRateLimitEventParams struct {
	ResetAt time.Time `json:"reset_at"`
	Detail  string    `json:"detail"`
	ID      int64     `json:"id"`
}

// Pushes an open episode's reset_at later. A platform can re-report a 429 with
// a further-out reset while the provider is still sidelined; that is the SAME
// episode with a longer quota window, so the row is extended instead of a
// second row being opened (which would double-count the throttle tally).
func (q *Queries) ExtendProviderRateLimitEvent(ctx context.Context, arg ExtendProviderRateLimitEventParams) error {
	_, err := q.db.ExecContext(ctx, extendProviderRateLimitEvent, arg.ResetAt, arg.Detail, arg.ID)
	return err
}

const getOpenProviderRateLimitEvent = `-- name: GetOpenProviderRateLimitEvent :one
SELECT id, provider_id, workspace_id, owner_type, owner_id, triggered_at, reset_at, resumed_at, cleared_manually, detail, created_at FROM provider_rate_limit_events
WHERE provider_id = ? AND resumed_at IS NULL
ORDER BY triggered_at DESC
LIMIT 1
`

// The provider's most recent still-open episode (never resumed). Used to avoid
// opening a duplicate row when a platform emits several 429 lines in a burst,
// and to find the row to close on resume.
func (q *Queries) GetOpenProviderRateLimitEvent(ctx context.Context, providerID int64) (ProviderRateLimitEvent, error) {
	row := q.db.QueryRowContext(ctx, getOpenProviderRateLimitEvent, providerID)
	var i ProviderRateLimitEvent
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.WorkspaceID,
		&i.OwnerType,
		&i.OwnerID,
		&i.TriggeredAt,
		&i.ResetAt,
		&i.ResumedAt,
		&i.ClearedManually,
		&i.Detail,
		&i.CreatedAt,
	)
	return i, err
}

const listOwnerProviderRateLimitEvents = `-- name: ListOwnerProviderRateLimitEvents :many
SELECT
    e.id,
    e.provider_id,
    p.name     AS provider_name,
    p.platform AS provider_platform,
    e.workspace_id,
    e.triggered_at,
    e.reset_at,
    e.resumed_at,
    e.cleared_manually,
    e.detail
FROM provider_rate_limit_events e
JOIN env_providers p ON p.id = e.provider_id
WHERE e.owner_type = ? AND e.owner_id = ?
  AND e.triggered_at >= ? AND e.triggered_at < ?
ORDER BY e.triggered_at DESC
LIMIT ?
`

type ListOwnerProviderRateLimitEventsParams struct {
	OwnerType     string    `json:"owner_type"`
	OwnerID       int64     `json:"owner_id"`
	TriggeredAt   time.Time `json:"triggered_at"`
	TriggeredAt_2 time.Time `json:"triggered_at_2"`
	Limit         int64     `json:"limit"`
}

type ListOwnerProviderRateLimitEventsRow struct {
	ID               int64         `json:"id"`
	ProviderID       int64         `json:"provider_id"`
	ProviderName     string        `json:"provider_name"`
	ProviderPlatform string        `json:"provider_platform"`
	WorkspaceID      sql.NullInt64 `json:"workspace_id"`
	TriggeredAt      time.Time     `json:"triggered_at"`
	ResetAt          time.Time     `json:"reset_at"`
	ResumedAt        sql.NullTime  `json:"resumed_at"`
	ClearedManually  int64         `json:"cleared_manually"`
	Detail           string        `json:"detail"`
}

// Event log for the owner's platforms, newest first, for the UI table.
func (q *Queries) ListOwnerProviderRateLimitEvents(ctx context.Context, arg ListOwnerProviderRateLimitEventsParams) ([]ListOwnerProviderRateLimitEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOwnerProviderRateLimitEvents,
		arg.OwnerType,
		arg.OwnerID,
		arg.TriggeredAt,
		arg.TriggeredAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnerProviderRateLimitEventsRow{}
	for rows.Next() {
		var i ListOwnerProviderRateLimitEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ProviderName,
			&i.ProviderPlatform,
			&i.WorkspaceID,
			&i.TriggeredAt,
			&i.ResetAt,
			&i.ResumedAt,
			&i.ClearedManually,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnerProviderRateLimitSpans = `-- name: ListOwnerProviderRateLimitSpans :many
SELECT provider_id, triggered_at, resumed_at
FROM provider_rate_limit_events
WHERE owner_type = ? AND owner_id = ?
  AND triggered_at >= ? AND triggered_at < ?
`

type ListOwnerProviderRateLimitSpansParams struct {
	OwnerType     string    `json:"owner_type"`
	OwnerID       int64     `json:"owner_id"`
	TriggeredAt   time.Time `json:"triggered_at"`
	TriggeredAt_2 time.Time `json:"triggered_at_2"`
}

type ListOwnerProviderRateLimitSpansRow struct {
	ProviderID  int64        `json:"provider_id"`
	TriggeredAt time.Time    `json:"triggered_at"`
	ResumedAt   sql.NullTime `json:"resumed_at"`
}

// Raw (provider, triggered_at, resumed_at) spans over the window, unlimited, so
// the service can aggregate per-platform throttle counts and blocked duration.
// Deliberately NOT computed in SQL: date arithmetic is dialect-specific
// (strftime vs EXTRACT) and this store targets both SQLite and PostgreSQL.
// An open span (resumed_at NULL) counts toward the tally but contributes no
// duration, so "blocked so far" is honest rather than an invented end time.
func (q *Queries) ListOwnerProviderRateLimitSpans(ctx context.Context, arg ListOwnerProviderRateLimitSpansParams) ([]ListOwnerProviderRateLimitSpansRow, error) {
	rows, err := q.db.QueryContext(ctx, listOwnerProviderRateLimitSpans,
		arg.OwnerType,
		arg.OwnerID,
		arg.TriggeredAt,
		arg.TriggeredAt_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnerProviderRateLimitSpansRow{}
	for rows.Next() {
		var i ListOwnerProviderRateLimitSpansRow
		if err := rows.Scan(&i.ProviderID, &i.TriggeredAt, &i.ResumedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnerProviderTokenHourly = `-- name: ListOwnerProviderTokenHourly :many
SELECT
    h.bucket_hour,
    h.provider_id,
    p.name     AS provider_name,
    p.platform AS provider_platform,
    CAST(COALESCE(SUM(h.input_tokens),0)          AS BIGINT) AS input_tokens,
    CAST(COALESCE(SUM(h.output_tokens),0)         AS BIGINT) AS output_tokens,
    CAST(COALESCE(SUM(h.cache_creation_tokens),0) AS BIGINT) AS cache_creation_tokens,
    CAST(COALESCE(SUM(h.cache_read_tokens),0)     AS BIGINT) AS cache_read_tokens,
    CAST(COALESCE(SUM(h.interaction_count),0)     AS BIGINT) AS interaction_count
FROM provider_token_hourly h
JOIN env_providers p ON p.id = h.provider_id
WHERE h.owner_type = ? AND h.owner_id = ?
  AND h.bucket_hour >= ? AND h.bucket_hour < ?
GROUP BY h.bucket_hour, h.provider_id, p.name, p.platform
ORDER BY h.bucket_hour
`

type ListOwnerProviderTokenHourlyParams struct {
	OwnerType    string    `json:"owner_type"`
	OwnerID      int64     `json:"owner_id"`
	BucketHour   time.Time `json:"bucket_hour"`
	BucketHour_2 time.Time `json:"bucket_hour_2"`
}

type ListOwnerProviderTokenHourlyRow struct {
	BucketHour          time.Time `json:"bucket_hour"`
	ProviderID          int64     `json:"provider_id"`
	ProviderName        string    `json:"provider_name"`
	ProviderPlatform    string    `json:"provider_platform"`
	InputTokens         int64     `json:"input_tokens"`
	OutputTokens        int64     `json:"output_tokens"`
	CacheCreationTokens int64     `json:"cache_creation_tokens"`
	CacheReadTokens     int64     `json:"cache_read_tokens"`
	InteractionCount    int64     `json:"interaction_count"`
}

// Hourly series broken down BY platform for one owner: the main chart's data,
// one row per (hour, provider). provider_name is joined in so the UI does not
// need a second round trip to label the series.
func (q *Queries) ListOwnerProviderTokenHourly(ctx context.Context, arg ListOwnerProviderTokenHourlyParams) ([]ListOwnerProviderTokenHourlyRow, error) {
	rows, err := q.db.QueryContext(ctx, listOwnerProviderTokenHourly,
		arg.OwnerType,
		arg.OwnerID,
		arg.BucketHour,
		arg.BucketHour_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnerProviderTokenHourlyRow{}
	for rows.Next() {
		var i ListOwnerProviderTokenHourlyRow
		if err := rows.Scan(
			&i.BucketHour,
			&i.ProviderID,
			&i.ProviderName,
			&i.ProviderPlatform,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheCreationTokens,
			&i.CacheReadTokens,
			&i.InteractionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderTokenHourly = `-- name: ListProviderTokenHourly :many
SELECT bucket_hour, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, interaction_count
FROM provider_token_hourly
WHERE provider_id = ? AND owner_type = ? AND owner_id = ?
  AND bucket_hour >= ? AND bucket_hour < ?
ORDER BY bucket_hour
`

type ListProviderTokenHourlyParams struct {
	ProviderID   int64     `json:"provider_id"`
	OwnerType    string    `json:"owner_type"`
	OwnerID      int64     `json:"owner_id"`
	BucketHour   time.Time `json:"bucket_hour"`
	BucketHour_2 time.Time `json:"bucket_hour_2"`
}

type ListProviderTokenHourlyRow struct {
	BucketHour          time.Time `json:"bucket_hour"`
	InputTokens         int64     `json:"input_tokens"`
	OutputTokens        int64     `json:"output_tokens"`
	CacheCreationTokens int64     `json:"cache_creation_tokens"`
	CacheReadTokens     int64     `json:"cache_read_tokens"`
	InteractionCount    int64     `json:"interaction_count"`
}

// Hourly series for ONE platform in [from, to), for the drill-down chart.
func (q *Queries) ListProviderTokenHourly(ctx context.Context, arg ListProviderTokenHourlyParams) ([]ListProviderTokenHourlyRow, error) {
	rows, err := q.db.QueryContext(ctx, listProviderTokenHourly,
		arg.ProviderID,
		arg.OwnerType,
		arg.OwnerID,
		arg.BucketHour,
		arg.BucketHour_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProviderTokenHourlyRow{}
	for rows.Next() {
		var i ListProviderTokenHourlyRow
		if err := rows.Scan(
			&i.BucketHour,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheCreationTokens,
			&i.CacheReadTokens,
			&i.InteractionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneProviderRateLimitEvents = `-- name: PruneProviderRateLimitEvents :exec
DELETE FROM provider_rate_limit_events WHERE triggered_at < ?
`

func (q *Queries) PruneProviderRateLimitEvents(ctx context.Context, triggeredAt time.Time) error {
	_, err := q.db.ExecContext(ctx, pruneProviderRateLimitEvents, triggeredAt)
	return err
}

const pruneProviderTokenHourly = `-- name: PruneProviderTokenHourly :exec
DELETE FROM provider_token_hourly WHERE bucket_hour < ?
`

func (q *Queries) PruneProviderTokenHourly(ctx context.Context, bucketHour time.Time) error {
	_, err := q.db.ExecContext(ctx, pruneProviderTokenHourly, bucketHour)
	return err
}

const resumeProviderRateLimitEvents = `-- name: ResumeProviderRateLimitEvents :exec
UPDATE provider_rate_limit_events
SET resumed_at = ?, cleared_manually = ?
WHERE provider_id = ? AND resumed_at IS NULL
`

type ResumeProviderRateLimitEventsParams struct {
	ResumedAt       sql.NullTime `json:"resumed_at"`
	ClearedManually int64        `json:"cleared_manually"`
	ProviderID      int64        `json:"provider_id"`
}

// Closes every open episode for a provider: the provider is back in service,
// so resumed_at is the real "unblocked and used again" timestamp. Plural
// because a burst that raced past the dedup guard can leave more than one row
// open; closing all of them keeps "open episode" meaning "currently limited".
func (q *Queries) ResumeProviderRateLimitEvents(ctx context.Context, arg ResumeProviderRateLimitEventsParams) error {
	_, err := q.db.ExecContext(ctx, resumeProviderRateLimitEvents, arg.ResumedAt, arg.ClearedManually, arg.ProviderID)
	return err
}

const sumOwnerProviderTokens = `-- name: SumOwnerProviderTokens :many
SELECT
    h.provider_id,
    p.name     AS provider_name,
    p.platform AS provider_platform,
    CAST(COALESCE(SUM(h.input_tokens),0)          AS BIGINT) AS input_tokens,
    CAST(COALESCE(SUM(h.output_tokens),0)         AS BIGINT) AS output_tokens,
    CAST(COALESCE(SUM(h.cache_creation_tokens),0) AS BIGINT) AS cache_creation_tokens,
    CAST(COALESCE(SUM(h.cache_read_tokens),0)     AS BIGINT) AS cache_read_tokens,
    CAST(COALESCE(SUM(h.interaction_count),0)     AS BIGINT) AS interaction_count
FROM provider_token_hourly h
JOIN env_providers p ON p.id = h.provider_id
WHERE h.owner_type = ? AND h.owner_id = ?
  AND h.bucket_hour >= ? AND h.bucket_hour < ?
GROUP BY h.provider_id, p.name, p.platform
ORDER BY SUM(h.input_tokens + h.output_tokens) DESC
`

type SumOwnerProviderTokensParams struct {
	OwnerType    string    `json:"owner_type"`
	OwnerID      int64     `json:"owner_id"`
	BucketHour   time.Time `json:"bucket_hour"`
	BucketHour_2 time.Time `json:"bucket_hour_2"`
}

type SumOwnerProviderTokensRow struct {
	ProviderID          int64  `json:"provider_id"`
	ProviderName        string `json:"provider_name"`
	ProviderPlatform    string `json:"provider_platform"`
	InputTokens         int64  `json:"input_tokens"`
	OutputTokens        int64  `json:"output_tokens"`
	CacheCreationTokens int64  `json:"cache_creation_tokens"`
	CacheReadTokens     int64  `json:"cache_read_tokens"`
	InteractionCount    int64  `json:"interaction_count"`
}

// Per-platform TOTALS over the window (no hour dimension): drives the summary
// table so the UI does not have to re-sum the hourly series client-side.
func (q *Queries) SumOwnerProviderTokens(ctx context.Context, arg SumOwnerProviderTokensParams) ([]SumOwnerProviderTokensRow, error) {
	rows, err := q.db.QueryContext(ctx, sumOwnerProviderTokens,
		arg.OwnerType,
		arg.OwnerID,
		arg.BucketHour,
		arg.BucketHour_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumOwnerProviderTokensRow{}
	for rows.Next() {
		var i SumOwnerProviderTokensRow
		if err := rows.Scan(
			&i.ProviderID,
			&i.ProviderName,
			&i.ProviderPlatform,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheCreationTokens,
			&i.CacheReadTokens,
			&i.InteractionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProviderTokenHourly = `-- name: UpsertProviderTokenHourly :exec
INSERT INTO provider_token_hourly (
    provider_id, owner_type, owner_id, bucket_hour,
    input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, interaction_count
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 1)
ON CONFLICT(provider_id, owner_type, owner_id, bucket_hour) DO UPDATE SET
    input_tokens          = provider_token_hourly.input_tokens + excluded.input_tokens,
    output_tokens         = provider_token_hourly.output_tokens + excluded.output_tokens,
    cache_creation_tokens = provider_token_hourly.cache_creation_tokens + excluded.cache_creation_tokens,
    cache_read_tokens     = provider_token_hourly.cache_read_tokens + excluded.cache_read_tokens,
    interaction_count     = provider_token_hourly.interaction_count + 1
`

type UpsertProviderTokenHourlyParams struct {
	ProviderID          int64     `json:"provider_id"`
	OwnerType           string    `json:"owner_type"`
	OwnerID             int64     `json:"owner_id"`
	BucketHour          time.Time `json:"bucket_hour"`
	InputTokens         int64     `json:"input_tokens"`
	OutputTokens        int64     `json:"output_tokens"`
	CacheCreationTokens int64     `json:"cache_creation_tokens"`
	CacheReadTokens     int64     `json:"cache_read_tokens"`
}

// Additive per-hour accumulation at subscription-platform grain. Mirrors
// UpsertWorkspaceTokenHourly, but keyed on the provider plus the CONSUMING
// owner (shared seeded providers have owner_id = 0, so keying on the provider
// row's owner would collapse every user into one series).
func (q *Queries) UpsertProviderTokenHourly(ctx context.Context, arg UpsertProviderTokenHourlyParams) error {
	_, err := q.db.ExecContext(ctx, upsertProviderTokenHourly,
		arg.ProviderID,
		arg.OwnerType,
		arg.OwnerID,
		arg.BucketHour,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheCreationTokens,
		arg.CacheReadTokens,
	)
	return err
}
