// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repositories.sql

package store

import (
	"context"
	"database/sql"
)

const createRepository = `-- name: CreateRepository :one
INSERT INTO repositories (name, path, git_remote, default_branch, owner_type, owner_id) VALUES (?, ?, ?, ?, ?, ?) RETURNING id, name, path, git_remote, default_branch, owner_type, owner_id, created_at, updated_at
`

type CreateRepositoryParams struct {
	Name          string         `json:"name"`
	Path          string         `json:"path"`
	GitRemote     sql.NullString `json:"git_remote"`
	DefaultBranch sql.NullString `json:"default_branch"`
	OwnerType     string         `json:"owner_type"`
	OwnerID       int64          `json:"owner_id"`
}

func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error) {
	row := q.db.QueryRowContext(ctx, createRepository,
		arg.Name,
		arg.Path,
		arg.GitRemote,
		arg.DefaultBranch,
		arg.OwnerType,
		arg.OwnerID,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.GitRemote,
		&i.DefaultBranch,
		&i.OwnerType,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRepository = `-- name: DeleteRepository :exec
DELETE FROM repositories WHERE id = ?
`

func (q *Queries) DeleteRepository(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRepository, id)
	return err
}

const getRepository = `-- name: GetRepository :one
SELECT id, name, path, git_remote, default_branch, owner_type, owner_id, created_at, updated_at FROM repositories WHERE id = ?
`

func (q *Queries) GetRepository(ctx context.Context, id int64) (Repository, error) {
	row := q.db.QueryRowContext(ctx, getRepository, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.GitRemote,
		&i.DefaultBranch,
		&i.OwnerType,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryByName = `-- name: GetRepositoryByName :one
SELECT id, name, path, git_remote, default_branch, owner_type, owner_id, created_at, updated_at FROM repositories WHERE name = ?
`

func (q *Queries) GetRepositoryByName(ctx context.Context, name string) (Repository, error) {
	row := q.db.QueryRowContext(ctx, getRepositoryByName, name)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.GitRemote,
		&i.DefaultBranch,
		&i.OwnerType,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRepositories = `-- name: ListRepositories :many
SELECT id, name, path, git_remote, default_branch, owner_type, owner_id, created_at, updated_at FROM repositories ORDER BY created_at DESC
`

func (q *Queries) ListRepositories(ctx context.Context) ([]Repository, error) {
	rows, err := q.db.QueryContext(ctx, listRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.GitRemote,
			&i.DefaultBranch,
			&i.OwnerType,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRepository = `-- name: UpdateRepository :one
UPDATE repositories SET name = ?, path = ?, git_remote = ?, default_branch = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, name, path, git_remote, default_branch, owner_type, owner_id, created_at, updated_at
`

type UpdateRepositoryParams struct {
	Name          string         `json:"name"`
	Path          string         `json:"path"`
	GitRemote     sql.NullString `json:"git_remote"`
	DefaultBranch sql.NullString `json:"default_branch"`
	ID            int64          `json:"id"`
}

func (q *Queries) UpdateRepository(ctx context.Context, arg UpdateRepositoryParams) (Repository, error) {
	row := q.db.QueryRowContext(ctx, updateRepository,
		arg.Name,
		arg.Path,
		arg.GitRemote,
		arg.DefaultBranch,
		arg.ID,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.GitRemote,
		&i.DefaultBranch,
		&i.OwnerType,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
