// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scenes.sql

package store

import (
	"context"
	"strings"
)

const countScenesByOwner = `-- name: CountScenesByOwner :one
SELECT COUNT(*) FROM scenes
WHERE owner_type = ? AND owner_id = ?
`

type CountScenesByOwnerParams struct {
	OwnerType string `json:"owner_type"`
	OwnerID   int64  `json:"owner_id"`
}

func (q *Queries) CountScenesByOwner(ctx context.Context, arg CountScenesByOwnerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countScenesByOwner, arg.OwnerType, arg.OwnerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScene = `-- name: CreateScene :one
INSERT INTO scenes
  (owner_type, owner_id, slug, display_name, description, tags, source, source_slug, definition, content_hash, enabled)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, owner_type, owner_id, slug, display_name, description, tags, source, source_slug, definition, content_hash, enabled, created_at, updated_at
`

type CreateSceneParams struct {
	OwnerType   string `json:"owner_type"`
	OwnerID     int64  `json:"owner_id"`
	Slug        string `json:"slug"`
	DisplayName string `json:"display_name"`
	Description string `json:"description"`
	Tags        string `json:"tags"`
	Source      string `json:"source"`
	SourceSlug  string `json:"source_slug"`
	Definition  string `json:"definition"`
	ContentHash string `json:"content_hash"`
	Enabled     int64  `json:"enabled"`
}

func (q *Queries) CreateScene(ctx context.Context, arg CreateSceneParams) (Scene, error) {
	row := q.db.QueryRowContext(ctx, createScene,
		arg.OwnerType,
		arg.OwnerID,
		arg.Slug,
		arg.DisplayName,
		arg.Description,
		arg.Tags,
		arg.Source,
		arg.SourceSlug,
		arg.Definition,
		arg.ContentHash,
		arg.Enabled,
	)
	var i Scene
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.Tags,
		&i.Source,
		&i.SourceSlug,
		&i.Definition,
		&i.ContentHash,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteScene = `-- name: DeleteScene :exec
DELETE FROM scenes WHERE id = ?
`

func (q *Queries) DeleteScene(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteScene, id)
	return err
}

const getScene = `-- name: GetScene :one
SELECT id, owner_type, owner_id, slug, display_name, description, tags, source, source_slug, definition, content_hash, enabled, created_at, updated_at FROM scenes WHERE id = ?
`

func (q *Queries) GetScene(ctx context.Context, id int64) (Scene, error) {
	row := q.db.QueryRowContext(ctx, getScene, id)
	var i Scene
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.Tags,
		&i.Source,
		&i.SourceSlug,
		&i.Definition,
		&i.ContentHash,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSceneByOwnerSlug = `-- name: GetSceneByOwnerSlug :one
SELECT id, owner_type, owner_id, slug, display_name, description, tags, source, source_slug, definition, content_hash, enabled, created_at, updated_at FROM scenes
WHERE owner_type = ? AND owner_id = ? AND slug = ?
`

type GetSceneByOwnerSlugParams struct {
	OwnerType string `json:"owner_type"`
	OwnerID   int64  `json:"owner_id"`
	Slug      string `json:"slug"`
}

// Lookup by (owner_type, owner_id, slug). 'builtin' scenes use the sentinel
// (owner_type='user', owner_id=0) and are looked up the same way.
func (q *Queries) GetSceneByOwnerSlug(ctx context.Context, arg GetSceneByOwnerSlugParams) (Scene, error) {
	row := q.db.QueryRowContext(ctx, getSceneByOwnerSlug, arg.OwnerType, arg.OwnerID, arg.Slug)
	var i Scene
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.Tags,
		&i.Source,
		&i.SourceSlug,
		&i.Definition,
		&i.ContentHash,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScenesByIDs = `-- name: GetScenesByIDs :many
SELECT id, owner_type, owner_id, slug, display_name, description, tags, source, source_slug, definition, content_hash, enabled, created_at, updated_at FROM scenes WHERE id IN (/*SLICE:ids*/?)
`

// Batched form of GetScene for resolving a workspace's scene layers in one
// query (scene projection recompute) instead of one query per layer.
func (q *Queries) GetScenesByIDs(ctx context.Context, ids []int64) ([]Scene, error) {
	query := getScenesByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scene{}
	for rows.Next() {
		var i Scene
		if err := rows.Scan(
			&i.ID,
			&i.OwnerType,
			&i.OwnerID,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.Tags,
			&i.Source,
			&i.SourceSlug,
			&i.Definition,
			&i.ContentHash,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuiltinScenes = `-- name: ListBuiltinScenes :many
SELECT id, owner_type, owner_id, slug, display_name, description, tags, source, source_slug, definition, content_hash, enabled, created_at, updated_at FROM scenes WHERE source = 'builtin' ORDER BY slug ASC
`

func (q *Queries) ListBuiltinScenes(ctx context.Context) ([]Scene, error) {
	rows, err := q.db.QueryContext(ctx, listBuiltinScenes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scene{}
	for rows.Next() {
		var i Scene
		if err := rows.Scan(
			&i.ID,
			&i.OwnerType,
			&i.OwnerID,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.Tags,
			&i.Source,
			&i.SourceSlug,
			&i.Definition,
			&i.ContentHash,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScene = `-- name: UpdateScene :exec
UPDATE scenes
SET display_name = ?,
    description = ?,
    tags = ?,
    definition = ?,
    content_hash = ?,
    enabled = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateSceneParams struct {
	DisplayName string `json:"display_name"`
	Description string `json:"description"`
	Tags        string `json:"tags"`
	Definition  string `json:"definition"`
	ContentHash string `json:"content_hash"`
	Enabled     int64  `json:"enabled"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateScene(ctx context.Context, arg UpdateSceneParams) error {
	_, err := q.db.ExecContext(ctx, updateScene,
		arg.DisplayName,
		arg.Description,
		arg.Tags,
		arg.Definition,
		arg.ContentHash,
		arg.Enabled,
		arg.ID,
	)
	return err
}

const upsertBuiltinScene = `-- name: UpsertBuiltinScene :exec
INSERT INTO scenes
  (owner_type, owner_id, slug, display_name, description, tags, source, source_slug, definition, content_hash, enabled)
VALUES ('user', 0, ?, ?, ?, ?, 'builtin', ?, ?, ?, 1)
ON CONFLICT(owner_type, owner_id, slug) DO UPDATE SET
  display_name = excluded.display_name,
  description = excluded.description,
  tags = excluded.tags,
  source_slug = excluded.source_slug,
  definition = excluded.definition,
  content_hash = excluded.content_hash,
  updated_at = CURRENT_TIMESTAMP
WHERE scenes.source = 'builtin'
`

type UpsertBuiltinSceneParams struct {
	Slug        string `json:"slug"`
	DisplayName string `json:"display_name"`
	Description string `json:"description"`
	Tags        string `json:"tags"`
	SourceSlug  string `json:"source_slug"`
	Definition  string `json:"definition"`
	ContentHash string `json:"content_hash"`
}

// Builtin seed path: insert-or-update by (owner_type, owner_id, slug) where
// owner is the global sentinel (user, 0). User-forked copies live under
// their own (owner_type, owner_id) tuple and do not collide.
func (q *Queries) UpsertBuiltinScene(ctx context.Context, arg UpsertBuiltinSceneParams) error {
	_, err := q.db.ExecContext(ctx, upsertBuiltinScene,
		arg.Slug,
		arg.DisplayName,
		arg.Description,
		arg.Tags,
		arg.SourceSlug,
		arg.Definition,
		arg.ContentHash,
	)
	return err
}
