// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedule_runs.sql

package store

import (
	"context"
)

const createScheduleRun = `-- name: CreateScheduleRun :one
INSERT INTO schedule_runs (schedule_id, workspace_id, status, message)
VALUES (?, ?, ?, ?)
RETURNING id, schedule_id, workspace_id, status, message, created_at
`

type CreateScheduleRunParams struct {
	ScheduleID  int64  `json:"schedule_id"`
	WorkspaceID int64  `json:"workspace_id"`
	Status      string `json:"status"`
	Message     string `json:"message"`
}

func (q *Queries) CreateScheduleRun(ctx context.Context, arg CreateScheduleRunParams) (ScheduleRun, error) {
	row := q.db.QueryRowContext(ctx, createScheduleRun,
		arg.ScheduleID,
		arg.WorkspaceID,
		arg.Status,
		arg.Message,
	)
	var i ScheduleRun
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.WorkspaceID,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const listScheduleRuns = `-- name: ListScheduleRuns :many
SELECT id, schedule_id, workspace_id, status, message, created_at FROM schedule_runs
WHERE schedule_id = ?1
  AND (CAST(?2 AS BIGINT) = 0 OR id < ?2)
ORDER BY created_at DESC
LIMIT ?3
`

type ListScheduleRunsParams struct {
	ScheduleID int64 `json:"schedule_id"`
	BeforeID   int64 `json:"before_id"`
	Limit      int64 `json:"limit"`
}

// before_id is a "no filter" sentinel: 0 means "no upper bound, return latest".
// The CAST(... AS BIGINT) anchors the parameter's parse-time type so Postgres
// can unify the two uses (= 0 and id < ?) without SQLSTATE 42P18. SQLite is
// fine with CAST(x AS BIGINT) because BIGINT collapses to INTEGER affinity.
func (q *Queries) ListScheduleRuns(ctx context.Context, arg ListScheduleRunsParams) ([]ScheduleRun, error) {
	rows, err := q.db.QueryContext(ctx, listScheduleRuns, arg.ScheduleID, arg.BeforeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleRun{}
	for rows.Next() {
		var i ScheduleRun
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.WorkspaceID,
			&i.Status,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
