// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: server_settings.sql

package store

import (
	"context"
	"database/sql"
)

const getServerSetting = `-- name: GetServerSetting :one
SELECT value FROM server_settings WHERE key = ?
`

func (q *Queries) GetServerSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getServerSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const upsertServerSetting = `-- name: UpsertServerSetting :exec
INSERT INTO server_settings (key, value, updated_by, updated_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(key) DO UPDATE
SET value = excluded.value,
    updated_by = excluded.updated_by,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertServerSettingParams struct {
	Key       string        `json:"key"`
	Value     string        `json:"value"`
	UpdatedBy sql.NullInt64 `json:"updated_by"`
}

func (q *Queries) UpsertServerSetting(ctx context.Context, arg UpsertServerSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertServerSetting, arg.Key, arg.Value, arg.UpdatedBy)
	return err
}
