// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_state.sql

package store

import (
	"context"
)

const deleteSessionState = `-- name: DeleteSessionState :exec
DELETE FROM session_state WHERE workspace_id = ? AND session_id = ?
`

type DeleteSessionStateParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	SessionID   string `json:"session_id"`
}

func (q *Queries) DeleteSessionState(ctx context.Context, arg DeleteSessionStateParams) error {
	_, err := q.db.ExecContext(ctx, deleteSessionState, arg.WorkspaceID, arg.SessionID)
	return err
}

const deleteWorkspaceSessionStates = `-- name: DeleteWorkspaceSessionStates :exec
DELETE FROM session_state WHERE workspace_id = ?
`

func (q *Queries) DeleteWorkspaceSessionStates(ctx context.Context, workspaceID int64) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspaceSessionStates, workspaceID)
	return err
}

const getSessionState = `-- name: GetSessionState :one
SELECT id, workspace_id, session_id, repo_states, last_user_msg, last_context_tokens, snapshot_at FROM session_state
WHERE workspace_id = ? AND session_id = ?
`

type GetSessionStateParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	SessionID   string `json:"session_id"`
}

func (q *Queries) GetSessionState(ctx context.Context, arg GetSessionStateParams) (SessionState, error) {
	row := q.db.QueryRowContext(ctx, getSessionState, arg.WorkspaceID, arg.SessionID)
	var i SessionState
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SessionID,
		&i.RepoStates,
		&i.LastUserMsg,
		&i.LastContextTokens,
		&i.SnapshotAt,
	)
	return i, err
}

const upsertSessionLastContextTokens = `-- name: UpsertSessionLastContextTokens :exec
INSERT INTO session_state (workspace_id, session_id, last_context_tokens, snapshot_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(workspace_id, session_id) DO UPDATE SET
    last_context_tokens = excluded.last_context_tokens,
    snapshot_at   = CURRENT_TIMESTAMP
`

type UpsertSessionLastContextTokensParams struct {
	WorkspaceID       int64  `json:"workspace_id"`
	SessionID         string `json:"session_id"`
	LastContextTokens int64  `json:"last_context_tokens"`
}

// Persist the session's last observed context-window occupancy (tokens) so
// the auto-compact heuristic survives agent/server restarts on long
// --resume conversations. Called once per completed turn.
func (q *Queries) UpsertSessionLastContextTokens(ctx context.Context, arg UpsertSessionLastContextTokensParams) error {
	_, err := q.db.ExecContext(ctx, upsertSessionLastContextTokens, arg.WorkspaceID, arg.SessionID, arg.LastContextTokens)
	return err
}

const upsertSessionState = `-- name: UpsertSessionState :exec
INSERT INTO session_state (workspace_id, session_id, repo_states, last_user_msg, snapshot_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(workspace_id, session_id) DO UPDATE SET
    repo_states   = excluded.repo_states,
    last_user_msg = excluded.last_user_msg,
    snapshot_at   = CURRENT_TIMESTAMP
`

type UpsertSessionStateParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	SessionID   string `json:"session_id"`
	RepoStates  string `json:"repo_states"`
	LastUserMsg string `json:"last_user_msg"`
}

func (q *Queries) UpsertSessionState(ctx context.Context, arg UpsertSessionStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertSessionState,
		arg.WorkspaceID,
		arg.SessionID,
		arg.RepoStates,
		arg.LastUserMsg,
	)
	return err
}
