// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_stats.sql

package store

import (
	"context"
	"strings"
)

const getWorkspaceStats = `-- name: GetWorkspaceStats :one
SELECT workspace_id, owner_type, owner_id, user_message_count, ai_message_count, interaction_count, total_turns, total_duration_ms, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, last_activity_at, updated_at FROM workspace_stats WHERE workspace_id = ?
`

func (q *Queries) GetWorkspaceStats(ctx context.Context, workspaceID int64) (WorkspaceStat, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceStats, workspaceID)
	var i WorkspaceStat
	err := row.Scan(
		&i.WorkspaceID,
		&i.OwnerType,
		&i.OwnerID,
		&i.UserMessageCount,
		&i.AiMessageCount,
		&i.InteractionCount,
		&i.TotalTurns,
		&i.TotalDurationMs,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheCreationTokens,
		&i.CacheReadTokens,
		&i.LastActivityAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrWorkspaceStatsUserMessage = `-- name: IncrWorkspaceStatsUserMessage :exec
INSERT INTO workspace_stats (workspace_id, owner_type, owner_id, user_message_count, last_activity_at, updated_at)
VALUES (?, ?, ?, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT(workspace_id) DO UPDATE SET
    user_message_count = workspace_stats.user_message_count + 1,
    last_activity_at   = CURRENT_TIMESTAMP,
    updated_at         = CURRENT_TIMESTAMP
`

type IncrWorkspaceStatsUserMessageParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	OwnerType   string `json:"owner_type"`
	OwnerID     int64  `json:"owner_id"`
}

func (q *Queries) IncrWorkspaceStatsUserMessage(ctx context.Context, arg IncrWorkspaceStatsUserMessageParams) error {
	_, err := q.db.ExecContext(ctx, incrWorkspaceStatsUserMessage, arg.WorkspaceID, arg.OwnerType, arg.OwnerID)
	return err
}

const listWorkspaceStatsForWorkspaces = `-- name: ListWorkspaceStatsForWorkspaces :many
SELECT workspace_id, owner_type, owner_id, user_message_count, ai_message_count, interaction_count, total_turns, total_duration_ms, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, last_activity_at, updated_at FROM workspace_stats
WHERE workspace_id IN (/*SLICE:workspace_ids*/?)
`

func (q *Queries) ListWorkspaceStatsForWorkspaces(ctx context.Context, workspaceIds []int64) ([]WorkspaceStat, error) {
	query := listWorkspaceStatsForWorkspaces
	var queryParams []interface{}
	if len(workspaceIds) > 0 {
		for _, v := range workspaceIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:workspace_ids*/?", strings.Repeat(",?", len(workspaceIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:workspace_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceStat{}
	for rows.Next() {
		var i WorkspaceStat
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.OwnerType,
			&i.OwnerID,
			&i.UserMessageCount,
			&i.AiMessageCount,
			&i.InteractionCount,
			&i.TotalTurns,
			&i.TotalDurationMs,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheCreationTokens,
			&i.CacheReadTokens,
			&i.LastActivityAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWorkspaceStatsAI = `-- name: UpsertWorkspaceStatsAI :exec
INSERT INTO workspace_stats (
    workspace_id, owner_type, owner_id,
    ai_message_count, interaction_count, total_turns, total_duration_ms,
    input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens,
    last_activity_at, updated_at
) VALUES (?, ?, ?, 1, 1, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT(workspace_id) DO UPDATE SET
    ai_message_count      = workspace_stats.ai_message_count + 1,
    interaction_count     = workspace_stats.interaction_count + 1,
    total_turns           = workspace_stats.total_turns + excluded.total_turns,
    total_duration_ms     = workspace_stats.total_duration_ms + excluded.total_duration_ms,
    input_tokens          = workspace_stats.input_tokens + excluded.input_tokens,
    output_tokens         = workspace_stats.output_tokens + excluded.output_tokens,
    cache_creation_tokens = workspace_stats.cache_creation_tokens + excluded.cache_creation_tokens,
    cache_read_tokens     = workspace_stats.cache_read_tokens + excluded.cache_read_tokens,
    last_activity_at      = CURRENT_TIMESTAMP,
    updated_at            = CURRENT_TIMESTAMP
`

type UpsertWorkspaceStatsAIParams struct {
	WorkspaceID         int64  `json:"workspace_id"`
	OwnerType           string `json:"owner_type"`
	OwnerID             int64  `json:"owner_id"`
	TotalTurns          int64  `json:"total_turns"`
	TotalDurationMs     int64  `json:"total_duration_ms"`
	InputTokens         int64  `json:"input_tokens"`
	OutputTokens        int64  `json:"output_tokens"`
	CacheCreationTokens int64  `json:"cache_creation_tokens"`
	CacheReadTokens     int64  `json:"cache_read_tokens"`
}

// Accumulate one AI ("done") interaction. owner_* set on first insert only.
func (q *Queries) UpsertWorkspaceStatsAI(ctx context.Context, arg UpsertWorkspaceStatsAIParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkspaceStatsAI,
		arg.WorkspaceID,
		arg.OwnerType,
		arg.OwnerID,
		arg.TotalTurns,
		arg.TotalDurationMs,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheCreationTokens,
		arg.CacheReadTokens,
	)
	return err
}
