// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_start_queue.sql

package store

import (
	"context"
)

const countQueuedForIssue = `-- name: CountQueuedForIssue :one
SELECT COUNT(*) FROM workspace_start_queue
WHERE issue_id = ? AND status = 'queued'
`

// Whether a specific issue is already queued (keeps re-dispatch idempotent).
func (q *Queries) CountQueuedForIssue(ctx context.Context, issueID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQueuedForIssue, issueID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQueuedForOwner = `-- name: CountQueuedForOwner :one
SELECT COUNT(*) FROM workspace_start_queue
WHERE owner_type = ? AND owner_id = ? AND status = 'queued'
`

type CountQueuedForOwnerParams struct {
	OwnerType string `json:"owner_type"`
	OwnerID   int64  `json:"owner_id"`
}

// Number of issues currently queued for an owner (used as the queue position).
func (q *Queries) CountQueuedForOwner(ctx context.Context, arg CountQueuedForOwnerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQueuedForOwner, arg.OwnerType, arg.OwnerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dequeueNextForOwner = `-- name: DequeueNextForOwner :one
SELECT id, issue_id FROM workspace_start_queue
WHERE owner_type = ? AND owner_id = ? AND status = 'queued'
ORDER BY enqueued_at, id
LIMIT 1
`

type DequeueNextForOwnerParams struct {
	OwnerType string `json:"owner_type"`
	OwnerID   int64  `json:"owner_id"`
}

type DequeueNextForOwnerRow struct {
	ID      int64 `json:"id"`
	IssueID int64 `json:"issue_id"`
}

// Oldest queued entry for an owner, FIFO.
func (q *Queries) DequeueNextForOwner(ctx context.Context, arg DequeueNextForOwnerParams) (DequeueNextForOwnerRow, error) {
	row := q.db.QueryRowContext(ctx, dequeueNextForOwner, arg.OwnerType, arg.OwnerID)
	var i DequeueNextForOwnerRow
	err := row.Scan(&i.ID, &i.IssueID)
	return i, err
}

const enqueueWorkspaceStart = `-- name: EnqueueWorkspaceStart :exec
INSERT INTO workspace_start_queue (owner_type, owner_id, issue_id, status)
VALUES (?, ?, ?, 'queued')
`

type EnqueueWorkspaceStartParams struct {
	OwnerType string `json:"owner_type"`
	OwnerID   int64  `json:"owner_id"`
	IssueID   int64  `json:"issue_id"`
}

// Append an issue to an owner's start-overflow queue.
func (q *Queries) EnqueueWorkspaceStart(ctx context.Context, arg EnqueueWorkspaceStartParams) error {
	_, err := q.db.ExecContext(ctx, enqueueWorkspaceStart, arg.OwnerType, arg.OwnerID, arg.IssueID)
	return err
}

const listOwnersWithQueuedStarts = `-- name: ListOwnersWithQueuedStarts :many
SELECT DISTINCT owner_type, owner_id FROM workspace_start_queue
WHERE status = 'queued'
`

type ListOwnersWithQueuedStartsRow struct {
	OwnerType string `json:"owner_type"`
	OwnerID   int64  `json:"owner_id"`
}

// Distinct owners that currently have at least one queued start entry. Drives a
// global drain when the concurrency cap is raised or removed, so freed capacity
// is used immediately instead of waiting for the next workspace-completion event.
func (q *Queries) ListOwnersWithQueuedStarts(ctx context.Context) ([]ListOwnersWithQueuedStartsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOwnersWithQueuedStarts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnersWithQueuedStartsRow{}
	for rows.Next() {
		var i ListOwnersWithQueuedStartsRow
		if err := rows.Scan(&i.OwnerType, &i.OwnerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStartQueueCanceled = `-- name: MarkStartQueueCanceled :exec
UPDATE workspace_start_queue
SET status = 'canceled'
WHERE id = ?
`

func (q *Queries) MarkStartQueueCanceled(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markStartQueueCanceled, id)
	return err
}

const markStartQueueStarted = `-- name: MarkStartQueueStarted :exec
UPDATE workspace_start_queue
SET status = 'started', started_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) MarkStartQueueStarted(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markStartQueueStarted, id)
	return err
}
