// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_env.sql

package store

import (
	"context"
)

const deleteAllWorkspaceEnv = `-- name: DeleteAllWorkspaceEnv :exec
DELETE FROM workspace_env WHERE workspace_id = ?
`

func (q *Queries) DeleteAllWorkspaceEnv(ctx context.Context, workspaceID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAllWorkspaceEnv, workspaceID)
	return err
}

const deleteWorkspaceEnv = `-- name: DeleteWorkspaceEnv :exec
DELETE FROM workspace_env WHERE workspace_id = ? AND key = ?
`

type DeleteWorkspaceEnvParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	Key         string `json:"key"`
}

func (q *Queries) DeleteWorkspaceEnv(ctx context.Context, arg DeleteWorkspaceEnvParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspaceEnv, arg.WorkspaceID, arg.Key)
	return err
}

const getWorkspaceEnv = `-- name: GetWorkspaceEnv :many
SELECT id, workspace_id, "key", value, created_at, updated_at FROM workspace_env WHERE workspace_id = ? AND key = ?
`

type GetWorkspaceEnvParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	Key         string `json:"key"`
}

func (q *Queries) GetWorkspaceEnv(ctx context.Context, arg GetWorkspaceEnvParams) ([]WorkspaceEnv, error) {
	rows, err := q.db.QueryContext(ctx, getWorkspaceEnv, arg.WorkspaceID, arg.Key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceEnv{}
	for rows.Next() {
		var i WorkspaceEnv
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceEnv = `-- name: ListWorkspaceEnv :many
SELECT id, workspace_id, "key", value, created_at, updated_at FROM workspace_env WHERE workspace_id = ? ORDER BY key
`

func (q *Queries) ListWorkspaceEnv(ctx context.Context, workspaceID int64) ([]WorkspaceEnv, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceEnv, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceEnv{}
	for rows.Next() {
		var i WorkspaceEnv
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWorkspaceEnv = `-- name: SetWorkspaceEnv :exec
INSERT INTO workspace_env (workspace_id, key, value) VALUES (?, ?, ?)
ON CONFLICT(workspace_id, key) DO UPDATE SET value = excluded.value, updated_at = CURRENT_TIMESTAMP
`

type SetWorkspaceEnvParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	Key         string `json:"key"`
	Value       string `json:"value"`
}

func (q *Queries) SetWorkspaceEnv(ctx context.Context, arg SetWorkspaceEnvParams) error {
	_, err := q.db.ExecContext(ctx, setWorkspaceEnv, arg.WorkspaceID, arg.Key, arg.Value)
	return err
}
