// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const archiveWorkspace = `-- name: ArchiveWorkspace :exec
UPDATE workspaces SET is_archived = 1, archived_at = CURRENT_TIMESTAMP, path = '', updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) ArchiveWorkspace(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, archiveWorkspace, id)
	return err
}

const countSchedulesByWorkspace = `-- name: CountSchedulesByWorkspace :many
SELECT workspace_id, COUNT(*) AS count
FROM workspace_schedules
WHERE enabled = 1
GROUP BY workspace_id
`

type CountSchedulesByWorkspaceRow struct {
	WorkspaceID int64 `json:"workspace_id"`
	Count       int64 `json:"count"`
}

func (q *Queries) CountSchedulesByWorkspace(ctx context.Context) ([]CountSchedulesByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, countSchedulesByWorkspace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountSchedulesByWorkspaceRow{}
	for rows.Next() {
		var i CountSchedulesByWorkspaceRow
		if err := rows.Scan(&i.WorkspaceID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (issue_id, name, path, status, owner_type, owner_id, created_by, cli_type, codex_sandbox_mode, codex_approval_policy, language)
VALUES (?, ?, ?, ?, ?, ?, ?, COALESCE(NULLIF(CAST(?8 AS TEXT), ''), 'claude'), 'danger-full-access', 'never', CAST(?9 AS TEXT))
RETURNING id, issue_id, name, path, status, agent_pid, agent_status, session_id, session_status, owner_type, owner_id, current_session_user_id, created_by, created_at, updated_at, is_temporary, is_archived, archived_at, claude_account_id, mcp_servers, cli_type, codex_account_id, codex_sandbox_mode, codex_approval_policy, is_studio, strict_mcp_config, language
`

type CreateWorkspaceParams struct {
	IssueID   sql.NullInt64 `json:"issue_id"`
	Name      string        `json:"name"`
	Path      string        `json:"path"`
	Status    string        `json:"status"`
	OwnerType string        `json:"owner_type"`
	OwnerID   int64         `json:"owner_id"`
	CreatedBy sql.NullInt64 `json:"created_by"`
	CliType   string        `json:"cli_type"`
	Language  string        `json:"language"`
}

// Default empty cli_type to 'claude' so callers that omit it (existing tests
// and back-compat code paths) still satisfy the CHECK (cli_type IN
// ('claude','codex')) constraint. Explicit 'claude' or 'codex' bypasses the
// COALESCE branch and hits the CHECK directly.
// CAST(... AS TEXT) anchors the parameter type for sqlc generation and for
// the PG parser so this query does not trip SQLSTATE 42P18 on Postgres
// (see CLAUDE.md "Known PG-on-server pitfalls").
// sqlc.arg(cli_type) is safe here because ConvertPlaceholders (in
// store/pgplaceholder.go) recognizes the `?N` numbered form sqlc emits and
// rewrites it to `$N` without leaking the trailing digit. See the comment
// on ConvertPlaceholders for the failure mode that motivated that fix.
//
// codex_sandbox_mode/codex_approval_policy are written as literals here
// because legacy SQLite installs added these columns via ALTER TABLE with
// the OLD defaults ('workspace-write'/'on-failure'). SQLite does not
// support changing a column's DEFAULT after the fact, so relying on the
// schema DEFAULT would silently give new codex workspaces the old (and
// now wrong) sandbox/approval combo until the next server restart fires
// the post-startup UPDATE in addWorkspaceCodexSandboxColumns. Writing the
// literals here removes that startup-window race so newly created codex
// workspaces immediately get the correct danger-full-access/never combo.
// Claude workspaces ignore these columns, so the literals are harmless
// there.
func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspace,
		arg.IssueID,
		arg.Name,
		arg.Path,
		arg.Status,
		arg.OwnerType,
		arg.OwnerID,
		arg.CreatedBy,
		arg.CliType,
		arg.Language,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Name,
		&i.Path,
		&i.Status,
		&i.AgentPid,
		&i.AgentStatus,
		&i.SessionID,
		&i.SessionStatus,
		&i.OwnerType,
		&i.OwnerID,
		&i.CurrentSessionUserID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsTemporary,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.ClaudeAccountID,
		&i.McpServers,
		&i.CliType,
		&i.CodexAccountID,
		&i.CodexSandboxMode,
		&i.CodexApprovalPolicy,
		&i.IsStudio,
		&i.StrictMcpConfig,
		&i.Language,
	)
	return i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces WHERE id = ?
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspace, id)
	return err
}

const getProjectIDForWorkspace = `-- name: GetProjectIDForWorkspace :one
SELECT c.project_id FROM workspaces w
JOIN issues i ON w.issue_id = i.id
JOIN columns c ON i.column_id = c.id
WHERE w.id = ?
`

func (q *Queries) GetProjectIDForWorkspace(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getProjectIDForWorkspace, id)
	var project_id int64
	err := row.Scan(&project_id)
	return project_id, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, issue_id, name, path, status, agent_pid, agent_status, session_id, session_status, owner_type, owner_id, current_session_user_id, created_by, created_at, updated_at, is_temporary, is_archived, archived_at, claude_account_id, mcp_servers, cli_type, codex_account_id, codex_sandbox_mode, codex_approval_policy, is_studio, strict_mcp_config, language FROM workspaces WHERE id = ?
`

func (q *Queries) GetWorkspace(ctx context.Context, id int64) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Name,
		&i.Path,
		&i.Status,
		&i.AgentPid,
		&i.AgentStatus,
		&i.SessionID,
		&i.SessionStatus,
		&i.OwnerType,
		&i.OwnerID,
		&i.CurrentSessionUserID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsTemporary,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.ClaudeAccountID,
		&i.McpServers,
		&i.CliType,
		&i.CodexAccountID,
		&i.CodexSandboxMode,
		&i.CodexApprovalPolicy,
		&i.IsStudio,
		&i.StrictMcpConfig,
		&i.Language,
	)
	return i, err
}

const getWorkspaceAlertableUserIDs = `-- name: GetWorkspaceAlertableUserIDs :many
SELECT DISTINCT user_id FROM (
    SELECT created_by AS user_id FROM workspaces w
    WHERE w.id = ?1 AND created_by IS NOT NULL
    UNION
    SELECT ia.user_id FROM issue_assignees ia
    JOIN workspaces w ON w.issue_id = ia.issue_id
    WHERE w.id = ?1
) sub
`

// Returns the deduplicated, NULL-dropped union of:
//   - workspaces.created_by (if non-NULL)
//   - issue_assignees.user_id where issue_id matches the workspace's linked issue
//
// Used by emit sites of workspace-targeted toast events to populate
// extra.should_alert_user_ids.
func (q *Queries) GetWorkspaceAlertableUserIDs(ctx context.Context, workspaceID int64) ([]sql.NullInt64, error) {
	rows, err := q.db.QueryContext(ctx, getWorkspaceAlertableUserIDs, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullInt64{}
	for rows.Next() {
		var user_id sql.NullInt64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceCliType = `-- name: GetWorkspaceCliType :one
SELECT cli_type FROM workspaces WHERE id = ?
`

func (q *Queries) GetWorkspaceCliType(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceCliType, id)
	var cli_type string
	err := row.Scan(&cli_type)
	return cli_type, err
}

const getWorkspacesByIssue = `-- name: GetWorkspacesByIssue :many
SELECT id, issue_id, name, path, status, agent_pid, agent_status, session_id, session_status, owner_type, owner_id, current_session_user_id, created_by, created_at, updated_at, is_temporary, is_archived, archived_at, claude_account_id, mcp_servers, cli_type, codex_account_id, codex_sandbox_mode, codex_approval_policy, is_studio, strict_mcp_config, language FROM workspaces WHERE issue_id = ? ORDER BY is_archived ASC, created_at DESC
`

func (q *Queries) GetWorkspacesByIssue(ctx context.Context, issueID sql.NullInt64) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, getWorkspacesByIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Name,
			&i.Path,
			&i.Status,
			&i.AgentPid,
			&i.AgentStatus,
			&i.SessionID,
			&i.SessionStatus,
			&i.OwnerType,
			&i.OwnerID,
			&i.CurrentSessionUserID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsTemporary,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.ClaudeAccountID,
			&i.McpServers,
			&i.CliType,
			&i.CodexAccountID,
			&i.CodexSandboxMode,
			&i.CodexApprovalPolicy,
			&i.IsStudio,
			&i.StrictMcpConfig,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchivedWorkspaces = `-- name: ListArchivedWorkspaces :many
SELECT id, issue_id, name, path, status, agent_pid, agent_status, session_id, session_status, owner_type, owner_id, current_session_user_id, created_by, created_at, updated_at, is_temporary, is_archived, archived_at, claude_account_id, mcp_servers, cli_type, codex_account_id, codex_sandbox_mode, codex_approval_policy, is_studio, strict_mcp_config, language FROM workspaces WHERE is_archived = 1 ORDER BY archived_at DESC
`

func (q *Queries) ListArchivedWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listArchivedWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Name,
			&i.Path,
			&i.Status,
			&i.AgentPid,
			&i.AgentStatus,
			&i.SessionID,
			&i.SessionStatus,
			&i.OwnerType,
			&i.OwnerID,
			&i.CurrentSessionUserID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsTemporary,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.ClaudeAccountID,
			&i.McpServers,
			&i.CliType,
			&i.CodexAccountID,
			&i.CodexSandboxMode,
			&i.CodexApprovalPolicy,
			&i.IsStudio,
			&i.StrictMcpConfig,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchivedWorkspacesWithMeta = `-- name: ListArchivedWorkspacesWithMeta :many
SELECT w.id, w.issue_id, w.name, w.path, w.status, w.agent_pid, w.agent_status, w.session_id, w.session_status, w.owner_type, w.owner_id, w.current_session_user_id, w.created_by, w.created_at, w.updated_at, w.is_temporary, w.is_archived, w.archived_at, w.claude_account_id, w.mcp_servers, w.cli_type, w.codex_account_id, w.codex_sandbox_mode, w.codex_approval_policy, w.is_studio, w.strict_mcp_config, w.language,
  COALESCE(i.title, '') AS issue_title,
  COALESCE(p.name, '') AS project_name
FROM workspaces w
LEFT JOIN issues i ON w.issue_id = i.id
LEFT JOIN columns c ON i.column_id = c.id
LEFT JOIN projects p ON c.project_id = p.id
WHERE w.is_archived = 1
ORDER BY w.archived_at DESC
`

type ListArchivedWorkspacesWithMetaRow struct {
	ID                   int64          `json:"id"`
	IssueID              sql.NullInt64  `json:"issue_id"`
	Name                 string         `json:"name"`
	Path                 string         `json:"path"`
	Status               string         `json:"status"`
	AgentPid             sql.NullInt64  `json:"agent_pid"`
	AgentStatus          sql.NullString `json:"agent_status"`
	SessionID            sql.NullString `json:"session_id"`
	SessionStatus        sql.NullString `json:"session_status"`
	OwnerType            string         `json:"owner_type"`
	OwnerID              int64          `json:"owner_id"`
	CurrentSessionUserID sql.NullInt64  `json:"current_session_user_id"`
	CreatedBy            sql.NullInt64  `json:"created_by"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	IsTemporary          int64          `json:"is_temporary"`
	IsArchived           int64          `json:"is_archived"`
	ArchivedAt           sql.NullTime   `json:"archived_at"`
	ClaudeAccountID      sql.NullInt64  `json:"claude_account_id"`
	McpServers           string         `json:"mcp_servers"`
	CliType              string         `json:"cli_type"`
	CodexAccountID       sql.NullInt64  `json:"codex_account_id"`
	CodexSandboxMode     string         `json:"codex_sandbox_mode"`
	CodexApprovalPolicy  string         `json:"codex_approval_policy"`
	IsStudio             int64          `json:"is_studio"`
	StrictMcpConfig      int64          `json:"strict_mcp_config"`
	Language             string         `json:"language"`
	IssueTitle           string         `json:"issue_title"`
	ProjectName          string         `json:"project_name"`
}

func (q *Queries) ListArchivedWorkspacesWithMeta(ctx context.Context) ([]ListArchivedWorkspacesWithMetaRow, error) {
	rows, err := q.db.QueryContext(ctx, listArchivedWorkspacesWithMeta)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArchivedWorkspacesWithMetaRow{}
	for rows.Next() {
		var i ListArchivedWorkspacesWithMetaRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Name,
			&i.Path,
			&i.Status,
			&i.AgentPid,
			&i.AgentStatus,
			&i.SessionID,
			&i.SessionStatus,
			&i.OwnerType,
			&i.OwnerID,
			&i.CurrentSessionUserID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsTemporary,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.ClaudeAccountID,
			&i.McpServers,
			&i.CliType,
			&i.CodexAccountID,
			&i.CodexSandboxMode,
			&i.CodexApprovalPolicy,
			&i.IsStudio,
			&i.StrictMcpConfig,
			&i.Language,
			&i.IssueTitle,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectPlansWithWorkspace = `-- name: ListProjectPlansWithWorkspace :many
SELECT i.id, i.title, i.column_id, w.id AS workspace_id
FROM issues i
JOIN columns c ON c.id = i.column_id
JOIN workspaces w ON w.id = (
    SELECT w2.id FROM workspaces w2 WHERE w2.issue_id = i.id
    ORDER BY w2.is_archived ASC, w2.created_at DESC LIMIT 1
)
WHERE c.project_id = ?
ORDER BY c.position, i.position
`

type ListProjectPlansWithWorkspaceRow struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	ColumnID    int64  `json:"column_id"`
	WorkspaceID int64  `json:"workspace_id"`
}

// One row per project issue that has a backing workspace, paired with its primary
// workspace id (non-archived newest, else archived newest), in a single statement.
// Replaces an N+1 (ListIssuesByProject then GetWorkspacesByIssue per issue) on the
// IM inbound / classifier / issues-list hot path. Order matches ListIssuesByProject
// (c.position, i.position) so the /use index numbering stays stable.
func (q *Queries) ListProjectPlansWithWorkspace(ctx context.Context, projectID int64) ([]ListProjectPlansWithWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectPlansWithWorkspace, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectPlansWithWorkspaceRow{}
	for rows.Next() {
		var i ListProjectPlansWithWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ColumnID,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectWorkspacesForCleanup = `-- name: ListProjectWorkspacesForCleanup :many
SELECT
    w.id               AS workspace_id,
    i.id               AS issue_id,
    w.agent_status     AS agent_status,
    w.session_status   AS session_status,
    w.updated_at       AS updated_at,
    i.lifecycle_status AS lifecycle_status,
    i.exec_status      AS exec_status,
    st.last_activity_at AS last_activity_at
FROM workspaces w
JOIN issues  i ON w.issue_id  = i.id
JOIN columns c ON i.column_id = c.id
LEFT JOIN workspace_stats st ON st.workspace_id = w.id
WHERE c.project_id = ?
  AND w.is_archived = 0
  AND w.status <> 'deleting'
`

type ListProjectWorkspacesForCleanupRow struct {
	WorkspaceID     int64          `json:"workspace_id"`
	IssueID         int64          `json:"issue_id"`
	AgentStatus     sql.NullString `json:"agent_status"`
	SessionStatus   sql.NullString `json:"session_status"`
	UpdatedAt       time.Time      `json:"updated_at"`
	LifecycleStatus string         `json:"lifecycle_status"`
	ExecStatus      string         `json:"exec_status"`
	LastActivityAt  sql.NullTime   `json:"last_activity_at"`
}

// Live (non-archived, not mid-delete) workspaces bound to an issue in a project,
// with the issue status pair and the last-activity signal, for auto-cleanup.
// last_activity_at is NULL when the workspace has had no AI/user interaction; the
// service falls back to updated_at in that case.
func (q *Queries) ListProjectWorkspacesForCleanup(ctx context.Context, projectID int64) ([]ListProjectWorkspacesForCleanupRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectWorkspacesForCleanup, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectWorkspacesForCleanupRow{}
	for rows.Next() {
		var i ListProjectWorkspacesForCleanupRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.IssueID,
			&i.AgentStatus,
			&i.SessionStatus,
			&i.UpdatedAt,
			&i.LifecycleStatus,
			&i.ExecStatus,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, issue_id, name, path, status, agent_pid, agent_status, session_id, session_status, owner_type, owner_id, current_session_user_id, created_by, created_at, updated_at, is_temporary, is_archived, archived_at, claude_account_id, mcp_servers, cli_type, codex_account_id, codex_sandbox_mode, codex_approval_policy, is_studio, strict_mcp_config, language FROM workspaces WHERE is_temporary = 0 AND is_archived = 0 ORDER BY created_at DESC
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Name,
			&i.Path,
			&i.Status,
			&i.AgentPid,
			&i.AgentStatus,
			&i.SessionID,
			&i.SessionStatus,
			&i.OwnerType,
			&i.OwnerID,
			&i.CurrentSessionUserID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsTemporary,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.ClaudeAccountID,
			&i.McpServers,
			&i.CliType,
			&i.CodexAccountID,
			&i.CodexSandboxMode,
			&i.CodexApprovalPolicy,
			&i.IsStudio,
			&i.StrictMcpConfig,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWorkspaceDeleting = `-- name: MarkWorkspaceDeleting :execrows
UPDATE workspaces SET status = 'deleting', updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND status != 'deleting'
`

// Atomic guard for async batch delete: flips status to 'deleting' only when the
// workspace is not already being deleted. The affected-row count is the dedup
// gate -- 0 rows means a concurrent (or repeated) request already claimed it, so
// the caller skips it instead of starting a second cleanup goroutine.
// status != 'deleting' anchors the parameter against the typed status column so
// PG infers its type at parse time (no SQLSTATE 42P18).
func (q *Queries) MarkWorkspaceDeleting(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, markWorkspaceDeleting, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setWorkspaceStudio = `-- name: SetWorkspaceStudio :exec
UPDATE workspaces SET is_studio = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type SetWorkspaceStudioParams struct {
	IsStudio int64 `json:"is_studio"`
	ID       int64 `json:"id"`
}

// is_studio = ? anchors the parameter against the typed is_studio column so PG
// can infer its type at parse time (no SQLSTATE 42P18).
func (q *Queries) SetWorkspaceStudio(ctx context.Context, arg SetWorkspaceStudioParams) error {
	_, err := q.db.ExecContext(ctx, setWorkspaceStudio, arg.IsStudio, arg.ID)
	return err
}

const updateAgentStatus = `-- name: UpdateAgentStatus :exec
UPDATE workspaces SET agent_pid = ?, agent_status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateAgentStatusParams struct {
	AgentPid    sql.NullInt64  `json:"agent_pid"`
	AgentStatus sql.NullString `json:"agent_status"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAgentStatus, arg.AgentPid, arg.AgentStatus, arg.ID)
	return err
}

const updateSessionColumns = `-- name: UpdateSessionColumns :exec
UPDATE workspaces
SET session_id = ?, session_status = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateSessionColumnsParams struct {
	SessionID     sql.NullString `json:"session_id"`
	SessionStatus sql.NullString `json:"session_status"`
	ID            int64          `json:"id"`
}

func (q *Queries) UpdateSessionColumns(ctx context.Context, arg UpdateSessionColumnsParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionColumns, arg.SessionID, arg.SessionStatus, arg.ID)
	return err
}

const updateWorkspaceMcpServers = `-- name: UpdateWorkspaceMcpServers :exec
UPDATE workspaces
SET mcp_servers = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateWorkspaceMcpServersParams struct {
	McpServers string `json:"mcp_servers"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateWorkspaceMcpServers(ctx context.Context, arg UpdateWorkspaceMcpServersParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkspaceMcpServers, arg.McpServers, arg.ID)
	return err
}

const updateWorkspaceName = `-- name: UpdateWorkspaceName :exec
UPDATE workspaces SET name = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateWorkspaceNameParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateWorkspaceName(ctx context.Context, arg UpdateWorkspaceNameParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkspaceName, arg.Name, arg.ID)
	return err
}

const updateWorkspacePath = `-- name: UpdateWorkspacePath :one
UPDATE workspaces SET path = ? WHERE id = ? RETURNING id, issue_id, name, path, status, agent_pid, agent_status, session_id, session_status, owner_type, owner_id, current_session_user_id, created_by, created_at, updated_at, is_temporary, is_archived, archived_at, claude_account_id, mcp_servers, cli_type, codex_account_id, codex_sandbox_mode, codex_approval_policy, is_studio, strict_mcp_config, language
`

type UpdateWorkspacePathParams struct {
	Path string `json:"path"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateWorkspacePath(ctx context.Context, arg UpdateWorkspacePathParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, updateWorkspacePath, arg.Path, arg.ID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Name,
		&i.Path,
		&i.Status,
		&i.AgentPid,
		&i.AgentStatus,
		&i.SessionID,
		&i.SessionStatus,
		&i.OwnerType,
		&i.OwnerID,
		&i.CurrentSessionUserID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsTemporary,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.ClaudeAccountID,
		&i.McpServers,
		&i.CliType,
		&i.CodexAccountID,
		&i.CodexSandboxMode,
		&i.CodexApprovalPolicy,
		&i.IsStudio,
		&i.StrictMcpConfig,
		&i.Language,
	)
	return i, err
}

const updateWorkspaceSessionUser = `-- name: UpdateWorkspaceSessionUser :exec
UPDATE workspaces SET current_session_user_id = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateWorkspaceSessionUserParams struct {
	CurrentSessionUserID sql.NullInt64 `json:"current_session_user_id"`
	ID                   int64         `json:"id"`
}

func (q *Queries) UpdateWorkspaceSessionUser(ctx context.Context, arg UpdateWorkspaceSessionUserParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkspaceSessionUser, arg.CurrentSessionUserID, arg.ID)
	return err
}

const updateWorkspaceStatus = `-- name: UpdateWorkspaceStatus :exec
UPDATE workspaces SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateWorkspaceStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateWorkspaceStatus(ctx context.Context, arg UpdateWorkspaceStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkspaceStatus, arg.Status, arg.ID)
	return err
}

const updateWorkspaceStatusConditional = `-- name: UpdateWorkspaceStatusConditional :exec
UPDATE workspaces SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND status = ?
`

type UpdateWorkspaceStatusConditionalParams struct {
	Status   string `json:"status"`
	ID       int64  `json:"id"`
	Status_2 string `json:"status_2"`
}

func (q *Queries) UpdateWorkspaceStatusConditional(ctx context.Context, arg UpdateWorkspaceStatusConditionalParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkspaceStatusConditional, arg.Status, arg.ID, arg.Status_2)
	return err
}

const updateWorkspaceStrictMCP = `-- name: UpdateWorkspaceStrictMCP :exec
UPDATE workspaces
SET strict_mcp_config = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateWorkspaceStrictMCPParams struct {
	StrictMcpConfig int64 `json:"strict_mcp_config"`
	ID              int64 `json:"id"`
}

func (q *Queries) UpdateWorkspaceStrictMCP(ctx context.Context, arg UpdateWorkspaceStrictMCPParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkspaceStrictMCP, arg.StrictMcpConfig, arg.ID)
	return err
}
