// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_scene_projection.sql

package store

import (
	"context"
)

const deleteProjection = `-- name: DeleteProjection :exec
DELETE FROM workspace_scene_projection WHERE workspace_id = ?
`

func (q *Queries) DeleteProjection(ctx context.Context, workspaceID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProjection, workspaceID)
	return err
}

const getProjection = `-- name: GetProjection :one
SELECT workspace_id, digest, projected_definition, missing_credentials, install_failures, hot_applied_at, restart_required, recomputed_at, dismissed_plugins FROM workspace_scene_projection WHERE workspace_id = ?
`

func (q *Queries) GetProjection(ctx context.Context, workspaceID int64) (WorkspaceSceneProjection, error) {
	row := q.db.QueryRowContext(ctx, getProjection, workspaceID)
	var i WorkspaceSceneProjection
	err := row.Scan(
		&i.WorkspaceID,
		&i.Digest,
		&i.ProjectedDefinition,
		&i.MissingCredentials,
		&i.InstallFailures,
		&i.HotAppliedAt,
		&i.RestartRequired,
		&i.RecomputedAt,
		&i.DismissedPlugins,
	)
	return i, err
}

const setDismissedPlugins = `-- name: SetDismissedPlugins :exec
UPDATE workspace_scene_projection SET dismissed_plugins = ? WHERE workspace_id = ?
`

type SetDismissedPluginsParams struct {
	DismissedPlugins string `json:"dismissed_plugins"`
	WorkspaceID      int64  `json:"workspace_id"`
}

// Overwrites the per-workspace dismissed plugin source list. Only touches the
// dismissed_plugins column so a concurrent UpsertProjection (recompute) does
// not clobber it, and vice versa. Requires the projection row to already
// exist (it does whenever the banner is showing).
func (q *Queries) SetDismissedPlugins(ctx context.Context, arg SetDismissedPluginsParams) error {
	_, err := q.db.ExecContext(ctx, setDismissedPlugins, arg.DismissedPlugins, arg.WorkspaceID)
	return err
}

const upsertProjection = `-- name: UpsertProjection :exec
INSERT INTO workspace_scene_projection
  (workspace_id, digest, projected_definition, missing_credentials,
   install_failures, restart_required, hot_applied_at, recomputed_at)
VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (workspace_id) DO UPDATE SET
  digest = excluded.digest,
  projected_definition = excluded.projected_definition,
  missing_credentials = excluded.missing_credentials,
  install_failures = excluded.install_failures,
  restart_required = excluded.restart_required,
  hot_applied_at = excluded.hot_applied_at,
  recomputed_at = CURRENT_TIMESTAMP
`

type UpsertProjectionParams struct {
	WorkspaceID         int64  `json:"workspace_id"`
	Digest              string `json:"digest"`
	ProjectedDefinition string `json:"projected_definition"`
	MissingCredentials  string `json:"missing_credentials"`
	InstallFailures     string `json:"install_failures"`
	RestartRequired     int64  `json:"restart_required"`
}

// Cached projection per workspace. PRIMARY KEY is workspace_id so a vanilla
// ON CONFLICT (workspace_id) DO UPDATE is sqlc-safe (no partial-index conflict
// target, unlike workspace_scene_layers; see InsertBaseLayer header).
func (q *Queries) UpsertProjection(ctx context.Context, arg UpsertProjectionParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjection,
		arg.WorkspaceID,
		arg.Digest,
		arg.ProjectedDefinition,
		arg.MissingCredentials,
		arg.InstallFailures,
		arg.RestartRequired,
	)
	return err
}
