// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_local_runner.sql

package store

import (
	"context"
)

const deleteWorkspaceLocalRunner = `-- name: DeleteWorkspaceLocalRunner :exec
DELETE FROM workspace_local_runner WHERE workspace_id = ?
`

func (q *Queries) DeleteWorkspaceLocalRunner(ctx context.Context, workspaceID int64) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspaceLocalRunner, workspaceID)
	return err
}

const getWorkspaceLocalRunner = `-- name: GetWorkspaceLocalRunner :one
SELECT workspace_id, local_dir, prompt_snippet, allowed_commands, always_allow_persist, created_at, updated_at FROM workspace_local_runner WHERE workspace_id = ?
`

func (q *Queries) GetWorkspaceLocalRunner(ctx context.Context, workspaceID int64) (WorkspaceLocalRunner, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceLocalRunner, workspaceID)
	var i WorkspaceLocalRunner
	err := row.Scan(
		&i.WorkspaceID,
		&i.LocalDir,
		&i.PromptSnippet,
		&i.AllowedCommands,
		&i.AlwaysAllowPersist,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWorkspaceLocalRunner = `-- name: UpsertWorkspaceLocalRunner :one
INSERT INTO workspace_local_runner (
    workspace_id, local_dir, prompt_snippet, allowed_commands, always_allow_persist, updated_at
) VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT (workspace_id) DO UPDATE SET
    local_dir = excluded.local_dir,
    prompt_snippet = excluded.prompt_snippet,
    allowed_commands = excluded.allowed_commands,
    always_allow_persist = excluded.always_allow_persist,
    updated_at = CURRENT_TIMESTAMP
RETURNING workspace_id, local_dir, prompt_snippet, allowed_commands, always_allow_persist, created_at, updated_at
`

type UpsertWorkspaceLocalRunnerParams struct {
	WorkspaceID        int64  `json:"workspace_id"`
	LocalDir           string `json:"local_dir"`
	PromptSnippet      string `json:"prompt_snippet"`
	AllowedCommands    string `json:"allowed_commands"`
	AlwaysAllowPersist int64  `json:"always_allow_persist"`
}

func (q *Queries) UpsertWorkspaceLocalRunner(ctx context.Context, arg UpsertWorkspaceLocalRunnerParams) (WorkspaceLocalRunner, error) {
	row := q.db.QueryRowContext(ctx, upsertWorkspaceLocalRunner,
		arg.WorkspaceID,
		arg.LocalDir,
		arg.PromptSnippet,
		arg.AllowedCommands,
		arg.AlwaysAllowPersist,
	)
	var i WorkspaceLocalRunner
	err := row.Scan(
		&i.WorkspaceID,
		&i.LocalDir,
		&i.PromptSnippet,
		&i.AllowedCommands,
		&i.AlwaysAllowPersist,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
