// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_pins.sql

package store

import (
	"context"
)

const listPinnedWorkspaceIDsForUser = `-- name: ListPinnedWorkspaceIDsForUser :many
SELECT workspace_id FROM workspace_pins WHERE user_id = ? ORDER BY pinned_at DESC, id DESC
`

// Ordered most-recently-pinned first, matching the sidebar pinned zone order.
func (q *Queries) ListPinnedWorkspaceIDsForUser(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listPinnedWorkspaceIDsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var workspace_id int64
		if err := rows.Scan(&workspace_id); err != nil {
			return nil, err
		}
		items = append(items, workspace_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pinWorkspace = `-- name: PinWorkspace :exec

INSERT INTO workspace_pins (user_id, workspace_id, pinned_at)
VALUES (?, ?, CURRENT_TIMESTAMP)
ON CONFLICT (user_id, workspace_id) DO UPDATE SET pinned_at = CURRENT_TIMESTAMP
`

type PinWorkspaceParams struct {
	UserID      int64 `json:"user_id"`
	WorkspaceID int64 `json:"workspace_id"`
}

// Per-user workspace pins for the overview page. All comments are pure ASCII
// (a stray non-ASCII byte silently truncates a later query -- see CLAUDE.md).
// Idempotent: re-pinning refreshes pinned_at so the row jumps to the top of
// the pinned section. user_id / workspace_id anchor the ON CONFLICT target.
func (q *Queries) PinWorkspace(ctx context.Context, arg PinWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, pinWorkspace, arg.UserID, arg.WorkspaceID)
	return err
}

const unpinWorkspace = `-- name: UnpinWorkspace :exec
DELETE FROM workspace_pins WHERE user_id = ? AND workspace_id = ?
`

type UnpinWorkspaceParams struct {
	UserID      int64 `json:"user_id"`
	WorkspaceID int64 `json:"workspace_id"`
}

func (q *Queries) UnpinWorkspace(ctx context.Context, arg UnpinWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, unpinWorkspace, arg.UserID, arg.WorkspaceID)
	return err
}
