// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_schedules.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const countEnabledSchedulesByWorkspace = `-- name: CountEnabledSchedulesByWorkspace :many
SELECT workspace_id, COUNT(*) AS count
FROM workspace_schedules
WHERE enabled = 1
GROUP BY workspace_id
`

type CountEnabledSchedulesByWorkspaceRow struct {
	WorkspaceID int64 `json:"workspace_id"`
	Count       int64 `json:"count"`
}

func (q *Queries) CountEnabledSchedulesByWorkspace(ctx context.Context) ([]CountEnabledSchedulesByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, countEnabledSchedulesByWorkspace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountEnabledSchedulesByWorkspaceRow{}
	for rows.Next() {
		var i CountEnabledSchedulesByWorkspaceRow
		if err := rows.Scan(&i.WorkspaceID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO workspace_schedules (workspace_id, name, default_message, schedule_type, cron_expr, run_at, action_kind)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, workspace_id, name, default_message, schedule_type, cron_expr, run_at, enabled, fired_at, last_run_at, action_kind, created_at, updated_at
`

type CreateScheduleParams struct {
	WorkspaceID    int64        `json:"workspace_id"`
	Name           string       `json:"name"`
	DefaultMessage string       `json:"default_message"`
	ScheduleType   string       `json:"schedule_type"`
	CronExpr       string       `json:"cron_expr"`
	RunAt          sql.NullTime `json:"run_at"`
	ActionKind     string       `json:"action_kind"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (WorkspaceSchedule, error) {
	row := q.db.QueryRowContext(ctx, createSchedule,
		arg.WorkspaceID,
		arg.Name,
		arg.DefaultMessage,
		arg.ScheduleType,
		arg.CronExpr,
		arg.RunAt,
		arg.ActionKind,
	)
	var i WorkspaceSchedule
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.DefaultMessage,
		&i.ScheduleType,
		&i.CronExpr,
		&i.RunAt,
		&i.Enabled,
		&i.FiredAt,
		&i.LastRunAt,
		&i.ActionKind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM workspace_schedules WHERE id = ?
`

func (q *Queries) DeleteSchedule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSchedule, id)
	return err
}

const disableSchedule = `-- name: DisableSchedule :exec
UPDATE workspace_schedules
SET enabled = 0, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) DisableSchedule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, disableSchedule, id)
	return err
}

const disableSchedulesByWorkspace = `-- name: DisableSchedulesByWorkspace :exec
UPDATE workspace_schedules
SET enabled = 0, updated_at = CURRENT_TIMESTAMP
WHERE workspace_id = ?
`

func (q *Queries) DisableSchedulesByWorkspace(ctx context.Context, workspaceID int64) error {
	_, err := q.db.ExecContext(ctx, disableSchedulesByWorkspace, workspaceID)
	return err
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, workspace_id, name, default_message, schedule_type, cron_expr, run_at, enabled, fired_at, last_run_at, action_kind, created_at, updated_at FROM workspace_schedules WHERE id = ?
`

func (q *Queries) GetSchedule(ctx context.Context, id int64) (WorkspaceSchedule, error) {
	row := q.db.QueryRowContext(ctx, getSchedule, id)
	var i WorkspaceSchedule
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.DefaultMessage,
		&i.ScheduleType,
		&i.CronExpr,
		&i.RunAt,
		&i.Enabled,
		&i.FiredAt,
		&i.LastRunAt,
		&i.ActionKind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllSchedulesWithWorkspace = `-- name: ListAllSchedulesWithWorkspace :many
SELECT ws.id, ws.workspace_id, ws.name, ws.default_message, ws.schedule_type, ws.cron_expr, ws.run_at, ws.enabled, ws.fired_at, ws.last_run_at, ws.action_kind, ws.created_at, ws.updated_at, w.name AS workspace_name, w.status AS workspace_status
FROM workspace_schedules ws
JOIN workspaces w ON w.id = ws.workspace_id
ORDER BY ws.workspace_id, ws.created_at ASC
`

type ListAllSchedulesWithWorkspaceRow struct {
	ID              int64        `json:"id"`
	WorkspaceID     int64        `json:"workspace_id"`
	Name            string       `json:"name"`
	DefaultMessage  string       `json:"default_message"`
	ScheduleType    string       `json:"schedule_type"`
	CronExpr        string       `json:"cron_expr"`
	RunAt           sql.NullTime `json:"run_at"`
	Enabled         int64        `json:"enabled"`
	FiredAt         sql.NullTime `json:"fired_at"`
	LastRunAt       sql.NullTime `json:"last_run_at"`
	ActionKind      string       `json:"action_kind"`
	CreatedAt       time.Time    `json:"created_at"`
	UpdatedAt       time.Time    `json:"updated_at"`
	WorkspaceName   string       `json:"workspace_name"`
	WorkspaceStatus string       `json:"workspace_status"`
}

func (q *Queries) ListAllSchedulesWithWorkspace(ctx context.Context) ([]ListAllSchedulesWithWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllSchedulesWithWorkspace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSchedulesWithWorkspaceRow{}
	for rows.Next() {
		var i ListAllSchedulesWithWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.DefaultMessage,
			&i.ScheduleType,
			&i.CronExpr,
			&i.RunAt,
			&i.Enabled,
			&i.FiredAt,
			&i.LastRunAt,
			&i.ActionKind,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkspaceName,
			&i.WorkspaceStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledSchedules = `-- name: ListEnabledSchedules :many
SELECT id, workspace_id, name, default_message, schedule_type, cron_expr, run_at, enabled, fired_at, last_run_at, action_kind, created_at, updated_at FROM workspace_schedules
WHERE enabled = 1
`

func (q *Queries) ListEnabledSchedules(ctx context.Context) ([]WorkspaceSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceSchedule{}
	for rows.Next() {
		var i WorkspaceSchedule
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.DefaultMessage,
			&i.ScheduleType,
			&i.CronExpr,
			&i.RunAt,
			&i.Enabled,
			&i.FiredAt,
			&i.LastRunAt,
			&i.ActionKind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, workspace_id, name, default_message, schedule_type, cron_expr, run_at, enabled, fired_at, last_run_at, action_kind, created_at, updated_at FROM workspace_schedules
WHERE workspace_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListSchedules(ctx context.Context, workspaceID int64) ([]WorkspaceSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedules, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceSchedule{}
	for rows.Next() {
		var i WorkspaceSchedule
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.DefaultMessage,
			&i.ScheduleType,
			&i.CronExpr,
			&i.RunAt,
			&i.Enabled,
			&i.FiredAt,
			&i.LastRunAt,
			&i.ActionKind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnfiredOnceSchedules = `-- name: ListUnfiredOnceSchedules :many
SELECT id, workspace_id, name, default_message, schedule_type, cron_expr, run_at, enabled, fired_at, last_run_at, action_kind, created_at, updated_at FROM workspace_schedules
WHERE enabled = 1 AND schedule_type = 'once' AND fired_at IS NULL
`

func (q *Queries) ListUnfiredOnceSchedules(ctx context.Context) ([]WorkspaceSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listUnfiredOnceSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceSchedule{}
	for rows.Next() {
		var i WorkspaceSchedule
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.DefaultMessage,
			&i.ScheduleType,
			&i.CronExpr,
			&i.RunAt,
			&i.Enabled,
			&i.FiredAt,
			&i.LastRunAt,
			&i.ActionKind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markScheduleFired = `-- name: MarkScheduleFired :exec
UPDATE workspace_schedules
SET fired_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) MarkScheduleFired(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markScheduleFired, id)
	return err
}

const markScheduleRan = `-- name: MarkScheduleRan :exec
UPDATE workspace_schedules
SET last_run_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) MarkScheduleRan(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markScheduleRan, id)
	return err
}

const pruneOrphanedWorkspaceSchedules = `-- name: PruneOrphanedWorkspaceSchedules :exec
DELETE FROM workspace_schedules WHERE workspace_id NOT IN (SELECT id FROM workspaces)
`

// Delete schedules whose workspace no longer exists (avoids FK errors from scheduler).
func (q *Queries) PruneOrphanedWorkspaceSchedules(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, pruneOrphanedWorkspaceSchedules)
	return err
}

const toggleSchedule = `-- name: ToggleSchedule :exec
UPDATE workspace_schedules
SET enabled = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type ToggleScheduleParams struct {
	Enabled int64 `json:"enabled"`
	ID      int64 `json:"id"`
}

func (q *Queries) ToggleSchedule(ctx context.Context, arg ToggleScheduleParams) error {
	_, err := q.db.ExecContext(ctx, toggleSchedule, arg.Enabled, arg.ID)
	return err
}

const updateSchedule = `-- name: UpdateSchedule :exec
UPDATE workspace_schedules
SET name = ?, default_message = ?, schedule_type = ?, cron_expr = ?, run_at = ?, action_kind = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateScheduleParams struct {
	Name           string       `json:"name"`
	DefaultMessage string       `json:"default_message"`
	ScheduleType   string       `json:"schedule_type"`
	CronExpr       string       `json:"cron_expr"`
	RunAt          sql.NullTime `json:"run_at"`
	ActionKind     string       `json:"action_kind"`
	ID             int64        `json:"id"`
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) error {
	_, err := q.db.ExecContext(ctx, updateSchedule,
		arg.Name,
		arg.DefaultMessage,
		arg.ScheduleType,
		arg.CronExpr,
		arg.RunAt,
		arg.ActionKind,
		arg.ID,
	)
	return err
}
