// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces_owner_filter.sql

package store

import (
	"context"
	"database/sql"
	"strings"
)

const listWorkspaceCreatorsForOwners = `-- name: ListWorkspaceCreatorsForOwners :many
SELECT DISTINCT u.id, u.username, u.display_name
FROM workspaces w
JOIN users u ON u.id = w.created_by
WHERE w.is_archived = 0
  AND w.created_by IS NOT NULL
  AND ((w.owner_type = 'user' AND w.owner_id = ?)
    OR (w.owner_type = 'org'  AND w.owner_id IN (/*SLICE:org_ids*/?)))
ORDER BY u.display_name, u.username
`

type ListWorkspaceCreatorsForOwnersParams struct {
	OwnerID int64   `json:"owner_id"`
	OrgIds  []int64 `json:"org_ids"`
}

type ListWorkspaceCreatorsForOwnersRow struct {
	ID          int64  `json:"id"`
	Username    string `json:"username"`
	DisplayName string `json:"display_name"`
}

// Distinct creators within the (owner_user_id, org_ids) scope; caller
// pre-narrows scope via authz to avoid cross-org identity leaks.
// Excludes NULL created_by (picker has no "unknown" option).
func (q *Queries) ListWorkspaceCreatorsForOwners(ctx context.Context, arg ListWorkspaceCreatorsForOwnersParams) ([]ListWorkspaceCreatorsForOwnersRow, error) {
	query := listWorkspaceCreatorsForOwners
	var queryParams []interface{}
	queryParams = append(queryParams, arg.OwnerID)
	if len(arg.OrgIds) > 0 {
		for _, v := range arg.OrgIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:org_ids*/?", strings.Repeat(",?", len(arg.OrgIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:org_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceCreatorsForOwnersRow{}
	for rows.Next() {
		var i ListWorkspaceCreatorsForOwnersRow
		if err := rows.Scan(&i.ID, &i.Username, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesForOwners = `-- name: ListWorkspacesForOwners :many
SELECT id, issue_id, name, path, status, agent_pid, agent_status, session_id, session_status, owner_type, owner_id, current_session_user_id, created_by, created_at, updated_at, is_temporary, is_archived, archived_at, claude_account_id, mcp_servers, cli_type, codex_account_id, codex_sandbox_mode, codex_approval_policy, is_studio, strict_mcp_config, language FROM workspaces
WHERE is_archived = 0
  AND ((owner_type = 'user' AND owner_id = ?)
    OR (owner_type = 'org'  AND owner_id IN (/*SLICE:org_ids*/?)))
  AND (
        ? = 0
     OR created_by = ?
     OR (
          created_by IS NULL
          AND owner_type = 'user'
          AND owner_id = ?
        )
  )
ORDER BY created_at DESC
`

type ListWorkspacesForOwnersParams struct {
	OwnerID   int64         `json:"owner_id"`
	OrgIds    []int64       `json:"org_ids"`
	Column3   interface{}   `json:"column_3"`
	CreatedBy sql.NullInt64 `json:"created_by"`
	OwnerID_2 int64         `json:"owner_id_2"`
}

// Workspaces accessible to caller (personal + member orgs).
// The ? = 0 sentinel avoids the 42P18 parameter-typing issue on Postgres
// while keeping a single cross-dialect query: when the creator filter is 0
// (no filter), ? = 0 evaluates to TRUE and the entire AND-group is a no-op.
// When the filter is set (cid > 0), ? = 0 is FALSE, and the remaining
// branches (created_by = ? and the legacy-NULL fallback) are tested.
func (q *Queries) ListWorkspacesForOwners(ctx context.Context, arg ListWorkspacesForOwnersParams) ([]Workspace, error) {
	query := listWorkspacesForOwners
	var queryParams []interface{}
	queryParams = append(queryParams, arg.OwnerID)
	if len(arg.OrgIds) > 0 {
		for _, v := range arg.OrgIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:org_ids*/?", strings.Repeat(",?", len(arg.OrgIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:org_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Column3)
	queryParams = append(queryParams, arg.CreatedBy)
	queryParams = append(queryParams, arg.OwnerID_2)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Name,
			&i.Path,
			&i.Status,
			&i.AgentPid,
			&i.AgentStatus,
			&i.SessionID,
			&i.SessionStatus,
			&i.OwnerType,
			&i.OwnerID,
			&i.CurrentSessionUserID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsTemporary,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.ClaudeAccountID,
			&i.McpServers,
			&i.CliType,
			&i.CodexAccountID,
			&i.CodexSandboxMode,
			&i.CodexApprovalPolicy,
			&i.IsStudio,
			&i.StrictMcpConfig,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
