// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_kbs.sql

package store

import (
	"context"
	"time"
)

const createWorkspaceKB = `-- name: CreateWorkspaceKB :one
INSERT INTO workspace_kbs (workspace_id, kb_id, dataset_path)
VALUES (?, ?, ?) RETURNING id, workspace_id, kb_id, dataset_path, created_at
`

type CreateWorkspaceKBParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	KbID        int64  `json:"kb_id"`
	DatasetPath string `json:"dataset_path"`
}

// Records an explicit workspace -> KB mount. Unique per (workspace, kb); the
// dataset_path is the read-only materialized dir inside the workspace tree.
func (q *Queries) CreateWorkspaceKB(ctx context.Context, arg CreateWorkspaceKBParams) (WorkspaceKb, error) {
	row := q.db.QueryRowContext(ctx, createWorkspaceKB, arg.WorkspaceID, arg.KbID, arg.DatasetPath)
	var i WorkspaceKb
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.KbID,
		&i.DatasetPath,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorkspaceKBByWorkspaceAndKB = `-- name: DeleteWorkspaceKBByWorkspaceAndKB :exec
DELETE FROM workspace_kbs WHERE workspace_id = ? AND kb_id = ?
`

type DeleteWorkspaceKBByWorkspaceAndKBParams struct {
	WorkspaceID int64 `json:"workspace_id"`
	KbID        int64 `json:"kb_id"`
}

func (q *Queries) DeleteWorkspaceKBByWorkspaceAndKB(ctx context.Context, arg DeleteWorkspaceKBByWorkspaceAndKBParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspaceKBByWorkspaceAndKB, arg.WorkspaceID, arg.KbID)
	return err
}

const getWorkspaceKB = `-- name: GetWorkspaceKB :one
SELECT id, workspace_id, kb_id, dataset_path, created_at FROM workspace_kbs WHERE workspace_id = ? AND kb_id = ?
`

type GetWorkspaceKBParams struct {
	WorkspaceID int64 `json:"workspace_id"`
	KbID        int64 `json:"kb_id"`
}

func (q *Queries) GetWorkspaceKB(ctx context.Context, arg GetWorkspaceKBParams) (WorkspaceKb, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceKB, arg.WorkspaceID, arg.KbID)
	var i WorkspaceKb
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.KbID,
		&i.DatasetPath,
		&i.CreatedAt,
	)
	return i, err
}

const listMountedKBsForWorkspace = `-- name: ListMountedKBsForWorkspace :many
SELECT kb.id, kb.name, kb.description, kb.source_kind, kb.source_addr, kb.status,
       wk.dataset_path, wk.created_at
FROM workspace_kbs wk
JOIN knowledge_bases kb ON kb.id = wk.kb_id
WHERE wk.workspace_id = ?
  AND kb.owner_type = ?
  AND kb.owner_id = ?
  AND kb.status <> 'disabled'
ORDER BY wk.created_at ASC
`

type ListMountedKBsForWorkspaceParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	OwnerType   string `json:"owner_type"`
	OwnerID     int64  `json:"owner_id"`
}

type ListMountedKBsForWorkspaceRow struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	SourceKind  string    `json:"source_kind"`
	SourceAddr  string    `json:"source_addr"`
	Status      string    `json:"status"`
	DatasetPath string    `json:"dataset_path"`
	CreatedAt   time.Time `json:"created_at"`
}

// KBs explicitly mounted to a workspace, joined with their dataset_path so the
// service can expose the read-only dir (and fall back to project-bound KBs when
// a workspace has no explicit mounts). owner_type/owner_id enforce tenant
// isolation; a disabled KB is excluded so disabling stops both kb_search and
// the agent direct-read mount.
func (q *Queries) ListMountedKBsForWorkspace(ctx context.Context, arg ListMountedKBsForWorkspaceParams) ([]ListMountedKBsForWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listMountedKBsForWorkspace, arg.WorkspaceID, arg.OwnerType, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMountedKBsForWorkspaceRow{}
	for rows.Next() {
		var i ListMountedKBsForWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SourceKind,
			&i.SourceAddr,
			&i.Status,
			&i.DatasetPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceKBsForWorkspace = `-- name: ListWorkspaceKBsForWorkspace :many
SELECT id, workspace_id, kb_id, dataset_path, created_at FROM workspace_kbs WHERE workspace_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListWorkspaceKBsForWorkspace(ctx context.Context, workspaceID int64) ([]WorkspaceKb, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceKBsForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceKb{}
	for rows.Next() {
		var i WorkspaceKb
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.KbID,
			&i.DatasetPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
