/**
 * pairedDesktopsStore — persisted list of desktops paired to this mobile.
 *
 * Import-cycle invariant: this module imports `useTransportStore` as a
 * value (for cross-store cleanup inside `removeDesktop`) and is itself
 * runtime-imported by `relayAccountStore` (for `clearAll` on logout).
 * Do NOT runtime-import `relayAccountStore` from here — that would create
 * a cycle Metro resolves by returning `undefined` on the late side. Use
 * `import type` only if an account type is ever needed.
 */
import { useEffect, useState } from 'react';
import { create } from 'zustand';
import { createJSONStorage, persist } from 'zustand/middleware';
import * as SecureStore from 'expo-secure-store';
import { useTransportStore } from './transportStore';

// SecureStore on Android requires keys to match ^[\w.-]+$ — no colons.
const PAIRED_DESKTOPS_KEY = 'niuniu.paired-desktops';

// ─── Secure-store backed JSON storage ────────────────────────────────────────

const secureStorage = {
  getItem: async (name: string): Promise<string | null> => {
    return SecureStore.getItemAsync(name);
  },
  setItem: async (name: string, value: string): Promise<void> => {
    await SecureStore.setItemAsync(name, value);
  },
  removeItem: async (name: string): Promise<void> => {
    await SecureStore.deleteItemAsync(name);
  },
};

// ─── Types ───────────────────────────────────────────────────────────────────

/** A known LAN endpoint for a paired desktop, cached from previous successful connections. */
export interface LanEndpoint {
  host: string;
  port: number;
  /** Unix timestamp (ms) of the last successful LAN connection via this endpoint. */
  lastSeen: number;
}

export interface PairedDesktop {
  desktopId: string;
  desktopName: string;
  /** Base64-encoded X25519 public key */
  xpub: string;
  /** Base64-encoded Ed25519 public key */
  signPub: string;
  /** Opaque relay device token for authenticating tunnel requests */
  relayDeviceToken: string;
  /** The mobile device ID assigned by the relay during pairing */
  mobileId?: string;
  /**
   * Base64-encoded 32-byte ChaCha20-Poly1305 key generated by the relay
   * at scan-pairing time and returned via the claim long-poll. Each
   * (mobile, desktop) pair gets a fresh independent key; re-pair
   * supersedes it. Empty for pairings established before the relay
   * shipped pair_key (older pairings fall back to noise / plaintext).
   */
  pairKey?: string;
  pairedAt: string; // ISO date string
  /**
   * Recently-seen LAN endpoints for this desktop, most-recent first.
   * Populated on each successful LAN probe; capped at 3 entries.
   * Cleared when the desktop is unpaired.
   */
  lastKnownLanEndpoints?: LanEndpoint[];
}

interface PairedDesktopsState {
  desktops: PairedDesktop[];

  addDesktop: (desktop: PairedDesktop) => void;
  removeDesktop: (desktopId: string) => void;
  updateDesktop: (desktopId: string, updates: Partial<PairedDesktop>) => void;
  getDesktop: (desktopId: string) => PairedDesktop | undefined;
  clearAll: () => void;
  /**
   * Records a successful LAN endpoint for the given desktop.
   * Inserts at the front, de-duplicates by host+port, caps at 3 entries.
   */
  recordLanEndpoint: (desktopId: string, endpoint: { host: string; port: number }) => void;
}

// ─── Store ───────────────────────────────────────────────────────────────────

export const usePairedDesktopsStore = create<PairedDesktopsState>()(
  persist(
    (set, get) => ({
      desktops: [],

      addDesktop: (desktop) => {
        set((state) => {
          // Upsert: replace existing entry for same desktopId
          const filtered = state.desktops.filter(
            (d) => d.desktopId !== desktop.desktopId,
          );
          return { desktops: [...filtered, desktop] };
        });
      },

      removeDesktop: (desktopId) => {
        set((state) => ({
          desktops: state.desktops.filter((d) => d.desktopId !== desktopId),
        }));
        // Cross-store cleanup for unpair:
        //   • If the removed desktop was the active transport target,
        //     clear the persisted choice so the next cold start routes
        //     to the picker instead of tabs with a gone desktop id.
        //   • Tear down the cached cipher and close the cached LAN
        //     handle so *new* requests can't resurrect a stale session.
        // Contract: in-flight relay/LAN requests to this desktop are
        // considered cancelled by unpair. smartFetch in apiClient.ts
        // already catches LAN RPC failures and falls back to the relay
        // path; an in-flight relay call will surface a tunnel-closed
        // error to its caller, which is the correct outcome for an
        // unpair the user just initiated.
        const transport = useTransportStore.getState();
        if (transport.activeDesktopId === desktopId) {
          transport.resetActiveTransport();
        }
        transport.removeCipher(desktopId);
        transport.removeLanHandle(desktopId);
      },

      updateDesktop: (desktopId, updates) => {
        set((state) => ({
          desktops: state.desktops.map((d) =>
            d.desktopId === desktopId ? { ...d, ...updates } : d,
          ),
        }));
      },

      getDesktop: (desktopId) => {
        return get().desktops.find((d) => d.desktopId === desktopId);
      },

      clearAll: () => {
        set({ desktops: [] });
      },

      recordLanEndpoint: (desktopId, { host, port }) => {
        set((state) => ({
          desktops: state.desktops.map((d) => {
            if (d.desktopId !== desktopId) return d;
            const newEntry: LanEndpoint = { host, port, lastSeen: Date.now() };
            const existing = d.lastKnownLanEndpoints ?? [];
            // Remove stale duplicate entry for same host+port, insert new at front
            const deduped = existing.filter((e) => !(e.host === host && e.port === port));
            return {
              ...d,
              lastKnownLanEndpoints: [newEntry, ...deduped].slice(0, 3),
            };
          }),
        }));
      },
    }),
    {
      name: PAIRED_DESKTOPS_KEY,
      storage: createJSONStorage(() => secureStorage),
    },
  ),
);

// ─── Hydration hook ─────────────────────────────────────────────────────

/**
 * Returns true once the SecureStore-backed persist middleware has finished
 * rehydrating the paired-desktops list. Routing code that validates an
 * `activeDesktopId` against this list must wait for this; a cold-start
 * read would otherwise return an empty list and wrongly treat every
 * persisted activeDesktopId as stale.
 */
export function usePairedDesktopsHydrated(): boolean {
  const [hydrated, setHydrated] = useState<boolean>(() =>
    usePairedDesktopsStore.persist.hasHydrated(),
  );
  useEffect(() => {
    if (hydrated) return;
    const unsub = usePairedDesktopsStore.persist.onFinishHydration(() =>
      setHydrated(true),
    );
    return unsub;
  }, [hydrated]);
  return hydrated;
}
