/**
 * DPoP Interop Test: Go ↔ JS
 *
 * Reads testdata/dpop_vectors.json (generated by Go with GEN_DPOP_VECTORS=1)
 * and verifies the JS signDPoP function produces identical headers.
 *
 * Both sides use HMAC-SHA256(deviceTokenPlain, method+" "+path+" "+ts) as the
 * Ed25519 input per spec §7.4.  The device_token_hex field in each vector
 * carries the plaintext token used as the HMAC key.
 */

import { signDPoP } from '../dpop';

// Path relative to this test file.
const VECTORS_PATH = require('path').join(
  __dirname,
  '../../../../go-shared/tokenbind/testdata/dpop_vectors.json',
);

interface DPoPVector {
  ed_priv_hex: string;
  ed_pub_hex: string;
  device_token_hex: string;
  method: string;
  path: string;
  timestamp: number;
  header: string;
}

function fromHex(hex: string): Uint8Array {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return bytes;
}

describe('DPoP interop — Go ↔ JS', () => {
  let vectors: DPoPVector[];

  beforeAll(() => {
    try {
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      vectors = require(VECTORS_PATH);
    } catch {
      vectors = [];
    }
  });

  it('vector file exists and has entries', () => {
    expect(vectors.length).toBeGreaterThan(0);
  });

  /**
   * JS self-consistency: signDPoP produces a header that splits into exactly
   * two parts (base64url-sig.timestamp). This tests JS internal consistency
   * regardless of Go compatibility.
   */
  it('JS produces well-formed DPoP headers for each vector key', () => {
    for (let i = 0; i < vectors.length; i++) {
      const v = vectors[i];
      const edPriv = fromHex(v.ed_priv_hex);
      const deviceToken = fromHex(v.device_token_hex);
      const header = signDPoP(edPriv, deviceToken, v.method, v.path, v.timestamp);
      const parts = header.split('.');
      expect(parts.length).toBe(2);
      expect(parts[1]).toBe(String(v.timestamp));
    }
  });

  /**
   * Cross-implementation check: JS header must exactly match Go-generated header.
   *
   * Both sides now use HMAC-SHA256(deviceTokenPlain, method+" "+path+" "+ts)
   * as the Ed25519 input per spec §7.4.  No divergence is expected.
   */
  it('JS header matches Go-generated header', () => {
    const mismatches: string[] = [];
    for (let i = 0; i < vectors.length; i++) {
      const v = vectors[i];
      const edPriv = fromHex(v.ed_priv_hex);
      const deviceToken = fromHex(v.device_token_hex);
      const jsHeader = signDPoP(edPriv, deviceToken, v.method, v.path, v.timestamp);
      if (jsHeader !== v.header) {
        mismatches.push(
          `vector ${i} (${v.method} ${v.path}): JS="${jsHeader}" Go="${v.header}"`,
        );
      }
    }
    expect(mismatches).toEqual([]);
  });
});
